xbmc/repo-scripts

service.subtitles.podnapisi/addon.xml, service.subtitles.podnapisi/changelog.txt, service.subtitles.podnapisi/resources/lib/pn_utilities.py, service.subtitles.podnapisi/service.py
5.4.0
- use new API for better search and easier download.
=> [service.subtitles.podnapisi] -v5.4.0

script.xbmc.unpausejumpback/addon.xml, script.xbmc.unpausejumpback/changelog.txt, script.xbmc.unpausejumpback/resources/language/Bulgarian/strings.xml
- added bulgarian translation - thx to @NEOhidra (you can do the PR directly to the repo-scripts repo here in the future...)
=> [script.xbmc.unpausejumpback] 2.3.3

service.subtitles.opensubtitles/addon.xml, service.subtitles.opensubtitles/changelog.txt, service.subtitles.opensubtitles/resources/language/Chinese (Simple)/strings.po, service.subtitles.opensubtitles/service.py
5.0.13
- Fix for Greek subtitles, thx host505
5.0.12
- compare season and episode and display only matching results
=> [service.subtitles.opensubtitles] -v 5.0.13

service.subtitles.opensubtitles/addon.xml, service.subtitles.opensubtitles/changelog.txt, service.subtitles.opensubtitles/service.py
5.0.14
- Fix for Portuguese (Brazil) broken by 42f6ec9, thx host505
=> [service.subtitles.opensubtitles] -v 5.0.14

script.xbmc.unpausejumpback/addon.xml, script.xbmc.unpausejumpback/changelog.txt
=> [script.xbmc.unpausejumpback] 2.3.4

script.module.t1mlib/addon.xml, script.module.t1mlib/changelog.txt, script.module.t1mlib/lib/t1mlib.py, script.module.t1mlib/readme.txt
Added functions and subtitle handling
=> [script.module.t1mlib] 1.0.12 added functions

script.xbmc.boblight/addon.xml, script.xbmc.boblight/changelog.txt, script.xbmc.boblight/default.py
=> [script.xbmc.boblight] 2.0.14

script.xbmc.boblight/README, script.xbmc.boblight/addon.xml, script.xbmc.boblight/changelog.txt, script.xbmc.boblight/default.py, script.xbmc.boblight/resources/lib/boblight.py, script.xbmc.boblight/resources/lib/settings.py, script.xbmc.boblight/resources/lib/tools.py
This time with rebrand :) - This also adds tvos support.
=> [script.xbmc.boblight] 2.0.15

script.module.autocompletion/addon.xml, script.module.autocompletion/changelog.txt, script.module.autocompletion/lib/AutoCompletion.py
quick bugfix release, sorry for the inconvenience.
=> script.module.autocompletion 1.1.2

script.extendedinfo/changelog.txt, script.extendedinfo/resources/lib/process.py
Remove autocompletion for older Kodi versions (since it is not possible to detect whether HIDDEN_INPUT is set.)
=> [helix] script.extendedinfo 3.1.4

script.audiobooks/addon.xml, script.audiobooks/changelog.txt, script.audiobooks/plugin.py, script.audiobooks/resources/lib/audiobook.py, script.audiobooks/resources/lib/bookplayer.py
Changelog:
v1.4.0 (2016-03-19)
- Order Books by title if available, otherwise file name
- Support folder.jpg and cover.jpg files
- Improve end of book detection for multiple file books
- Prevent the lyrics being searched for audiobooks
For Releases Gotham and beyond
=> [script.audiobooks] 1.4.0

service.subtitles.subsfactory/addon.xml, service.subtitles.subsfactory/changelog.txt, service.subtitles.subsfactory/service.py
hi, new version with several bugfix
=> [service.subtitles.subsfactory] 1.0.2

service.subtitles.subtitool/addon.xml, service.subtitles.subtitool/changelog.txt, service.subtitles.subtitool/resources/language/English/strings.po, service.subtitles.subtitool/resources/lib/SubTiTool.py, service.subtitles.subtitool/service.py
=> [service.subtitles.subtitool] 1.1.2

service.nextup.notification/addon.xml, service.nextup.notification/resources/lib/NextUpInfo.py
Fix an issue introduced in the last version
=> [service.nextup.notification] 1.0.17

service.subtitles.subspedia/addon.xml, service.subtitles.subspedia/changelog.txt, service.subtitles.subspedia/service.py
=> [service.subtitles.subspedia] 1.0.1

script.extendedinfo/addon.xml, script.extendedinfo/changelog.txt, script.extendedinfo/resources/lib/Trakt.py, script.extendedinfo/resources/lib/WindowManager.py, script.extendedinfo/resources/lib/YouTube.py, script.extendedinfo/resources/lib/dialogs/DialogEpisodeInfo.py, script.extendedinfo/resources/lib/process.py, script.extendedinfo/resources/skins/Default/1080i/script-ExtendedInfo Script-DialogInfo.xml, script.extendedinfo/resources/skins/Default/1080i/script-ExtendedInfo Script-DialogVideoInfo.xml, script.extendedinfo/resources/skins/Default/1080i/script-ExtendedInfo Script-YoutubeList.xml
Some obvious fixes, mostly caused by code refactoring.
=> script.extendedinfo 5.0.1

script.artistslideshow/addon.xml, script.artistslideshow/changelog.txt, script.artistslideshow/default.py, script.artistslideshow/resources/common/fileops.py
updated code to reduce API calls to external sites
=> [script.artistslideshow] 1.8.8

service.subtitles.subtitool/addon.xml, service.subtitles.subtitool/changelog.txt, service.subtitles.subtitool/resources/lib/SubTiTool.py
Some improvements in the search functionality
=> [service.subtitles.subtitool] 1.1.3

script.audiobooks/addon.xml, script.audiobooks/changelog.txt, script.audiobooks/cleancovercache.py, script.audiobooks/deletedb.py, script.audiobooks/plugin.py, script.audiobooks/resources/lib/audiobook.py, script.audiobooks/resources/lib/bookplayer.py, script.audiobooks/resources/lib/database.py, script.audiobooks/resources/lib/settings.py
Please can I have the following update merged.
This includes the changes requested to:
1) Remove the double underscore variable names https://github.com/xbmc/repo-scripts/pull/62#discussion-diff-57632054
2) Correct imports to not update system path https://github.com/xbmc/repo-scripts/pull/61#issuecomment-198761117
3) Remove the provides for non plugins https://github.com/xbmc/repo-scripts/pull/64#discussion-diff-56757247
Which have been made on previous submissions that I agreed I would fix.
Thanks, Rob
=> [script.audiobooks] 1.4.1

script.ebooks/addon.xml, script.ebooks/changelog.txt, script.ebooks/cleancovercache.py, script.ebooks/deletedb.py, script.ebooks/plugin.py, script.ebooks/resources/lib/database.py, script.ebooks/resources/lib/ebook.py, script.ebooks/resources/lib/epub/opf.py, script.ebooks/resources/lib/opds.py, script.ebooks/resources/lib/textviewer.py
Please can I have the following update merged.
This includes the changes requested to:
1) Remove the double underscore variable names https://github.com/xbmc/repo-scripts/pull/62#discussion-diff-57632054
2) Correct imports to not update system path https://github.com/xbmc/repo-scripts/pull/61#issuecomment-198761117
3) Remove the provides for non plugins https://github.com/xbmc/repo-scripts/pull/64#discussion-diff-56757247
Which have been made on previous submissions that I agreed I would fix.
Thanks, Rob
=> [script.ebooks] 1.2.1

script.sleep/addon.xml, script.sleep/changelog.txt, script.sleep/default.py, script.sleep/detect.py, script.sleep/resources/language/English/strings.po, script.sleep/resources/lib/overlay.py, script.sleep/resources/lib/settings.py, script.sleep/resources/lib/timer.py, script.sleep/resources/settings.xml, script.sleep/screensaver.py, script.sleep/service.py
Please can I have the following update merged.
This includes the changes requested to:
1) Remove the double underscore variable names https://github.com/xbmc/repo-scripts/pull/62#discussion-diff-57632054
2) Correct imports to not update system path https://github.com/xbmc/repo-scripts/pull/61#issuecomment-198761117
3) Remove the provides for non plugins https://github.com/xbmc/repo-scripts/pull/64#discussion-diff-56757247
Which have been made on previous submissions that I agreed I would fix.
Thanks, Rob
=> [script.sleep] 1.1.0

service.subtitles.subtitool/addon.xml, service.subtitles.subtitool/changelog.txt, service.subtitles.subtitool/resources/lib/SubTiTool.py
Some improvements in the search functionality
=> [service.subtitles.subtitool] 1.1.4

service.subtitles.legendasdivx/addon.xml, service.subtitles.legendasdivx/changelog.txt, service.subtitles.legendasdivx/service.py
_newtemp variable without decode utf-8 was causing issues with accents.
code cleanup
=> [service.subtitles.legendasdivx] 0.2.6

service.subtitles.legendasdivx/addon.xml, service.subtitles.legendasdivx/changelog.txt, service.subtitles.legendasdivx/service.py, service.subtitles.pipocas/addon.xml, service.subtitles.pipocas/changelog.txt, service.subtitles.pipocas/service.py
Addon DEBUG with a bug when it's turned on. My bad...
=> [service.subtitles.legendasdivx] 0.2.7

service.subtitles.subsfactory/addon.xml, service.subtitles.subsfactory/changelog.txt, service.subtitles.subsfactory/service.py
=> [service.subtitles.subsfactory] 1.0.3

script.tvtunes/addon.xml, script.tvtunes/advsettings.py, script.tvtunes/changelog.txt, script.tvtunes/resources/lib/upload.py
Please can I have the following small update merged in. (Prevents needless processing)
Thanks,
Rob
=> [script.tvtunes] 6.3.1

script.colorbox/Readme.md, script.colorbox/addon.xml, script.colorbox/changelog.txt, script.colorbox/default.py, script.colorbox/resources/lib/Utils.py
Hopefully within guidelines for 1 commit per pull.
=> [script.colorbox] 1.0.10

script.ebooks/addon.xml, script.ebooks/changelog.txt, script.ebooks/resources/lib/ebook.py, script.ebooks/resources/lib/epub/opf.py
Please can I have the following merged, it fixes support for people running Kodi with Python 2.6
Thanks,
Rob
=> [script.ebooks] 1.2.2

script.trakt/addon.xml, script.trakt/changelog.txt, script.trakt/script.py, script.trakt/service.py, script.trakt/traktapi.py
Fix for one bug I overlooked when testing 3.1.5
=> [script.trakt] 3.1.6

service.subtitles.torec/README.md, service.subtitles.torec/addon.xml, service.subtitles.torec/changelog.txt, service.subtitles.torec/resources/lib/TorecSubtitlesDownloader.py, service.subtitles.torec/service.py
Hey,
This pull request mainly handles breaking changes in the subtitle provider site
=> [service.subtitles.torec] 1.0.8

script.skin.helper.service/README.md, script.skin.helper.service/addon.xml, script.skin.helper.service/default.py, script.skin.helper.service/plugin.py, script.skin.helper.service/resources/lib/ArtworkUtils.py, script.skin.helper.service/resources/lib/BackgroundsUpdater.py, script.skin.helper.service/resources/lib/BackupRestore.py, script.skin.helper.service/resources/lib/ListItemMonitor.py, script.skin.helper.service/resources/lib/MainModule.py, script.skin.helper.service/resources/lib/SearchDialog.py, script.skin.helper.service/resources/lib/Utils.py
update to 1.0.90 - quick follow up update with mostly optimizations.
Thanks in advance for updating!
=> [script.skin.helper.service] 1.0.90

script.skinshortcuts/README.md, script.skinshortcuts/addon.xml, script.skinshortcuts/changelog.txt, script.skinshortcuts/default.py, script.skinshortcuts/resources/docs/FAQ.md, script.skinshortcuts/resources/docs/advanced/Advanced Usage.md, script.skinshortcuts/resources/docs/advanced/Custom shortcut properties.md, script.skinshortcuts/resources/docs/advanced/External editing.md, script.skinshortcuts/resources/docs/advanced/Managing backgrounds.md, script.skinshortcuts/resources/docs/advanced/Managing widgets.md, script.skinshortcuts/resources/docs/advanced/Overriding an action.md, script.skinshortcuts/resources/docs/advanced/Provide thumbnails.md, script.skinshortcuts/resources/docs/advanced/Templates.md, script.skinshortcuts/resources/docs/started/Getting Started.md, script.skinshortcuts/resources/language/Hebrew/strings.po, script.skinshortcuts/resources/lib/datafunctions.py, script.skinshortcuts/resources/lib/gui.py, script.skinshortcuts/resources/lib/library.py, script.skinshortcuts/resources/lib/nodefunctions.py, script.skinshortcuts/resources/lib/simpleeval.py, script.skinshortcuts/resources/lib/template.py, script.skinshortcuts/resources/lib/xmlfunctions.py, script.skinshortcuts/resources/shortcuts/overrides.xml
Latest version of the skinshortcuts script.
Thanks in advance for updating
=> [script.skinshortcuts] v.1.0.8

script.cinder/README.md, script.cinder/addon.xml, script.cinder/changelog.txt, script.cinder/resources/language/English/strings.po, script.cinder/resources/lib/CinderRandomPlayer.py, script.cinder/script.py
I'd like to make a minor set of updates:
- Improved random algorithm
- Added error handling for invalid configuration settings
- Added ability for finer granularity of user defined percentages
- Reformatted README.md to match GitHub markup
- Moved hardcoded error dialog messages to strings.po file
=> [script.cinder] 1.0.1

service.nextup.notification/addon.xml, service.nextup.notification/changelog.txt, service.nextup.notification/resources/lib/NextUpInfo.py
oops tvshowtitle is not available for episodes...use showtitle instead
=> [service.nextup.notification] 1.0.25

service.subtitles.subscenter/addon.xml, service.subtitles.subscenter/changelog.txt, service.subtitles.subscenter/resources/lib/SUBUtilities.py, service.subtitles.subtitle/addon.xml, service.subtitles.subtitle/changelog.txt, service.subtitles.subtitle/resources/lib/SUBUtilities.py
=> [service.subtitles.subscenter] 3.3.7 & [service.subtitles.subtitle] 4.4.2

script.service.next-episode/addon.xml, script.service.next-episode/changelog.txt, script.service.next-episode/libs/medialibrary.py, script.service.next-episode/libs/monitoring.py, script.service.next-episode/service.py
This PR updates `script.service.next-episode` addon to v. 1.1.0
=> [script.service.next-episode] 1.1.0

script.game.filmwise/addon.xml, script.game.filmwise/changelog.txt, script.game.filmwise/resources/lib/core.py
Fixes possible python script error
Thanks, Rob
=> [script.game.filmwise] 1.0.3

script.suitability/addon.xml, script.suitability/changelog.txt, script.suitability/resources/lib/scraper.py
Fixes possible python script error
Thanks, Rob
=> [script.suitability] 1.1.2

script.tvtunes/addon.xml, script.tvtunes/changelog.txt, script.tvtunes/resources/lib/library.py, script.tvtunes/resources/lib/themeFetcher.py, script.tvtunes/resources/lib/upload.py
Fixes a problem with Soundcloud support raised in the forum:
http://forum.kodi.tv/showthread.php?tid=214287&pid=2338099#pid2338099
Thanks, Rob
=> [script.tvtunes] 6.3.3

service.subtitles.subspedia/addon.xml, service.subtitles.subspedia/changelog.txt, service.subtitles.subspedia/service.py
=> [service.subtitles.subspedia] 1.0.2

script.filecleaner/addon.xml, script.filecleaner/changelog.txt, script.filecleaner/default.py, script.filecleaner/service.py
Bugfix/improvements release. Please let me know if there are any issues.
=> [script.filecleaner] 4.2.1

service.subtitles.torec/addon.xml, service.subtitles.torec/changelog.txt, service.subtitles.torec/resources/language/English/strings.po, service.subtitles.torec/resources/lib/SubtitleHelper.py, service.subtitles.torec/resources/lib/TorecSubtitlesDownloader.py, service.subtitles.torec/resources/settings.xml, service.subtitles.torec/service.py
* fixed some major changes with the provider (Torec) API 
* major code beautification refactor
=> [service.subtitles.torec] 1.0.9

script.pinsentry/addon.xml, script.pinsentry/changelog.txt, script.pinsentry/resources/lib/settings.py
This fixes the issue reported on the forum:
http://forum.kodi.tv/showthread.php?tid=228451&pid=2345121#pid2345121
Thanks, Rob
=> [script.pinsentry] 1.3.2

script.tvtunes/addon.xml, script.tvtunes/changelog.txt, script.tvtunes/resources/lib/upload.py
Theme check improvement.
Thanks, Rob
=> [script.tvtunes] 6.3.4

screensaver.video/addon.xml, screensaver.video/changelog.txt, screensaver.video/resources/language/English/strings.po, screensaver.video/resources/lib/settings.py, screensaver.video/resources/settings.xml, screensaver.video/resources/skins/Default/720p/screensaver-video-main.xml, screensaver.video/screensaver.py
Add option to display weather details.
Thanks, Rob
=> [screensaver.video] 1.4.2

service.watchedlist/addon.xml, service.watchedlist/changelog.txt, service.watchedlist/resources/language/English/strings.po, service.watchedlist/resources/language/German/strings.po, service.watchedlist/service.py
Please merge my fix for service.watchedlist
=> [service.watchedlist] 1.1.1

service.watchedlist/addon.xml, service.watchedlist/changelog.txt, service.watchedlist/service.py
Please merge my update of the addon service.watchedlist.
It circumvents a bug in the implementation of monitor: http://forum.kodi.tv/showthread.php?tid=210411&pid=2356399#pid2356399
=> [service.watchedlist] 1.1.2

script.module.kodi65/addon.xml, script.module.kodi65/changelog.txt, script.module.kodi65/lib/kodi65/dialogbaselist.py
Quick follow-up... Broke some important stuff.
=> [script.module.kodi65] 1.0.3

service.subtitles.subscene/addon.xml, service.subtitles.subscene/changelog.txt, service.subtitles.subscene/service.py
Fix HTTP proxy issue, check download errors
https://github.com/manacker/service.subtitles.subscene/pull/3
=> [service.subtitles.subscene] 1.7.1

script.myepisodes/addon.xml, script.myepisodes/changelog.txt, script.myepisodes/default.py, script.myepisodes/resources/lib/__init__.py, script.myepisodes/resources/lib/myepisodes.py
There was an issue in my first PR, the resources/lib folder was somehow missing.
=> [script.myepisodes] 1.2.8

script.videoextras/addon.xml, script.videoextras/advsettings.py, script.videoextras/changelog.txt, script.videoextras/resources/language/English/strings.po, script.videoextras/resources/lib/settings.py, script.videoextras/resources/settings.xml, script.videoextras/service.py
Please can I have the following update merged:
- Improve support when running on Python 2.6
- Allow Extras to be displayed when a movie completes
Thanks, Rob
=> [script.videoextras] 2.1.2

script.tvtunes/addon.xml, script.tvtunes/changelog.txt, script.tvtunes/resources/lib/settings.py, script.tvtunes/resources/lib/upload.py
Please can I have the following update merged, includes:
v6.3.5 (2016-07-29)
- Improve support when running on Python 2.6
- Support for Kodi v17
Thanks, Rob
=> [script.tvtunes] 6.3.5

script.cinder/README.md, script.cinder/addon.xml, script.cinder/changelog.txt, script.cinder/resources/language/English/strings.po, script.cinder/resources/lib/CinderRandomPlayer.py, script.cinder/scriptcontextmenuoption.py
Added "Run Cinder from here" context menu option.
=> [script.cinder] 1.0.2

script.artistslideshow/addon.xml, script.artistslideshow/changelog.txt, script.artistslideshow/default.py, script.artistslideshow/resources/language/German/strings.po
v.2.0.2
- fixed crash when using fuzzy local path with non-Windows option
- updated German strings
=> [Artist Slideshow] 2.0.2

script.tvtunes/addon.xml, script.tvtunes/changelog.txt, script.tvtunes/resources/lib/idLookup.py, script.tvtunes/resources/lib/themePlayer.py
Small fix to theme playing to update please.
Thanks
Rob
=> [script.tvtunes] 6.3.6

script.pinsentry/addon.xml, script.pinsentry/changelog.txt, script.pinsentry/plugin.py, script.pinsentry/resources/lib/mpaaLookup.py, script.pinsentry/service.py
Hi,
Please can I have the following update merged, it adds:
- Add support for Classification checks for Live TV/PVR
Thanks
Rob
=> [script.pinsentry] 2.1.0

service.subtitles.subscenter/addon.xml, service.subtitles.subscenter/changelog.txt, service.subtitles.subscenter/resources/language/English/strings.po, service.subtitles.subscenter/resources/lib/SUBUtilities.py, service.subtitles.subscenter/resources/lib/storageserverdummy.py, service.subtitles.subscenter/resources/settings.xml, service.subtitles.subscenter/service.py
Update service to work with site API
=> [service.subtitles.subscenter] 4.0.1

service.subtitles.subscenter/addon.xml, service.subtitles.subscenter/changelog.txt, service.subtitles.subscenter/resources/lib/SUBUtilities.py
=> [service.subtitles.subscenter] 4.0.2

service.subtitles.subscenter/addon.xml, service.subtitles.subscenter/changelog.txt, service.subtitles.subscenter/resources/language/Hebrew/strings.po, service.subtitles.subscenter/resources/lib/SUBUtilities.py, service.subtitles.subscenter/service.py, service.subtitles.subtitle/addon.xml, service.subtitles.subtitle/changelog.txt, service.subtitles.subtitle/resources/language/Hebrew/strings.po, service.subtitles.subtitle/resources/lib/SUBUtilities.py, service.subtitles.subtitle/resources/settings.xml, service.subtitles.subtitle/service.py
Added Hebrew translations and some minor fixes
=> [service.subtitles.subscenter] 4.0.3 && [service.subtitles.subtitle] 4.4.3

script.skinshortcuts/README.md, script.skinshortcuts/addon.xml, script.skinshortcuts/changelog.txt, script.skinshortcuts/default.py, script.skinshortcuts/resources/docs/FAQ.md, script.skinshortcuts/resources/docs/advanced/Advanced Usage.md, script.skinshortcuts/resources/docs/advanced/Context menu.md, script.skinshortcuts/resources/docs/advanced/Custom shortcut properties.md, script.skinshortcuts/resources/docs/advanced/Overriding icons.md, script.skinshortcuts/resources/docs/started/Management Dialog.md, script.skinshortcuts/resources/language/English/strings.po, script.skinshortcuts/resources/language/French/strings.po, script.skinshortcuts/resources/language/Spanish/strings.po, script.skinshortcuts/resources/lib/datafunctions.py, script.skinshortcuts/resources/lib/gui.py, script.skinshortcuts/resources/lib/library.py, script.skinshortcuts/resources/lib/nodefunctions.py, script.skinshortcuts/resources/lib/template.py, script.skinshortcuts/resources/lib/xmlfunctions.py, script.skinshortcuts/resources/shortcuts/overrides.xml
new stable version of skinshortcuts, thanks in advance for updating!
=> [script.skinshortcuts] 1.0.10

service.stinger.notification/README.md, service.stinger.notification/addon.xml, service.stinger.notification/changelog.txt
=> [service.stinger.notification] 1.0.1

service.subtitles.torec/addon.xml, service.subtitles.torec/changelog.txt, service.subtitles.torec/resources/lib/TorecSubtitlesDownloader.py
* fixed a breaking Host change for the target site
=> [service.subtitles.torec] 1.0.10

script.screensaver.football.panel/addon.xml, script.screensaver.football.panel/changelog.txt, script.screensaver.football.panel/interface.py, script.screensaver.football.panel/resources/lib/addonfileio.py, script.screensaver.football.panel/resources/lib/cache.py, script.screensaver.football.panel/resources/lib/common_addon.py
-Cache also applied to individual teams
-Bug fixing
-Reduce the load on the database site if no matches are available
Thanks
=> [script.screensaver.football.panel] 1.4.1

script.matchcenter/README.md, script.matchcenter/addon.xml, script.matchcenter/changelog.txt, script.matchcenter/main.py, script.matchcenter/resources/language/English/strings.po, script.matchcenter/resources/language/Portuguese/strings.po, script.matchcenter/resources/lib/eventdetails.py, script.matchcenter/resources/lib/ignoreleagues.py, script.matchcenter/resources/lib/leaguetables.py, script.matchcenter/resources/lib/livescores.py, script.matchcenter/resources/lib/mainmenu.py, script.matchcenter/resources/lib/matchhistory.py, script.matchcenter/resources/lib/tweets.py, script.matchcenter/resources/lib/utilities/addonfileio.py, script.matchcenter/resources/lib/utilities/cache.py, script.matchcenter/resources/lib/utilities/common_addon.py, script.matchcenter/resources/lib/utilities/ssutils.py, script.matchcenter/resources/lib/utilities/tweet.py, script.matchcenter/resources/settings.xml, script.matchcenter/resources/skins/default/720p/script-matchcenter-LeagueSelection.xml, script.matchcenter/resources/skins/default/720p/script-matchcenter-LeagueTables.xml, script.matchcenter/resources/skins/default/720p/script-matchcenter-MatchHistory.xml
Implements caching to reduce the load on the thesportsdb.com website and improves performance for less powerfull devices. Also implements "twitter history" based on the user input.
Thanks
=> [script.matchcenter] 2.1.0

service.subtitles.subscenter/addon.xml, service.subtitles.subscenter/changelog.txt, service.subtitles.subscenter/resources/lib/SUBUtilities.py
=> [service.subtitles.subscenter] 4.0.4

script.screensaver.football.panel/addon.xml, script.screensaver.football.panel/changelog.txt, script.screensaver.football.panel/interface.py, script.screensaver.football.panel/resources/lib/ignoreleagues.py, script.screensaver.football.panel/resources/lib/ssutils.py
-Fix English League One Table not showing
-Remove deprecated methods
Thanks
=> [script.screensaver.football.panel] 1.4.2

script.matchcenter/addon.xml, script.matchcenter/changelog.txt, script.matchcenter/resources/lib/eventdetails.py
Just some really small modifications to fix some bugs with past events
Thank you
=> [script.matchcenter] 2.1.2

service.subtitles.subsfactory/addon.xml, service.subtitles.subsfactory/changelog.txt, service.subtitles.subsfactory/service.py
bugfix for one tv show, thx
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuesly monitor your python coding …
=> [service.subtitles.subsfactory] 1.0.4

screensaver.digitalclock/addon.xml, screensaver.digitalclock/changelog.txt, screensaver.digitalclock/default.py, screensaver.digitalclock/resources/skins/default/720p/skin.estouchy.xml, screensaver.digitalclock/resources/skins/default/720p/skin.estuary.xml
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuesly monitor your python coding before submitting to repo.
- …
=> [screensaver.digitalclock] 3.7.0

service.subtitles.torec/addon.xml, service.subtitles.torec/changelog.txt, service.subtitles.torec/resources/lib/SubtitleHelper.py, service.subtitles.torec/resources/lib/TorecSubtitlesDownloader.py, service.subtitles.torec/service.py, service.subtitles.torec/tests/movie_tests.py, service.subtitles.torec/tests/tvshow_tests.py
updated the addon to support new parent website version (7.0) …
=> [service.subtitles.torec] 1.1.0

script.100fm/addon.py, script.100fm/addon.xml, script.100fm/api.py, script.100fm/changelog.txt, script.100fm/player.py
Add-on update - UI fine-tuning
Ignore empty data received from API …
=> script.100fm v0.2.3

service.subtitles.torec/addon.xml, service.subtitles.torec/changelog.txt, service.subtitles.torec/resources/lib/SubtitleHelper.py, service.subtitles.torec/resources/lib/TorecSubtitlesDownloader.py, service.subtitles.torec/tests/movie_tests.py, service.subtitles.torec/tests/tvshow_tests.py, service.subtitles.torec/tests/xbmc.py, service.subtitles.torec/tests/xbmcaddon.py
some minor bug fixes (download retries and inexistent tv show subtitles) …
=> [service.subtitles.torec] 1.1.1

service.subtitles.torec/addon.xml, service.subtitles.torec/changelog.txt, service.subtitles.torec/resources/lib/TorecSubtitlesDownloader.py
fixed download issue occurring to several users
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuesly monitor …
=> [service.subtitles.torec] 1.1.2

service.stinger.notification/addon.xml, service.stinger.notification/changelog.txt, service.stinger.notification/resources/language/English/strings.po, service.stinger.notification/resources/lib/chapters.py, service.stinger.notification/resources/lib/thechapterdb.py, service.stinger.notification/resources/lib/themoviedb.py, service.stinger.notification/resources/settings.xml, service.stinger.notification/service.py
- Add an option to set amount of time to display the notification
- Don't allow errors from web services to prevent the stinger notification …
=> [service.stinger.notification] 1.0.2

service.subtitles.torec/addon.xml, service.subtitles.torec/changelog.txt, service.subtitles.torec/resources/lib/TorecSubtitlesDownloader.py
another (hopefully better) fix for download link issue
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuesly …
=> [service.subtitles.torec] 1.1.3

service.subtitles.torec/addon.xml, service.subtitles.torec/changelog.txt, service.subtitles.torec/resources/lib/TorecSubtitlesDownloader.py
fixed broken search due to site API change …
=> [service.subtitles.torec] 1.1.4

service.subtitles.subtitle/addon.xml, service.subtitles.subtitle/changelog.txt, service.subtitles.subtitle/service.py
* Fix fetching IMDB id - by TheWiz
* Fetch list item data for external search - by burekas7 …
=> [service.subtitles.subtitle] 4.5.1

service.subtitles.subscenter/addon.xml, service.subtitles.subscenter/changelog.txt, service.subtitles.subscenter/service.py
=> [service.subtitles.subscenter] 4.1.2

script.skinshortcuts/README.md, script.skinshortcuts/addon.xml, script.skinshortcuts/changelog.txt, script.skinshortcuts/resources/lib/gui.py
Sorry to pr another update so soon after the last one, but a small bug affecting a limited number of users came to light when it got into a wider-number of peoples hand. This is a quick fix to ensure a particular value is a number before casting it to an int- the code will be properly refactored in a future update.
Note that I've not checked the first checkbox below as, in order to do what it does, the script writes an additional file to the skins directory. In all other ways, it complies with the add-on rules and piracy policy.
Thanks
- [add-on …
=> [script.skinshortcuts] 1.0.13

script.audio.profiles/addon.xml, script.audio.profiles/changelog.txt, script.audio.profiles/default.py, script.audio.profiles/resources/lib/debug.py, script.audio.profiles/resources/lib/dialog.py, script.audio.profiles/resources/skins/Default/720p/script-audio-profiles-menu.xml, script.audio.profiles/service.py
=> [script.audio.profiles] 1.1.1

service.subtitles.torec/addon.xml, service.subtitles.torec/changelog.txt, service.subtitles.torec/resources/lib/SubtitleHelper.py, service.subtitles.torec/resources/lib/TorecSubtitlesDownloader.py, service.subtitles.torec/service.py, service.subtitles.torec/tests/movie_tests.py
- added support for the new download code screen
- fix Manual Search, Empty Title&Kodi isn't playing (@burekas7) …
=> [service.subtitles.torec] 1.2.0

context.playrandomvideo/addon.xml, context.playrandomvideo/changelog.txt, context.playrandomvideo/context.py, script.playrandomvideos/README.md, script.playrandomvideos/addon.xml, script.playrandomvideos/changelog.txt, script.playrandomvideos/context.py, script.playrandomvideos/resources/language/English/strings.po, script.playrandomvideos/resources/lib/generators.py, script.playrandomvideos/resources/lib/listitembuilder.py, script.playrandomvideos/resources/lib/player.py, script.playrandomvideos/resources/lib/playrandom.py, script.playrandomvideos/resources/lib/pykodi.py, script.playrandomvideos/resources/lib/quickjson.py, script.playrandomvideos/resources/settings.xml, script.playrandomvideos/script.py
A big update for another add-on.
Thanks!
- Reworked to play through all videos in a list with minimal startup delay
- Merge context item and script
- A few updates for Krypton support
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these …
=> [script.playrandomvideos] 1.1.0

script.extendedinfo/addon.xml, script.extendedinfo/changelog.txt, script.extendedinfo/resources/lib/LastFM.py, script.extendedinfo/resources/lib/TheAudioDB.py, script.extendedinfo/resources/skins/Default/1080i/script-script.extendedinfo-DialogInfo.xml, script.extendedinfo/resources/skins/Default/1080i/script-script.extendedinfo-DialogVideoInfo.xml, script.extendedinfo/resources/skins/Default/1080i/script-script.extendedinfo-VideoList.xml, script.extendedinfo/resources/skins/Default/1080i/script-script.extendedinfo-YoutubeList.xml
=> [script.extendedinfo] 5.6.0

context.extendedinfo.dialog/addon.xml, context.extendedinfo.ratemedia/addon.xml
=> Krypton updates

weather.ozweather/addon.xml, weather.ozweather/changelog.txt, weather.ozweather/default.py, weather.ozweather/resources/lib/weatherzone.py
- Add Wind Speed/Direction support for the forecast data
- Bugfixes to cope with more different labels skins use - all thsi weather stuff could really do with some standardisation & proper docs!!
I'm still a bit new to the git subtree stuff, fingers crossed.  I had to use `--allow-unrelated-histories`  when doing this: `git pull --strategy subtree --squash weather.ozweather master`
=> [weather.ozweather] 0.8.8

service.subtitles.subscenter/addon.xml, service.subtitles.subscenter/changelog.txt, service.subtitles.subscenter/resources/lib/SUBUtilities.py
Bug fix, prevent filtering search results by year for tvshows …
=> [service.subtitles.subscenter] 4.1.3

script.artistslideshow/addon.xml, script.artistslideshow/changelog.txt, script.artistslideshow/default.py, script.artistslideshow/resources/language/English/strings.po, script.artistslideshow/resources/plugins/__init__.py, script.artistslideshow/resources/plugins/theaudiodb.py, script.artistslideshow/resources/settings.xml
v.2.0.4
- added option to use local fanart and folder image outside extrafanart
folder
- added MusicBrainz ID extraction from theaudiodb.com information
- added ArtistSlideshow.SimilarCount and ArtistSlideshow.AlbumCount to
skin properties
- fix for theaudiodb lookup when artists have ampersands in their name
- fix for artist name separation leaving extra spaces
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is …
=> [script.artistslideshow] 2.0.4

script.artistslideshow-helper/addon.xml, script.artistslideshow-helper/changelog.txt, script.artistslideshow-helper/default.py
v.0.4.4
- fix for crash when image migration is disabled
=> [script.artistslideshow-helper] 0.4.4

script.speedfaninfo/CHANGELOG.txt, script.speedfaninfo/addon.xml, script.speedfaninfo/default.py, script.speedfaninfo/resources/common/fileops.py, script.speedfaninfo/resources/language/English/strings.po, script.speedfaninfo/resources/settings.xml
v.0.7.5
- added option to run external script to generate log file
- added 'Other' option to sensor display
- added advanced setting for line read size
=> [speedfan info display] 0.7.5

script.artistslideshow/addon.xml, script.artistslideshow/changelog.txt, script.artistslideshow/default.py
note: 2.0.5 was never publicly released. That is intentional.
v.2.0.6
- removed some logging causing a unicode problem
- fix for crash when no valid JSON returned from theaudiodb.com
v.2.0.5
- reverted to old logic for checking for start of new artist (more reliable)
- fix for creation of empty artist folders when using fanart.jpg option
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise …
=> [script.artistslideshow] 2.0.6

script.module.phate89/addon.xml, script.module.phate89/changelog.txt
Remove the simplejson reference not needed anymore …
=> [script.module.phate89] 1.0.1

service.subtitles.subscenter/addon.xml, service.subtitles.subscenter/changelog.txt, service.subtitles.subscenter/service.py
=> [service.subtitles.subscenter] 4.1.4

service.nextup.notification/addon.xml, service.nextup.notification/library.py
=> [service.nextup.notification] 1.0.32

script.module.libmediathek3/LICENSE.txt, script.module.libmediathek3/addon.xml, script.module.libmediathek3/changelog.txt, script.module.libmediathek3/lib/libmediathek3.py, script.module.libmediathek3/lib/libmediathek3dialogs.py, script.module.libmediathek3/lib/libmediathek3listing.py, script.module.libmediathek3/lib/libmediathek3premadedirs.py, script.module.libmediathek3/lib/libmediathek3ttml2srt.py, script.module.libmediathek3/lib/libmediathek3utils.py, script.module.libmediathek3/lib/libmediathek3webvtt2srt.py, script.module.libmediathek3/resources/language/English/strings.po, script.module.libmediathek3/resources/language/German/strings.po, script.module.libmediathek3/resources/settings.xml
This is a new version of my mini framework, used by my add-ons.
=> [script.module.libmediathek3] v1.3.0

script.trakt/addon.xml, script.trakt/utilities.py
Update of the dependency and a small bugfix.
Please wait for script.module.trakt to be updated. …
=> [script.trakt] 2.1.9

service.subtitles.subdivx/addon.xml, service.subtitles.subdivx/changelog.txt, service.subtitles.subdivx/service.py
- Use html2text lib to scrape comments. Thanks Iván Ridao Freitas for help.
- Fix handling of movie path on filesystem. Thanks Santiago Ibarra for report.
- Enhance movie search performance and accuracy. Thanks Iván Ridao Freitas for report.
- Fix unzip performance using Kodi API facilities. Thanks Iván Ridao Freitas.
- More robust search for TV show episodes subtitles in the face of uneven metadata quality.
- Better handling of .ssa and .sub+.idx files. Stop recognizing .txt files as subtitles files.
- Kodi …
=> [service.subtitles.subdivx] 0.2.5

service.subtitles.subtitle/addon.xml, service.subtitles.subtitle/changelog.txt, service.subtitles.subtitle/resources/lib/SUBUtilities.py, service.subtitles.subtitle/service.py
* Add CAPTCH support
* Check item's media type …
=> [service.subtitles.subtitle] 4.6.0

script.module.libwdr/LICENSE.txt, script.module.libwdr/addon.xml, script.module.libwdr/changelog.txt, script.module.libwdr/lib/libwdr.py, script.module.libwdr/lib/libwdrhtmlparser.py, script.module.libwdr/lib/libwdrjsonparser.py, script.module.libwdr/lib/libwdrparser.py, script.module.libwdr/lib/libwdrrssparser.py
This is a scraper for http://www1.wdr.de/mediathek/video and websites which use the same framework. …
=> [script.module.libwdr] v1.0.0

service.subtitles.torec/addon.xml, service.subtitles.torec/changelog.txt, service.subtitles.torec/resources/lib/SubtitleHelper.py, service.subtitles.torec/resources/lib/TorecSubtitlesDownloader.py, service.subtitles.torec/tests/movie_tests.py, service.subtitles.torec/tests/tvshow_tests.py
Improved subtitle download speed significantly.
=> [service.subtitles.torec] 1.3.0

script.module.libswr/LICENSE.txt, script.module.libswr/addon.xml, script.module.libswr/changelog.txt, script.module.libswr/lib/libswr.py, script.module.libswr/lib/libswrparser.py
This is a scraper for http://swrmediathek.de/. …
=> [script.module.libswr] v1.0.0

script.module.libndr/LICENSE.txt, script.module.libndr/addon.xml, script.module.libndr/changelog.txt, script.module.libndr/lib/libndr.py, script.module.libndr/lib/libndrjsonparser.py, script.module.libndr/lib/libndrparser.py
This is an scraper for http://www.ndr.de/mediathek/. …
=> [script.module.libndr] v1.0.0

screensaver.digitalclock/addon.xml
Fixing my mistake regarding dependencies.
I do apologize for this, I misunderstood how they work, but now Ronie has explained it to me and this won't happen again. …
=> [screensaver.digitalclock] 4.0.1

script.module.libbr/LICENSE.txt, script.module.libbr/addon.xml, script.module.libbr/changelog.txt, script.module.libbr/lib/libbr.py, script.module.libbr/lib/libbrjsonparser.py
This is a scraper for the BR Mediathek (http://www.br.de/mediathek/video/index.html). It uses the JSON API of the Android app. …
=> [script.module.libbr] v1.0.0

script.module.libzdf/LICENSE.txt, script.module.libzdf/addon.xml, script.module.libzdf/changelog.txt, script.module.libzdf/lib/libzdf.py, script.module.libzdf/lib/libzdfjsonparser.py
This is a scraper for the ZDF Mediathek https://www.zdf.de/. …
=> [script.module.libzdf] v2.0.0

script.module.libkika/LICENSE.txt, script.module.libkika/addon.xml, script.module.libkika/changelog.txt, script.module.libkika/lib/libkika.py, script.module.libkika/lib/libkikajsonparser.py
This is a scraper for the kids channel KiKa (http://www.kika.de/). …
=> [script.module.libkika] v1.0.0

script.module.libmdr/LICENSE.txt, script.module.libmdr/addon.xml, script.module.libmdr/changelog.txt, script.module.libmdr/lib/libmdr.py, script.module.libmdr/lib/libmdrhtmlparser.py, script.module.libmdr/lib/libmdrmetaparser.py, script.module.libmdr/resources/language/English/strings.po, script.module.libmdr/resources/language/German/strings.po
This is a scraper for the MDR Mediathek (http://www.mdr.de/mediathek/index.html). …
=> [script.module.libmdr] v1.0.0

script.module.libdaserste/LICENSE.txt, script.module.libdaserste/addon.xml, script.module.libdaserste/changelog.txt, script.module.libdaserste/lib/libdaserste.py, script.module.libdaserste/lib/libdaserstejsonparser.py
This is a scraper lib for http://mediathek.daserste.de/. …
=> [script.module.libdaserste] v1.0.0

script.module.libsr/LICENSE.txt, script.module.libsr/addon.xml, script.module.libsr/changelog.txt, script.module.libsr/lib/libsr.py, script.module.libsr/lib/libsrjsonparser.py
This is a scraper for the SR Mediathek (http://sr-mediathek.de/). …
=> [script.module.libsr] v1.0.0

script.module.libhr/LICENSE.txt, script.module.libhr/addon.xml, script.module.libhr/changelog.txt, script.module.libhr/lib/libhr.py, script.module.libhr/lib/libhrparser.py
This is the scraper lib for the HR Mediathek http://www.hr-online.de/website/fernsehen/sendungen/. …
=> [script.module.libhr] v1.0.0

script.module.lib3sat/LICENSE.txt, script.module.lib3sat/addon.xml, script.module.lib3sat/changelog.txt, script.module.lib3sat/lib/lib3sat.py
This is a scraper for the 3sat Mediathek (http://www.3sat.de/mediathek/): …
=> [script.module.lib3sat] v1.0.0

script.module.mediathekxmlservice/LICENSE.txt, script.module.mediathekxmlservice/addon.xml, script.module.mediathekxmlservice/changelog.txt, script.module.mediathekxmlservice/lib/mediathekxmlservice.py, script.module.mediathekxmlservice/lib/mediathekxmlservicelisting.py, script.module.mediathekxmlservice/lib/mediathekxmlserviceplay.py
This is a scraper for various Mediathek add-ons. …
=> [script.module.mediathekxmlservice] v1.0.0

script.module.libard/LICENSE.txt, script.module.libard/addon.xml, script.module.libard/changelog.txt, script.module.libard/lib/libard.py, script.module.libard/lib/libardjsonparser.py, script.module.libard/lib/libardlisting.py, script.module.libard/lib/libardplayer.py, script.module.libard/lib/libardrssparser.py
This is a scraper for the ARD Mediathek (http://ardmediathek.de/). …
=> [script.module.libard] v1.0.0

script.audio.profiles/addon.xml, script.audio.profiles/changelog.txt, script.audio.profiles/default.py, script.audio.profiles/resources/language/English/strings.po, script.audio.profiles/resources/language/Italian/strings.po, script.audio.profiles/resources/lib/debug.py, script.audio.profiles/resources/settings.xml, script.audio.profiles/service.py
=> [script.audio.profiles] 1.2.0

script.video.funimationnow/addon.xml, script.video.funimationnow/changelog.txt, script.video.funimationnow/resources/language/resource.language.en_gb/strings.po, script.video.funimationnow/resources/language/resource.language.en_us/strings.po, script.video.funimationnow/resources/lib/gui/maingui.py, script.video.funimationnow/resources/lib/gui/showgui.py, script.video.funimationnow/resources/lib/gui/watchlistgui.py, script.video.funimationnow/resources/lib/modules/funimationnow.py, script.video.funimationnow/resources/lib/modules/player.py, script.video.funimationnow/resources/lib/modules/utils.py, script.video.funimationnow/resources/settings.xml
Vendor changed API and unbound the subtitles from the video, providing a new URL for subtitles.
Video links should now be updated as well as user should have a new setting to enable/disable subtitles.
This fix corrects:
The ability to play videos.
The ability to change audio languages.
- This add-on repository has …
=> [script.video.funimationnow] 0.1.3

service.subtitles.traduttorianonimi/README.md, service.subtitles.traduttorianonimi/addon.xml, service.subtitles.traduttorianonimi/changelog.txt, service.subtitles.traduttorianonimi/resources/lib/TraduttoriAnonimi.py, service.subtitles.traduttorianonimi/service.py
[service.subtitles.traduttorianonimi] v2.1.0
short changelog:
--code cleanup
-- now you can choose the best version (sync) of a subtitle ( if available)
=> [service.subtitles.traduttorianonimi] v2.1.0

script.module.thetvdb/README.md, script.module.thetvdb/addon.xml, script.module.thetvdb/lib/thetvdb.py
1) implemented caching of data (by use of script.module.simplecache)
2) pep8 compliance (monitored by codacy)
- [X ] Each add-on submission should be a single commit with using the following style: [sciprt.foo.bar] v1.0.0
=> [script.module.thetvdb] 1.0.12

service.linuxwhatelse.notify/addon.xml
Markes this addon as broken for now (will be deleted later) …
=> [service.linuxwhatelse.notify] 1.1.3

script.module.xbmcutil/addon.xml, script.module.xbmcutil/changelog.txt, script.module.xbmcutil/lib/xbmcutil/listitem.py
Switch to using kodi constants variable for sort instead of hard coding them
=> [script.module.xbmcutil] 3.0.3

screensaver.digitalclock/addon.xml, screensaver.digitalclock/changelog.txt, screensaver.digitalclock/default.py
4.0.3
- Better representation of CPU usage on multiple core systems …
=> [screensaver.digitalclock] 4.0.3

script.filecleaner/addon.xml, script.filecleaner/changelog.txt
Marking the addon as broken in favor of the Krypton version, as per request (https://github.com/xbmc/repo-scripts/pull/435). …
=> [script.filecleaner] 4.2.2

service.fussballpopup/addon.xml, service.fussballpopup/menu.py, service.fussballpopup/service.py
forgot to disable that old games are shown (Used it for testing if the Plugin is working after ´removing duplicate code from the orginal pr
Sorry …
=> [service.fussballpopup] 0.3.11

script.module.libzdf/addon.xml, script.module.libzdf/changelog.txt, script.module.libzdf/lib/libzdfjsonparser.py
The old API key is invalid, this version has a new one. I'll monitor other changes. …
=> [script.module.libzdf] v2.0.1

service.linuxwhatelse.notify/addon.xml, service.linuxwhatelse.notify/addon/routes/call.py, service.linuxwhatelse.notify/service.py
Reworked the http service implementation as it kinda froze up at times (still no clue why, maybe even a python httpserver bug).
Now using `ThreadingMixIn` which works nicely (so far at least)
Rest is just source prettyfication :)
- This add-on repository has automated code guideline check which could help you improve your …
=> [service.linuxwhatelse.notify] v2.1.0

script.module.arrow/addon.xml, script.module.arrow/changelog.txt, script.module.arrow/lib/HISTORY.md, script.module.arrow/lib/README.rst, script.module.arrow/lib/arrow/__init__.py, script.module.arrow/lib/arrow/api.py, script.module.arrow/lib/arrow/arrow.py, script.module.arrow/lib/arrow/factory.py, script.module.arrow/lib/arrow/formatter.py, script.module.arrow/lib/arrow/locales.py, script.module.arrow/lib/arrow/parser.py, script.module.arrow/lib/arrow/util.py
~~Same as available for Isengard, just for earlier versions. The version number is the same, if that's a problem please let me know.~~
https://github.com/xbmc/repo-scripts/tree/isengard/script.module.arrow
=> [script.module.arrow] 0.10.0

script.musicfinder/LICENSE, script.musicfinder/README.md, script.musicfinder/addon.xml, script.musicfinder/changelog.txt, script.musicfinder/default.py, script.musicfinder/resources/language/English/strings.po
Pull request for https://github.com/xbmc/repo-scripts/issues/453
Please check thorough. Code was not done by me, I'm just doing the PR.
=> [script.musicfinder] 1.0.0

service.subtitles.titlovi/README.md, service.subtitles.titlovi/addon.xml, service.subtitles.titlovi/changelog.txt, service.subtitles.titlovi/resources/lib/ti_utilities.py, service.subtitles.titlovi/service.py
Pull request for https://github.com/xbmc/repo-scripts/issues/457
Please check thorough. Code was not done by me, I'm just doing the PR.
I also took the liberty to grab the lastest version f63aabfb6a7b6705fef34673139b13ce8e873911 instead of the one asked for. (just changelog changed)
=> [service.subtitles.titlovi] 1.1.2

script.artwork.downloader/lib/provider/tmdb.py
Fix movie search with year on TMDB : 
http://forum.kodi.tv/showthread.php?tid=114633&pid=2392098#pid2392098
=> Fix TMDB search with year

script.artistslideshow/README.txt, script.artistslideshow/addon.xml, script.artistslideshow/changelog.txt, script.artistslideshow/default.py, script.artistslideshow/resources/plugins/__init__.py, script.artistslideshow/resources/plugins/lastfm.py, script.artistslideshow/resources/plugins/local.py, script.artistslideshow/resources/plugins/theaudiodb.py
v.2.0.7
- added last.fm bio file as option for finding Musicbrainz ID
- moved all Musicbrainz ID functions into plugins
- fix so featured artist parsing from song name is case insensitive
- strip errant linefeed from readfile on musicbrainz.nfo (where
manually created)
- This add-on repository has automated code guideline …
=> [AS 2.0.7]

script.artwork.downloader/lib/provider/tmdb.py
=> Revert "Fix TMDB search with year"

script.module.libzdf/addon.xml, script.module.libzdf/changelog.txt, script.module.libzdf/lib/libzdfjsonparser.py
This is the second take (sorry for the new PR, I'm still trying to figure out Git). 
This version respondes to another change to the API system. A permanent change is on the way. …
=> [script.module.libzdf] v2.0.2

service.tvh.manager/addon.xml, service.tvh.manager/changelog.txt, service.tvh.manager/default.py, service.tvh.manager/resources/language/English/strings.po, service.tvh.manager/resources/language/German/strings.po, service.tvh.manager/resources/language/Polish/strings.po, service.tvh.manager/resources/settings.xml
[service.tvh.manager] v0.3.21 update
from changelog.txt: Change option from excluded ports to monitored ports in network settings
=> [service.tvh.manager] v0.3.21 update

PULL_REQUEST_TEMPLATE.md
title says it all.
Also not sure if requiring a single commit makes sense since we can squash the commits when merging. I've left it at as it is though.
cheers
=> Fix small typo in PULL_REQUEST_TEMPLATE.md

script.module.kodiswift/addon.xml, script.module.kodiswift/changelog.txt, script.module.kodiswift/lib/kodiswift/listitem.py
- Set `listitem.is_folder` to `False` when setting `listitem.is_playable` to `True`.
=> [script.module.kodiswift] 0.0.8

service.subtitles.torec/addon.xml, service.subtitles.torec/changelog.txt, service.subtitles.torec/resources/lib/TorecSubtitlesDownloader.py
* Fixed broken download due to site changes and added some future changes protection
=> [service.subtitles.torec] 1.3.1

script.service.janitor/addon.xml, script.service.janitor/changelog.txt, script.service.janitor/default.py, script.service.janitor/utils.py
=> [script.service.janitor] 4.3.1

service.watchedlist/addon.xml, service.watchedlist/changelog.txt, service.watchedlist/manual.py, service.watchedlist/resources/language/English/strings.po, service.watchedlist/resources/language/German/strings.po, service.watchedlist/resources/lib/utils.py, service.watchedlist/resources/settings.xml, service.watchedlist/service.py
Pull request for updates on the addon service.watchedlist:
* Added verbosity option for graphical user notifications
* Added limitation of number of backup files
=> [service.watchedlist] 1.1.3

script.module.web-pdb/addon.xml, script.module.web-pdb/libs/web_pdb/static/js/web-console.js, script.module.web-pdb/libs/web_pdb/wsgi_app.py
Port of changes from the mainstream Web-PDB package
- [ x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [ x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the …
=> "[script.module.web-pdb] 1.3.1"

script.colorbox/addon.xml, script.colorbox/default.py
=> [script.colorbox] 2.0.1

service.subtitles.napisy24pl/addon.xml, service.subtitles.napisy24pl/changelog.txt, service.subtitles.napisy24pl/resources/language/English/strings.po, service.subtitles.napisy24pl/resources/language/Polish/strings.po, service.subtitles.napisy24pl/resources/lib/NapisyUtils.py, service.subtitles.napisy24pl/resources/settings.xml, service.subtitles.napisy24pl/service.py
Complete rewrite of the code, now allows to search tv-shows more accurately and faster.  …
=> [service.subtitles.napisy24pl] 2.0.1

service.fhemcinema/addon.py, service.fhemcinema/addon.xml, service.fhemcinema/changelog.txt, service.fhemcinema/resources/language/English/strings.xml, service.fhemcinema/resources/language/German/strings.xml, service.fhemcinema/resources/language/Italian/strings.xml, service.fhemcinema/resources/settings.xml
While playing with the CinemaVision addon i found a problem as follows.
I have configured the Home Cinema Automation addon to switch on my lights when playback stops. The CinemaVision addon plays multiple trailers and video bumpers before starting the actual movie. This leads to sort of light on, off, on, off situation.
This pull request adds a setting which allows to delay the execution of the stop command. This prevents the flicker and only executes that command if the movie was stopped for the given time.
Defaults to zero so this is backward compatible behavior.
- [add-on …
=> [service.fhemcinema] 0.3.1

script.trakt/addon.xml, script.trakt/changelog.txt, script.trakt/resources/language/English/strings.po, script.trakt/resources/lib/kodiUtilities.py, script.trakt/resources/lib/service.py, script.trakt/resources/settings.xml, script.trakt/tests/test_kodiUtilities.py
Some basic updates
(http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.
=> [script.trakt] 3.1.11

script.cdartmanager/addon.xml, script.cdartmanager/changelog.txt, script.cdartmanager/default.py, script.cdartmanager/lib/download.py, script.cdartmanager/lib/ftv_scraper.py, script.cdartmanager/lib/gui.py
Bugfix: no cdART was found in fanart.tv JSON-Data
- [ X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0
=> [script.cdartmanager] v4.2.1

script.service.janitor/addon.xml, script.service.janitor/default.py, script.service.janitor/resources/settings.xml, script.service.janitor/utils.py
Bugfix release only. Several minor bugs have been fixed. …
=> [script.service.janitor] 4.3.2

service.tvh.manager/README.md, service.tvh.manager/addon.xml, service.tvh.manager/changelog.txt, service.tvh.manager/default.py, service.tvh.manager/resources/language/English/strings.po, service.tvh.manager/resources/language/German/strings.po, service.tvh.manager/resources/language/Polish/strings.po, service.tvh.manager/resources/lib/shutdown.sh, service.tvh.manager/resources/lib/tools.py, service.tvh.manager/resources/settings.xml
0.3.22 update
- Some changes within the code structure made, so the addon also works in suspend mode.
- Routines from module requests introduced
- NVRAM Wakeup removed
- more robust method of LibreElec/OpenElec detection implemented
- This add-on repository has automated code guideline check which could help you improve …
=> [service.tvh.manager] v0.3.22

script.xbmc.boblight/addon.xml, script.xbmc.boblight/changelog.txt, script.xbmc.boblight/resources/lib/tools.py
This adds Support for Windows 64bit Version of kodi.
Binary libboblight was compiled from my tree (which i added visual Studio Support to) here:
https://github.com/Memphiz/boblight/commits/windows
binary dll for winx64 is uploaded accordingly
=> [script.xbmc.boblight] 2.0.17

script.artistslideshow/addon.xml, script.artistslideshow/changelog.txt, script.artistslideshow/resources/plugins/fanarttv.py, script.artistslideshow/resources/plugins/htbackdrops.py, script.artistslideshow/resources/plugins/kodi.py, script.artistslideshow/resources/plugins/lastfm.py, script.artistslideshow/resources/plugins/theaudiodb.py
v.2.0.8
- fix for crash if Kodi plugin tries to load bio with oddly encoded
characters
- fix for crash if a services cache file contains a string that doesn't
evaluate to int …
=> [Artist Slideshow] v2.0.8

screensaver.atv4/addon.xml, screensaver.atv4/resources/settings.xml
Fix wrong setting as pointed by @MartijnKaijser
=> [screensaver.atv4] 1.4.1

script.colorbox/addon.xml, script.colorbox/default.py, script.colorbox/resources/lib/Utils.py
=> [script.colorbox] 2.0.2

script.colorbox/addon.xml, script.colorbox/default.py, script.colorbox/resources/lib/Utils.py
- quick rework see skin.adonic
=> script.colorbox 2.0.3

service.subtitles.itasa/addon.xml, service.subtitles.itasa/changelog.txt, service.subtitles.itasa/service.py
=> [service.subtitles.itasa] 1.0.3

script.module.neverwise/addon.xml, script.module.neverwise/changelog.txt, script.module.neverwise/lib/neverwise.py, script.module.neverwise/resources/language/English/strings.po, script.module.neverwise/resources/language/Italian/strings.po
Update needed for a plugin addon …
=> [script.module.neverwise] v1.1.1

service.kn.switchtimer/addon.xml, service.kn.switchtimer/changelog.txt, service.kn.switchtimer/handler.py, service.kn.switchtimer/resources/language/resource.language.de_DE/strings.po, service.kn.switchtimer/resources/language/resource.language.en_GB/strings.po, service.kn.switchtimer/resources/language/resource.language.nl_NL/strings.po, service.kn.switchtimer/resources/language/resource.language.pt_BR/strings.po, service.kn.switchtimer/resources/language/resource.language.pt_PT/strings.po
Update:
- wrong languages directory names fixed
- language strings updated …
=> [service.kn.switchtimer] v2.0.5

screensaver.unsplash/addon.xml, screensaver.unsplash/gui.py, screensaver.unsplash/resources/language/resource.language.en_gb/strings.po, screensaver.unsplash/resources/settings.xml
=> [screensaver.unsplash] 1.0.1

screensaver.digitalclock/addon.xml, screensaver.digitalclock/changelog.txt, screensaver.digitalclock/resources/skins/default/720p/skin.aeon.nox.silvo.xml
Added support for Aeon Nox 5: SiLVO skin …
=>  [screensaver.digitalclock] 5.0.3

script.twittertweets/addon.xml, script.twittertweets/gui.py, script.twittertweets/resources/skins/default/1080i/script.twittertweets.default.xml, script.twittertweets/service.py
=> [script.twittertweets] 1.0.2

script.module.python.twitch/addon.xml, script.module.python.twitch/changelog.txt, script.module.python.twitch/resources/lib/twitch/api/v5/bits.py, script.module.python.twitch/resources/lib/twitch/api/v5/channels.py, script.module.python.twitch/resources/lib/twitch/api/v5/chat.py, script.module.python.twitch/resources/lib/twitch/api/v5/clips.py, script.module.python.twitch/resources/lib/twitch/api/v5/collections.py, script.module.python.twitch/resources/lib/twitch/api/v5/communities.py, script.module.python.twitch/resources/lib/twitch/api/v5/games.py, script.module.python.twitch/resources/lib/twitch/api/v5/ingests.py, script.module.python.twitch/resources/lib/twitch/api/v5/search.py, script.module.python.twitch/resources/lib/twitch/api/v5/streams.py, script.module.python.twitch/resources/lib/twitch/api/v5/teams.py, script.module.python.twitch/resources/lib/twitch/api/v5/users.py, script.module.python.twitch/resources/lib/twitch/api/v5/videos.py, script.module.python.twitch/resources/lib/twitch/queries.py
[script.module.python.twitch] 1.0.2
Dependency of [plugin.video.twitch] 2.0.2
Changes:
Fixes in line with changes to Twitch API
Thanks …
=> [script.module.python.twitch] 1.0.2

service.kn.switchtimer/addon.xml, service.kn.switchtimer/changelog.txt, service.kn.switchtimer/resources/language/resource.language.de_DE/strings.po, service.kn.switchtimer/resources/language/resource.language.en_GB/strings.po, service.kn.switchtimer/resources/language/resource.language.nl_NL/strings.po, service.kn.switchtimer/resources/language/resource.language.pt_BR/strings.po, service.kn.switchtimer/resources/language/resource.language.pt_PT/strings.po, service.kn.switchtimer/service.py
Update: Encode/Decode Issues fixed. …
=> [service.kn.switchtimer] v2.0.7

script.simkl/README.md, script.simkl/addon.xml, script.simkl/resources/language/resource.language.en_gb/strings.po, script.simkl/resources/language/resource.language.es_es/strings.po, script.simkl/resources/language/resource.language.pt_pt/strings.po, script.simkl/resources/lib/api_simkl.py, script.simkl/resources/lib/engine.py, script.simkl/resources/settings.xml
Bug fixes
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting …
=> [script.simkl] v2.1.0

screensaver.google.earth/addon.xml
version bump, repaired addon.xml. Last commit wasn't merged correctly. …
=> [screensaver.google.earth] 1.0.1

script.myepisodecalendar/addon.xml, script.myepisodecalendar/changelog.txt, script.myepisodecalendar/main.py, script.myepisodecalendar/resources/language/Hebrew/strings.po, script.myepisodecalendar/resources/lib/myepisodecalendar.py
New in 1.4.0:
+ Hebrew translation thanks to Eng2Heb
+ major improvements in matching series titles
+ better performance searching for series titles
- [/] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [/] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [/] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0
- [add-on …
=> [script.myepisodecalendar] 1.4.0

script.kodi.android.update/addon.xml, script.kodi.android.update/default.py, script.kodi.android.update/resources/language/resource.language.en_gb/strings.po, script.kodi.android.update/resources/settings.xml, script.kodi.android.update/service.py
Added delete download after install service. …
=> [script.kodi.android.update] 1.0.1

script.kodi.android.update/addon.xml, script.kodi.android.update/default.py, script.kodi.android.update/service.py
=> [script.kodi.android.update] 1.0.2

screensaver.digitalclock/addon.xml, screensaver.digitalclock/changelog.txt, screensaver.digitalclock/resources/skins/default/720p/skin.ftv.xml, screensaver.digitalclock/resources/skins/default/720p/skin.grid.xml, screensaver.digitalclock/resources/skins/default/720p/skin.horizon.xml, screensaver.digitalclock/resources/skins/default/720p/skin.reestuarized.xml
Added support for skins Ftv, Grid, Horizon and Reestuarized …
=> [screensaver.digitalclock] 5.0.4

service.subtitles.podnapisi/addon.xml, service.subtitles.podnapisi/changelog.txt, service.subtitles.podnapisi/resources/lib/pn_utilities.py, service.subtitles.podnapisi/resources/settings.xml, service.subtitles.podnapisi/service.py
- fix: Unicode issue with languages
- fix: Year was inside the title, it must be removed
- fix: Used year of the episode, switched to Premiered info
- fix: Podnapisi.NET does not have Serbo-Croatian language, it resulted into None and crashed the addon
- Removed/disabled old XML-RPC based API
- Removed login credentials (will probably be readded later)
- Added search with IMDb number, where possible
- all changes in 5.4.2 by MasterMind2k
https://github.com/amet/service.subtitles.podnapisi/pull/4
- Kodi …
=> [service.subtitles.podnapisi] v5.4.2

.tests-config.json
Much more features now and we're disabling three tests for gotham that we don't want to run.
=> Gotham tests config

script.module.uepg/addon.xml
Addon.xml removed art.
[script.module.uepg] 1.0.1 …
=> [script.module.uepg] 1.0.1

script.twittertweets/addon.xml, script.twittertweets/resources/settings.xml
Settings.xml XML format correction. …
=> [script.twittertweets] 1.0.5

script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/changelog.txt, script.module.inputstreamhelper/lib/config.py, script.module.inputstreamhelper/lib/inputstreamhelper.py
Update [script.module.inputstreamhelper](https://github.com/emilsvennesson/script.module.inputstreamhelper) on behalf of @emilsvennesson as he´s not able to do it technically atm.
The change includes the changes of the following 2 PRs (actual fix & version bump):
- https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/6
- https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/7
And fixes the following issue that prevents the plugin from downloading the correct file for Windows x64 systems: https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/5
=> [script.module.inputstreamhelper] 0.2.2.

script.module.libmediathek3/addon.xml, script.module.libmediathek3/changelog.txt, script.module.libmediathek3/lib/libmediathek3.py, script.module.libmediathek3/lib/libmediathek3listing.py, script.module.libmediathek3/lib/libmediathek3ttml2srt.py, script.module.libmediathek3/lib/libmediathek3utils.py, script.module.libmediathek3/resources/language/Dutch/strings.po, script.module.libmediathek3/resources/language/German/strings.po
=> [script.module.libmediathek3] 1.5.0

script.module.pyrollbar/addon.xml, script.module.pyrollbar/lib/rollbar/__init__.py, script.module.pyrollbar/lib/rollbar/kodi/__init__.py, script.module.pyrollbar/lib/rollbar/lib/__init__.py, script.module.pyrollbar/lib/rollbar/lib/transforms/__init__.py, script.module.pyrollbar/lib/rollbar/lib/transforms/scrub.py, script.module.pyrollbar/lib/rollbar/lib/transforms/scrub_redact.py, script.module.pyrollbar/lib/rollbar/lib/transforms/scruburl.py, script.module.pyrollbar/lib/rollbar/lib/transforms/serializable.py, script.module.pyrollbar/lib/rollbar/lib/transforms/shortener.py, script.module.pyrollbar/lib/rollbar/lib/transport.py, script.module.pyrollbar/lib/rollbar/lib/traverse.py, script.module.pyrollbar/resources/language/resource.language.en_gb/strings.po
- Updates the code to the [0.13.17 release](https://github.com/rollbar/pyrollbar/releases/tag/v0.13.17).
- Adds a Kodi specific module to simplify the reporting of errors, e.g.
```python
import rollbar.kodi
try:
...
except Exception as exc:
if rollbar.kodi.error_report_requested(exc):
rollbar.kodi.report_error(
access_token='********************************',
version=xbmcaddon.Addon().getAddonInfo('version'),
url=url
)
```
- …
=> [script.module.pyrollbar] 0.13.17

weather.ozweather/addon.xml
Update for recent urllib3 changes - for some reason this addon no longer worked in profiles other than the master profile...by explicitly importing urllib3, it now works.
=> [weather.ozweather] 0.9.0

service.smartthings/addon.xml, service.smartthings/service.py
=> [service.smartthings] 1.0.1

service.smartthings/addon.xml, service.smartthings/default.py, service.smartthings/service.py
=> [service.smartthings] 1.0.2

weather.ozweather/addon.xml
Ok, so my 'fix' wasn't a fix.  Apparently, in sub  profiles libs can be disabled at random.  So this import was not necessary. …
=> [weather.ozweather] 0.9.2

screensaver.system47/README.md, screensaver.system47/addon.xml, screensaver.system47/default.py, screensaver.system47/resources/settings.xml
Updated API Keys, removed savestate. …
=> [screensaver.system47] 2.2.g

script.module.googleapi/LICENSE.txt, script.module.googleapi/README.md, script.module.googleapi/addon.xml, script.module.googleapi/changelog.txt, script.module.googleapi/lib/googleapiclient/__init__.py, script.module.googleapi/lib/googleapiclient/_auth.py, script.module.googleapi/lib/googleapiclient/channel.py, script.module.googleapi/lib/googleapiclient/discovery.py, script.module.googleapi/lib/googleapiclient/discovery_cache/__init__.py, script.module.googleapi/lib/googleapiclient/discovery_cache/appengine_memcache.py, script.module.googleapi/lib/googleapiclient/discovery_cache/base.py, script.module.googleapi/lib/googleapiclient/discovery_cache/file_cache.py, script.module.googleapi/lib/googleapiclient/errors.py, script.module.googleapi/lib/googleapiclient/http.py, script.module.googleapi/lib/googleapiclient/mimeparse.py, script.module.googleapi/lib/googleapiclient/model.py, script.module.googleapi/lib/googleapiclient/sample_tools.py, script.module.googleapi/lib/googleapiclient/schema.py
Updated version of this from the google repo. It does depend on the oauth2client updated version in PR #683.  …
=> script.module.googleapi 1.6.4

service.smartthings/addon.xml, service.smartthings/default.py, service.smartthings/resources/language/resource.language.en_gb/strings.po, service.smartthings/resources/settings.xml, service.smartthings/service.py
Improved service, started move to proper api. …
=> [service.smartthings] 1.0.3

service.partymode.autostart/PartymodeAutostart.py, service.partymode.autostart/README.md, service.partymode.autostart/addon.xml, service.partymode.autostart/changelog.txt, service.partymode.autostart/resources/language/English/strings.po, service.partymode.autostart/resources/settings.xml
Updates:
* Playback controls (repeat and random)
* A toggle to enable party mode when auto-starting a playlist
* Explicit countdown window that actually tells you what it's going to do
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these …
=> [service.partymode.autostart] 0.9.0b

script.kodi.android.update/LICENSE, script.kodi.android.update/addon.xml, script.kodi.android.update/default.py, script.kodi.android.update/resources/settings.xml, script.kodi.android.update/service.py
=> [script.kodi.android.update] 1.0.3

script.kodi.windows.update/LICENSE, script.kodi.windows.update/addon.xml, script.kodi.windows.update/default.py, script.kodi.windows.update/resources/language/resource.language.en_gb/strings.po
UWP check, func tweaks, cancel download. …
=> [script.kodi.windows.update] 1.0.1

script.module.dropbox/addon.xml, script.module.dropbox/authenticate.py
Fixes up some issues on different platforms.
=> [script.module.dropbox] 8.4.1

.travis.yml
Builds all addons on branch build and only the changed addons on PR build.
Some code done by @Rechi some by me
=> Update repo-checker and travis config

weather.ozweather/addon.xml, weather.ozweather/changelog.txt, weather.ozweather/resources/lib/bom.py
Fix for upstream scrape change
(apologies for the merge commit in here, I've got no idea what's going on - each time I follow these instructions: 
```
Updating the addon is now easy. For this example we pull the master branch from myaddon:
git checkout gotham
git pull --strategy subtree --squash myaddon master
git commit -m "[plugin.my.addon] 1.0.2"
git push origin gotham
```
...I get a different result of git hell.
- [x ] Each add-on submission should be a single commit with using the following style: …
=> [weather.ozweather] 0.9.3

service.fussballpopup/addon.xml, service.popwindow/addon.xml, service.rsspopup/addon.xml, service.twitterfeed/addon.xml
Marked Addons as Broken, because i dont want the be online at kodi.tv anymore
=> Removed addon

service.subtitles.subcentral/addon.xml
Marked Addons as Broken, because i dont want the be online at kodi.tv anymore
=> service.subtitles.subcentral not suportet an kodi.tv anymore

script.screensaver.animexx/addon.xml, service.subtitles.tv4user/addon.xml
Marked Addons as Broken, because i dont want the be online at kodi.tv anymore
=> Addon Removed, because i dont want them on at kodi.tv anymore

weather.ozweather/addon.xml, weather.ozweather/changelog.txt, weather.ozweather/resources/lib/weatherzone.py
Changes for upstream scraping issues.  Most is just re-ordered code, no major changes from the (many) previous versions.  The use of print in the lib modules has previously been okay-ed as it allows for unit testing.
I closed the previous PR and re-cloned xbmc-scripts etc...seemed the only way to get out of git hell.
I hope and pray this one is ok!!!
=> [weather.ozweather] 0.9.5

weather.ozweather/addon.xml, weather.ozweather/resources/lib/weatherzone.py
Formatting clean-ups after recent scraper fixes
=> [weather.ozweather] v0.9.6

script.module.six/addon.xml, script.module.six/lib/six.py
Update `script.module.six` to v.1.11.0 …
=> [script.module.six] 1.11.0

service.watchedlist/addon.xml, service.watchedlist/lib/watchedlist/watchedlist.py
Please only merge this, if https://github.com/xbmc/repo-scripts/pull/719 is affirmed.
=> [service.watchedlist] 1.2.2

script.service.next-episode/addon.xml, script.service.next-episode/changelog.txt, script.service.next-episode/libs/commands.py, script.service.next-episode/libs/gui.py, script.service.next-episode/libs/medialibrary.py, script.service.next-episode/libs/monitoring.py, script.service.next-episode/libs/nextepisode.py, script.service.next-episode/resources/settings.xml
=> [script.service.next-episode] 1.1.3

script.module.buggalo/addon.xml, script.module.buggalo/changelog.txt, script.module.buggalo/lib/buggalo_client.py, script.module.buggalo/lib/buggalo_gui.py
Please merge the latest fixes from https://github.com/SchapplM/script.module.buggalo
=> [script.module.buggalo] 1.1.8

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/changelog.txt, script.module.inputstreamhelper/lib/config.py, script.module.inputstreamhelper/lib/inputstreamhelper.py, script.module.inputstreamhelper/resources/language/resource.language.de_de/strings.po, script.module.inputstreamhelper/resources/language/resource.language.en_gb/strings.po
This solves a lot of headache with users wondering why their video add-on suddenly stopped working after switching to 64-bit Kodi. …
=> [script.module.inputstreamhelper] 0.2.3

script.xbmcbackup/addon.xml, script.xbmcbackup/changelog.txt, script.xbmcbackup/resources/lib/dropbox/oauth.py, script.xbmcbackup/resources/lib/dropbox/stone_serializers.py, script.xbmcbackup/resources/lib/dropbox/stone_validators.py, script.xbmcbackup/resources/lib/vfs.py
[An issue](https://github.com/robweber/xbmcbackup/issues/126) was discovered that affected the Jarvis version of Kodi using the Backup addon for Android or Rpi installations. This was due to the fact those installs use Python 2.6 and the Dropbox library was not compatible. 
I've modified the library to work with these installations. You can see in the changed files these were all set/dict comprehensions. There is a working [Krypton branch](https://github.com/robweber/xbmcbackup/tree/krypton) __without__ these changes that will become the norm for all versions going forward since Python 2.6 is Jarvis and below only. 
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi …
=> [script.xbmcbackup] 1.1.2

service.watchedlist/addon.xml, service.watchedlist/changelog.txt, service.watchedlist/default.py, service.watchedlist/lib/watchedlist/api.py, service.watchedlist/lib/watchedlist/utils.py, service.watchedlist/lib/watchedlist/watchedlist.py, service.watchedlist/manual.py, service.watchedlist/resources/language/resource.language.de_de/strings.po, service.watchedlist/resources/language/resource.language.en_gb/strings.po, service.watchedlist/resources/language/resource.language.he_il/strings.po
Please merge the latest fixes from https://github.com/SchapplM/xbmc-addon-service-watchedlist
=> [service.watchedlist] 1.2.3

script.service.next-episode/addon.xml, script.service.next-episode/libs/medialibrary.py
=> [script.service.next-episode] 1.1.4

script.module.web-pdb/addon.xml, script.module.web-pdb/libs/web_pdb/__init__.py
Implemented updates from the upstream Web-PDB package v.1.3.3 …
=> "[script.module.web-pdb] 1.3.3"

script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/changelog.txt, script.module.inputstreamhelper/lib/inputstreamhelper.py, script.module.inputstreamhelper/resources/language/resource.language.de_de/strings.po, script.module.inputstreamhelper/resources/language/resource.language.en_gb/strings.po
I'm sorry for screwing up the last update by forgetting to bump version in addon.xml. …
=> [script.module.inputstreamhelper] 0.2.4

script.module.web-pdb/addon.xml, script.module.web-pdb/libs/web_pdb/__init__.py
This update finally fixes the bug with not being able to clear a breakpoint when debugging in Kodi. …
=> "[script.module.web-pdb] 1.3.4"

script.common.plugin.cache/addon.xml, script.common.plugin.cache/changelog.txt, script.common.plugin.cache/default.py, script.common.plugin.cache/lib/StorageServer.py
- fixes error for windows uwp (https://forum.kodi.tv/showthread.php?tid=326796)
- some python3 adjustments
=> [script.common.plugin.cache] 2.5.9

service.partymode.autostart/addon.xml, service.partymode.autostart/changelog.txt, service.partymode.autostart/resources/settings.xml
* Set new values default (fix issue #6) …
=> [service.partymode.autostart] 0.9.1b

script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/changelog.txt, script.module.inputstreamhelper/lib/config.py, script.module.inputstreamhelper/lib/inputstreamhelper.py
I'm terribly sorry for the update frequency. Getting this right with all the edge cases has proven to be a major PITA. This should (hopefully) be the last update for a while... …
=> [script.module.inputstreamhelper] 0.3.2

screensaver.system47/addon.xml, screensaver.system47/default.py, screensaver.system47/resources/language/resource.language.en_gb/strings.po, screensaver.system47/resources/settings.xml
=> [screensaver.system47] 2.2.h

service.subtitles.titlovi-com-official/addon.xml, service.subtitles.titlovi-com-official/resources/resource.language.hr_HR/strings.po
Added Croatian translation, updated addon description …
=> [service.subtitles.titlovi-com-official] 1.1.0

service.watchedlist/addon.xml, service.watchedlist/changelog.txt, service.watchedlist/lib/watchedlist/utils.py, service.watchedlist/lib/watchedlist/watchedlist.py
please merge this fix regarding smb support on windows
=> [service.watchedlist] 1.2.5

script.video.bgtime_tv/addon.xml, script.video.bgtime_tv/gui.py
- [ x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0
- …
=> [script.video.bgtime_tv] 1.0.6

script.speedfaninfo/CHANGELOG.txt, script.speedfaninfo/addon.xml, script.speedfaninfo/resources/common/fileops.py, script.speedfaninfo/resources/common/transforms.py, script.speedfaninfo/resources/common/url.py, script.speedfaninfo/resources/common/xlogger.py
v.0.7.6
- updated common libraries (including fix for subprocess not available in Windows Store version of Kodi)
- updated error handling to be consistent with Python3
- [ x ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ x ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [ x ] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0
- [add-on …
=> [script.speedfaninfo] 0.7.6

script.module.pyqrcode/addon.xml, script.module.pyqrcode/lib/pyqrcode/png.py
=> [script.module.pyqrcode] 0.0.2

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/changelog.txt, script.module.inputstreamhelper/lib/config.py, script.module.inputstreamhelper/lib/inputstreamhelper.py, script.module.inputstreamhelper/resources/language/resource.language.de_de/strings.po, script.module.inputstreamhelper/resources/language/resource.language.en_gb/strings.po
+ Load loop if it's a kernel module (thanks to mkreisl)
+ Fix legacy Widevine CDM update detection
+ inputstream_addon is now a public variable
+ Notify user that ARM64 needs 32-bit userspace
+ Improve logging
+ Cosmetics
- This add-on repository has automated code guideline check which could help you improve your coding. …
=> [script.module.inputstreamhelper] 0.3.3

script.module.libzdf/addon.xml, script.module.libzdf/changelog.txt, script.module.libzdf/lib/libzdf.py, script.module.libzdf/lib/libzdfjsonparser.py, script.module.libzdf/lib/libzdftokengrabber.py
=> [script.module.libzdf] v2.1.7

script.module.nexx/LICENSE.txt, script.module.nexx/addon.xml, script.module.nexx/changelog.txt, script.module.nexx/lib/nexx.py
This is a module for the video CMS Nexx.  …
=> [script.module.nexx] v1.2.0

script.kodi.android.update/addon.xml, script.kodi.android.update/default.py, script.kodi.android.update/resources/language/resource.language.en_gb/strings.po, script.kodi.android.update/service.py
=> [script.kodi.android.update] 1.0.6

script.kodi.android.update/addon.xml, script.kodi.android.update/default.py
=> [script.kodi.android.update] 1.0.7

script.module.pyhdhr/addon.xml, script.module.pyhdhr/lib/pyhdhr/PyHDHR.py
=> [script.module.pyhdhr] 1.0.3

script.kodi.windows.update/addon.xml, script.kodi.windows.update/default.py, script.kodi.windows.update/resources/language/resource.language.en_gb/strings.po, script.kodi.windows.update/resources/settings.xml, script.kodi.windows.update/service.py
update
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to …
=> [script.kodi.windows.update] 1.0.2

screensaver.kaster/addon.xml, screensaver.kaster/changelog.txt, screensaver.kaster/resources/lib/screensaver.py, screensaver.kaster/resources/skins/default/1080i/screensaver-kaster.xml
v1.2.0 28/2/2018
- Improve skinning
- Set clock font for Actic Zephyr skin
=> [screensaver.kaster] 1.2.0

script.module.pyhdhr/addon.xml, script.module.pyhdhr/lib/pyhdhr/PyHDHR.py
=> [script.module.pyhdhr] 1.0.4

screensaver.kaster/addon.xml, screensaver.kaster/changelog.txt, screensaver.kaster/resources/language/resource.language.es_es/strings.po, screensaver.kaster/resources/lib/screensaver.py, screensaver.kaster/resources/skins/default/1080i/screensaver-kaster.xml
- update spanish translation (tks roliversc)
- Clock font for eminence skin
=> [screensaver.kaster] 1.2.1

script.tubecast/addon.xml, script.tubecast/changelog.txt
=> [script.tubecast] 1.0.1

screensaver.atv4/addon.xml
Mark this as broken (despite being functional) to inform users to update to krypton to continue to receive support
=> [screensaver.atv4] 1.4.3/broken

script.tubecast/addon.xml, script.tubecast/changelog.txt, script.tubecast/resources/lib/service.py, script.tubecast/resources/lib/tubecast/youtube/player.py
=> [script.tubecast] 1.0.2

script.tubecast/addon.xml, script.tubecast/changelog.txt, script.tubecast/resources/lib/tubecast/chromecast.py, script.tubecast/resources/lib/tubecast/youtube/app.py, script.tubecast/resources/lib/tubecast/youtube/player.py
A quick merge is appreciated since the current version is reporting the playback to youtube even if playing movies/music/tvshows
=> [script.tubecast] 1.0.3

script.module.pyhdhr/addon.xml, script.module.pyhdhr/lib/pyhdhr/PyHDHR.py
=> [script.module.pyhdhr] 1.0.5

script.module.uepg/addon.xml, script.module.uepg/resources/skins/default/1080i/script.module.uepg.guide.xml, script.module.uepg/utils.py
=> [script.module.uepg] 1.0.3

script.service.next-episode/addon.xml, script.service.next-episode/changelog.txt, script.service.next-episode/libs/commands.py, script.service.next-episode/libs/logger.py, script.service.next-episode/libs/medialibrary.py, script.service.next-episode/libs/monitoring.py, script.service.next-episode/libs/nextepisode.py, script.service.next-episode/service.py
Fixed getting incorrect item IDs from JSON-RPC in Krypton and above. …
=> [script.service.next-episode] 1.1.5

service.subtitles.subspedia/addon.xml, service.subtitles.subspedia/changelog.txt, service.subtitles.subspedia/service.py
=> [service.subtitles.subspedia] 1.0.3

service.subtitles.pipocas/addon.xml, service.subtitles.pipocas/changelog.txt, service.subtitles.pipocas/service.py
Update [service.subtitles.pipocas] 0.1.5
http to https - Mandatory.
=> [service.subtitles.pipocas] 0.1.5

script.tubecast/addon.xml, script.tubecast/changelog.txt
Small change to respect kodi profiles
=> [script.tubecast] 1.0.4

weather.gismeteo/addon.xml, weather.gismeteo/changelog.txt, weather.gismeteo/default.py, weather.gismeteo/resources/language/English/strings.po, weather.gismeteo/resources/language/Russian/strings.po, weather.gismeteo/resources/lib/gismeteo.py, weather.gismeteo/resources/lib/simpleplugin.py, weather.gismeteo/resources/lib/simpleweather.py, weather.gismeteo/resources/lib/utilities.py
=> [weather.gismeteo] 0.3.3

screensaver.turnoff/addon.xml, screensaver.turnoff/screensaver.py
When fixing the xbmcgui.Dialog().notification() call I introduced a
small issue wrt. message. So every pop-up (on error) is now causing an
error. (The original v0.9.0 did not have this issue)
So I decided to do a quick v0.9.1 release as this could be annoying for
users testing the different methods.
- This add-on …
=> [screensaver.turnoff] v0.9.1

script.tubecast/addon.xml, script.tubecast/resources/language/resource.language.en_gb/strings.po, script.tubecast/resources/language/resource.language.pt_pt/strings.po, script.tubecast/resources/lib/tubecast/youtube/app.py, script.tubecast/resources/settings.xml
Added option to neglect SSL verifications as requested by a user.
=> [script.tubecast] 1.0.5

script.speedfaninfo/CHANGELOG.txt, script.speedfaninfo/addon.xml, script.speedfaninfo/default.py, script.speedfaninfo/resources/common/fileops.py, script.speedfaninfo/resources/settings.xml
v.0.7.8
- fix for problem with common library moving files
- changes for better compatibility when running script on non-Windows machine
- fix for crash if launching external script
- [ x ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ x ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [ x ] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0
- [add-on …
=> [script.speedfaninfo] 0.7.8

script.artistslideshow/addon.xml, script.artistslideshow/changelog.txt, script.artistslideshow/default.py, script.artistslideshow/resources/common/fileops.py
v.2.1.2
- fix for common library issue with moving a file
- fix for crash when trying to trim cache folder
- [ x ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ x ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [ x ] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0
- Kodi …
=> [script.artistslideshow] v2.1.2

service.smartthings/addon.xml
=> [service.smartthings] Broken

script.module.uepg/addon.xml, script.module.uepg/default.py, script.module.uepg/utils.py
=> [script.module.uepg] 1.0.5

script.tubecast/addon.xml, script.tubecast/changelog.txt, script.tubecast/resources/lib/tubecast/youtube/app.py, script.tubecast/resources/lib/tubecast/youtube/utils.py
Track code numbers sent by youtube so they are not executed twice when restarting the synchronous connection to the server
=> [script.tubecast] 1.0.6

script.xbmc.lcdproc/addon.xml, script.xbmc.lcdproc/changelog.txt, script.xbmc.lcdproc/main.py, script.xbmc.lcdproc/resources/lib/common.py, script.xbmc.lcdproc/resources/lib/infolabels.py, script.xbmc.lcdproc/resources/lib/lcdbase.py, script.xbmc.lcdproc/resources/lib/lcdproc.py, script.xbmc.lcdproc/resources/lib/settings.py, script.xbmc.lcdproc/resources/lib/xbmclcdproc.py
- Refactored the main addon handling into class XBMCLCDproc()
- Refactored the settings and infolabels modules into classes
- fixed connection status popup handling logic
- Code/vars move and cleanup
- Window ID cleanup (fixes the extraicon triggers during navigation)
This iteration gets rid of all the globals that were used throughout all modules (besides the stuff that lives in common.py, there's good reasons to keep that file and it's defines/globals as it is, in that these things are used rather randomly all over the place).
There's more things planned to be done differently that will involve changes to the overall logic of the addon (ie. use xbmc.Monitor() and it's notifiers), though this is currently blocked by https://trac.kodi.tv/ticket/17936 …
=> [script.xbmc.lcdproc] 3.0.2

context.altmovie.posters/addon.xml, context.altmovie.posters/capture.py, context.altmovie.posters/settings.py
=> [context.altmovie.posters] 1.0.1

script.episodehunter/addon.xml, script.episodehunter/changelog.txt, script.episodehunter/resources/lib/connection/connection.py
This update contains a bugfix (regarding that episodes was treated as movies on backend api) …
=> [script.episodehunter] 2.0.5

script.module.requests/LICENSE.txt, script.module.requests/addon.xml, script.module.requests/changelog.txt, script.module.requests/lib/AUTHORS.rst, script.module.requests/lib/HISTORY.rst, script.module.requests/lib/LICENSE, script.module.requests/lib/README.rst, script.module.requests/lib/requests/__init__.py, script.module.requests/lib/requests/__version__.py, script.module.requests/lib/requests/adapters.py, script.module.requests/lib/requests/api.py, script.module.requests/lib/requests/auth.py, script.module.requests/lib/requests/compat.py, script.module.requests/lib/requests/cookies.py, script.module.requests/lib/requests/exceptions.py, script.module.requests/lib/requests/help.py, script.module.requests/lib/requests/models.py, script.module.requests/lib/requests/sessions.py, script.module.requests/lib/requests/status_codes.py, script.module.requests/lib/requests/structures.py, script.module.requests/lib/requests/utils.py
Update of Python requests library packed for KODI …
=> [script.module.requests] 2.19.1

script.module.clouddrive.common/addon.xml, script.module.clouddrive.common/clouddrive/common/remote/errorreport.py, script.module.clouddrive.common/clouddrive/common/service/player.py, script.module.clouddrive.common/clouddrive/common/service/source.py, script.module.clouddrive.common/clouddrive/common/ui/addon.py, script.module.clouddrive.common/clouddrive/common/ui/utils.py
- Subtitles assigned in source mode
- Fixes …
=> [script.module.clouddrive.common] 1.2.6

script.module.codequick/addon.xml, script.module.codequick/lib/codequick/__init__.py, script.module.codequick/lib/codequick/listing.py, script.module.codequick/lib/codequick/resolver.py, script.module.codequick/lib/codequick/route.py, script.module.codequick/lib/codequick/script.py, script.module.codequick/lib/codequick/search.py, script.module.codequick/lib/codequick/storage.py, script.module.codequick/lib/codequick/support.py, script.module.codequick/lib/codequick/utils.py, script.module.codequick/lib/codequick/youtube.py, script.module.codequick/lib/urlquick.py, script.module.codequick/resources/language/resource.language.en_gb/strings.po, script.module.codequick/resources/language/resource.language.he_il/strings.po
* Mostly documentation changes.
* Added Time to live option to persistent storage.
* Added support for fetching localized strings using "msgid" as the reference. i.e. gettext
* Added some extra functions to utils, and removed some others.
* Lots of other minor changes.
* Tested with Kodi v18 Leia.
Sorry in advanced for the large commit changes log.
=> [script.module.codequick] 0.9.5

script.xbmc.lcdproc/addon.xml, script.xbmc.lcdproc/changelog.txt, script.xbmc.lcdproc/resources/language/resource.language.pl_pl/strings.po, script.xbmc.lcdproc/resources/lib/infolabels.py, script.xbmc.lcdproc/resources/lib/lcdbase.py
- Polish translation update by mskalski (thanks!)
- Fixed	a possible UTF8	conversion crash/exception
- Updated video/audiocodec strings for extraicon display …
=> [script.xbmc.lcdproc] 3.0.3

script.module.python.twitch/addon.xml, script.module.python.twitch/changelog.txt, script.module.python.twitch/resources/lib/twitch/log.py
redact user ip from token logging …
=> [script.module.python.twitch] v2.0.3

script.module.clouddrive.common/addon.xml, script.module.clouddrive.common/clouddrive/common/export.py, script.module.clouddrive.common/clouddrive/common/service/player.py, script.module.clouddrive.common/clouddrive/common/ui/addon.py, script.module.clouddrive.common/clouddrive/common/ui/logger.py, script.module.clouddrive.common/clouddrive/common/ui/utils.py, script.module.clouddrive.common/resources/language/resource.language.en_gb/strings.po
- Resume points and watched status for strm files in library …
=> [script.module.clouddrive.common] 1.2.8

screensaver.videosaver/addon.xml, screensaver.videosaver/default.py, screensaver.videosaver/resources/language/resource.language.es_es/strings.po, screensaver.videosaver/resources/settings.xml
=> [screensaver.videosaver] 1.0.2

script.module.lwe_mapper/addon.xml, script.module.lwe_mapper/lib/mapper.py
Much needed version bump.
Will be required by an upcoming PR to [service.linuxwhatelse.notify](https://github.com/xbmc/repo-scripts/tree/jarvis/service.linuxwhatelse.notify) …
=> [script.module.lwe_mapper] v1.2.5

script.module.adobepass/addon.xml, script.module.adobepass/lib/adobepass/adobe.py
- Code Refactor for PEP 8 Styling
- Improve Error Message reporting …
=> [script.module.adobepass] 2018.10.8

service.subtitles.napisy24pl/addon.xml, service.subtitles.napisy24pl/changelog.txt, service.subtitles.napisy24pl/resources/lib/NapisyUtils.py
Update site url to contain https …
=> [service.subtitles.napisy24pl] v2.0.2

service.subtitles.napisy24pl/addon.xml
Remove empty fields in the addon's metadata field …
=> [service.subtitles.napisy24pl] v2.0.3

context.artwork.downloader.gui/addon.xml
Dang I like [this webapp](https://forum.kodi.tv/showthread.php?tid=331874)! Even modifying PRs just works. Thanks for your patience while I flopped around on these. …
=> [context.artwork.downloader.gui] 1.0.2

service.linuxwhatelse.notify/addon.xml, service.linuxwhatelse.notify/addon/__init__.py, service.linuxwhatelse.notify/addon/routes/__init__.py, service.linuxwhatelse.notify/addon/routes/call.py, service.linuxwhatelse.notify/addon/routes/notification.py, service.linuxwhatelse.notify/addon/utils.py, service.linuxwhatelse.notify/resources/settings.xml, service.linuxwhatelse.notify/script.py, service.linuxwhatelse.notify/service.py
=> [service.linuxwhatelse.notify] 2.1.2

script.module.python.twitch/addon.xml, script.module.python.twitch/changelog.txt, script.module.python.twitch/resources/lib/twitch/api/usher.py
=> [script.module.python.twitch] v2.0.4

script.module.codequick/addon.xml, script.module.codequick/lib/codequick/__init__.py, script.module.codequick/lib/codequick/listing.py, script.module.codequick/lib/codequick/resolver.py, script.module.codequick/lib/codequick/route.py, script.module.codequick/lib/codequick/search.py, script.module.codequick/lib/codequick/storage.py, script.module.codequick/lib/codequick/support.py, script.module.codequick/lib/codequick/youtube.py, script.module.codequick/lib/urlquick.py, script.module.codequick/resources/language/resource.language.fr_fr/strings.po, script.module.codequick/resources/language/resource.language.he_il/strings.po
Mostly bug fixes with some small tweaks
Updated urlquick to v0.9.4
Added french translations
=> [script.module.codequick] 0.9.6

screensaver.kaster/addon.xml, screensaver.kaster/changelog.txt, screensaver.kaster/resources/language/resource.language.es_es/strings.po, screensaver.kaster/resources/lib/screensaver.py
v1.2.2
[fix] fix spanish translation (tks roliversc)
[fix] del instances left in memory
=> [screensaver.kaster] 1.2.2

screensaver.kaster/addon.xml, screensaver.kaster/changelog.txt, screensaver.kaster/resources/language/resource.language.nl_nl/strings.po
v1.2.3
- [new] add dutch translation (tks klojum)
=> [screensaver.kaster] 1.2.3

script.service.next-episode/addon.xml, script.service.next-episode/changelog.txt, script.service.next-episode/commands.py, script.service.next-episode/libs/addon.py, script.service.next-episode/libs/gui.py, script.service.next-episode/libs/logger.py, script.service.next-episode/libs/medialibrary.py, script.service.next-episode/libs/monitoring.py, script.service.next-episode/libs/nextepisode.py, script.service.next-episode/libs/utils.py, script.service.next-episode/main.py, script.service.next-episode/resources/settings.xml, script.service.next-episode/service.py
Updated code for compatibility with Python 3. …
=> [script.service.next-episode] 1.2.0

service.subtitles.napiprojekt/addon.xml, service.subtitles.napiprojekt/changelog.txt, service.subtitles.napiprojekt/resources/lib/NapiProjekt.py, service.subtitles.napiprojekt/service.py
=> [service.subtitles.napiprojekt] v1.1.3

script.module.trakt/addon.xml, script.module.trakt/changelog.txt, script.module.trakt/lib/trakt/client.py, script.module.trakt/lib/trakt/core/context_collection.py, script.module.trakt/lib/trakt/core/emitter.py, script.module.trakt/lib/trakt/core/errors.py, script.module.trakt/lib/trakt/core/http.py, script.module.trakt/lib/trakt/core/pagination.py, script.module.trakt/lib/trakt/interfaces/base/__init__.py, script.module.trakt/lib/trakt/interfaces/oauth/device.py, script.module.trakt/lib/trakt/interfaces/shows/__init__.py, script.module.trakt/lib/trakt/interfaces/sync/__init__.py, script.module.trakt/lib/trakt/interfaces/sync/collection.py, script.module.trakt/lib/trakt/interfaces/sync/core/mixins.py, script.module.trakt/lib/trakt/interfaces/sync/history.py, script.module.trakt/lib/trakt/interfaces/sync/playback.py, script.module.trakt/lib/trakt/interfaces/sync/ratings.py, script.module.trakt/lib/trakt/interfaces/sync/watched.py, script.module.trakt/lib/trakt/interfaces/sync/watchlist.py, script.module.trakt/lib/trakt/interfaces/users/__init__.py, script.module.trakt/lib/trakt/mapper/__init__.py, script.module.trakt/lib/trakt/mapper/core/base.py, script.module.trakt/lib/trakt/mapper/progress.py, script.module.trakt/lib/trakt/mapper/search.py, script.module.trakt/lib/trakt/mapper/sync.py, script.module.trakt/lib/trakt/objects/__init__.py, script.module.trakt/lib/trakt/objects/list/custom.py, script.module.trakt/lib/trakt/objects/progress.py, script.module.trakt/lib/trakt/version.py
=> [script.module.trakt] 3.0.0

script.kodi.android.update/addon.xml, script.kodi.android.update/default.py
=> [script.kodi.android.update] 1.1.1

service.linuxwhatelse.notify/addon.xml, service.linuxwhatelse.notify/addon/routes/notification.py, service.linuxwhatelse.notify/resources/language/resource.language.en_gb/strings.po, service.linuxwhatelse.notify/resources/settings.xml
Updates app beta access link in addon.xml so I can finally get rid of google+ and adds the ability to control the notifications display time. …
=> [service.linuxwhatelse.notify] 2.2.1

script.module.codequick/addon.xml, script.module.codequick/lib/codequick/__init__.py, script.module.codequick/lib/codequick/listing.py, script.module.codequick/lib/codequick/route.py, script.module.codequick/lib/codequick/support.py, script.module.codequick/lib/codequick/youtube.py
Some bug fixes and feature requests.
=> [script.module.codequick] 0.9.7

script.tag-generator/README.md, script.tag-generator/addon.xml, script.tag-generator/main.py
Bugfix for sleep timer. Math is hard.  …
=> [script.tag.generator] 0.6.4

service.subtitles.subspedia/addon.xml, service.subtitles.subspedia/changelog.txt
- Addon setted as broken, Subspedia community has closed!
=> [service.subtitles.subspedia] 1.1.0

service.subtitles.subspedia/addon.xml
requested at https://github.com/xbmc/repo-scripts/pull/971#issuecomment-449632435 …
=> service.subtitles.subspedia] 0.0.8 (broken)

script.service.checkpreviousepisode/addon.xml, script.service.checkpreviousepisode/changelog.txt, script.service.checkpreviousepisode/default.py, script.service.checkpreviousepisode/resources/language/English/strings.po
Fix for bug I introduced with previous version just released 0.3.2 (bug with Kodi versions < Leia).
Apologies @Rechi for another update so quickly but I apparently misinterpreted something the original dev did.  I'm doing this on less than ideal setups so it's a tad awkward,  but have this morning tested with both Krypton and Leia and all is working as expected.
Also, made that change to forum url as previously requested.
Slightly improved language & logging.
=> [script.service.checkpreviousepisode] 0.3.3

weather.ozweather/addon.xml, weather.ozweather/changelog.txt, weather.ozweather/resources/lib/bom.py
Fixes for the national radar, which behaves differently to all the rest
Simplify logic & fix exception reporting
=> [weather.ozweather] 0.9.9

weather.ozweather/addon.xml, weather.ozweather/changelog.txt, weather.ozweather/resources/lib/weatherzone.py
Improve error handling if bits of the scraped web pages are missing.
(Github makes this look like a bit change but it's literally just one extra exception handler and thanks to Python's tabs..everything goes one step to the right...)
=> [weather.ozweather] 1.0.0

service.watchedlist/addon.xml, service.watchedlist/changelog.txt, service.watchedlist/lib/watchedlist/watchedlist.py
please merge this fix regarding a minor seconds/milliseconds arguments mistake
=> [service.watchedlist] 1.2.6

script.hdhomerun.view/addon.xml, script.hdhomerun.view/changelog.txt, script.hdhomerun.view/lib/dvr.py, script.hdhomerun.view/lib/hdhr/netif/getifaddrs.py, script.hdhomerun.view/lib/hdhr/netif/ipconfig.py, script.hdhomerun.view/lib/record.py, script.hdhomerun.view/lib/skin.py, script.hdhomerun.view/resources/skins/Main/1080i/script-hdhomerun-view-dvr.xml, script.hdhomerun.view/resources/skins/Main/1080i/script-hdhomerun-view-dvr_episodes_dialog.xml, script.hdhomerun.view/resources/skins/Main/1080i/script-hdhomerun-view-dvr_record_dialog.xml, script.hdhomerun.view/resources/skins/Main/1080i/script-hdhomerun-view-options.xml, script.hdhomerun.view/resources/skins/Main/1080i/script-hdhomerun-view-overlay.xml
Update for Kodi 18 skin changes …
=> [script.hdhomerun.view] v2018.12.27

script.service.checkpreviousepisode/addon.xml, script.service.checkpreviousepisode/changelog.txt, script.service.checkpreviousepisode/default.py, script.service.checkpreviousepisode/resources/language/English/strings.po, script.service.checkpreviousepisode/resources/settings.xml
v0.3.4
* Add new option to ignore particular shows
* Move 'browse show episodes' to a setting rather than on every playback interaction, which felt janky to me
* Improve language across the board
* N.B. - new dependency - script.module.yaml
**NOTES / QUESTIONS**
There is a new dependency - script.module.yaml - I am not sure when this dependency was added to the Kodi repo so it's possible that I'll need to move the target forward from Gotham for this.  Also - I presume when Kodi installs the update, it will automatically install the new dependencies?
Also - I have used all new strings in this, as the previous language was not very 'native' and a bit all over the place (and several string were not used).  Once this is out I will ask in the forum thread for translators to submit updated …
=> [script.service.checkpreviousepisode] 0.3.4

screensaver.videosaver/addon.xml, screensaver.videosaver/default.py, screensaver.videosaver/resources/language/resource.language.en_gb/strings.po, screensaver.videosaver/resources/settings.xml
=> [screensaver.videosaver] 1.0.3

script.module.python.twitch/addon.xml, script.module.python.twitch/changelog.txt, script.module.python.twitch/resources/lib/twitch/api/helix/__init__.py, script.module.python.twitch/resources/lib/twitch/api/helix/entitlements.py, script.module.python.twitch/resources/lib/twitch/api/helix/streams.py, script.module.python.twitch/resources/lib/twitch/api/helix/subscriptions.py, script.module.python.twitch/resources/lib/twitch/api/helix/tags.py, script.module.python.twitch/resources/lib/twitch/api/parameters.py, script.module.python.twitch/resources/lib/twitch/keys.py
=> [script.module.python.twitch] v2.0.6

script.xbmc.lcdproc/addon.xml, script.xbmc.lcdproc/changelog.txt, script.xbmc.lcdproc/resources/lib/infolabels.py, script.xbmc.lcdproc/resources/lib/lcdbase.py
- Fix possible exception due to improper LCD.xml handling …
=> [script.xbmc.lcdproc] 3.0.4

script.module.codequick/addon.xml, script.module.codequick/lib/codequick/resolver.py
Fix for Dailymotion videos not working when using extract_source.
=> [script.module.codequick] 0.9.8

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/plugin_content.py
Hotfix for two functions that thrown exceptions if movie item has no cast or genre stored. …
=> [script.embuary.helper] 1.0.5

script.xbmc.lcdproc/addon.xml, script.xbmc.lcdproc/changelog.txt, script.xbmc.lcdproc/resources/language/resource.language.de_de/strings.po, script.xbmc.lcdproc/resources/language/resource.language.en_gb/strings.po, script.xbmc.lcdproc/resources/language/resource.language.fr_fr/strings.po, script.xbmc.lcdproc/resources/language/resource.language.pl_pl/strings.po, script.xbmc.lcdproc/resources/lib/infolabels.py, script.xbmc.lcdproc/resources/lib/lcdproc.py, script.xbmc.lcdproc/resources/lib/settings.py, script.xbmc.lcdproc/resources/settings.xml
- selectable BigDigit clock format by mskalski (thanks!) …
=> [script.xbmc.lcdproc] 3.0.5

script.module.python.twitch/addon.xml, script.module.python.twitch/changelog.txt, script.module.python.twitch/resources/lib/twitch/api/usher.py
=> [script.module.python.twitch] v2.0.7

script.embuary.helper/addon.xml, script.embuary.helper/resources/language/resource.language.en_gb/strings.po, script.embuary.helper/resources/lib/helper.py, script.embuary.helper/resources/lib/kodi_monitor.py, script.embuary.helper/resources/lib/plugin_content.py, script.embuary.helper/resources/settings.xml, script.embuary.helper/service.py
Service adjustments and improvements plus dropped support for Krypton. …
=> [script.embuary.helper] 1.0.6

script.embuary.helper/addon.xml, script.embuary.helper/default.py, script.embuary.helper/resources/lib/helper.py, script.embuary.helper/resources/lib/kodi_monitor.py, script.embuary.helper/resources/lib/library.py, script.embuary.helper/resources/lib/plugin_content.py, script.embuary.helper/resources/lib/utils.py
Fixed false logic of "Because you watched" widget
Added txtfile function
Cleanup  …
=> [script.embuary.helper] 1.0.9

script.service.checkpreviousepisode/addon.xml, script.service.checkpreviousepisode/changelog.txt, script.service.checkpreviousepisode/default.py
* Fixed error with non ascii chars in show title
* Better addon profile path handling, create profile directory if doesn't exists
* thanks @beam
=> [script.service.checkpreviousepisode] 0.3.5

script.embuary.helper/addon.xml, script.embuary.helper/default.py, script.embuary.helper/resources/lib/helper.py, script.embuary.helper/resources/lib/image.py, script.embuary.helper/resources/lib/kodi_monitor.py, script.embuary.helper/resources/lib/utils.py, script.embuary.helper/service.py
Added blurring feature
Tweaked widget reloadings
Minor adjustments …
=> [script.embuary.helper] 1.1.2

weather.ozweather/addon.xml, weather.ozweather/changelog.txt, weather.ozweather/resources/lib/b808common/b808common.py, weather.ozweather/resources/lib/weatherzone.py
Scrape WeatherZone via https as they now auto re-direct traffic 
(I am aware I have a lot of work to do vis a vis Python 3 for my various addons....I'll get to it!)
=> [weather.ozweather] 1.0.1

script.module.codequick/addon.xml, script.module.codequick/lib/codequick/route.py, script.module.codequick/lib/codequick/script.py, script.module.codequick/lib/codequick/support.py
More feature requests.
* Added support to auto redirect to the first listitem if there is only one single listitem (optional).
* Improved error handling, gives developers more control over exceptions.
=> [script.module.codequick] 0.9.10

script.embuary.helper/addon.xml, script.embuary.helper/plugin.py, script.embuary.helper/resources/lib/helper.py, script.embuary.helper/resources/lib/kodi_monitor.py, script.embuary.helper/resources/lib/plugin_content.py, script.embuary.helper/resources/lib/utils.py
- Fixed issue with umlauts
- Extended seasonal widget
- Adjusted shuffle play func
- Get video streamdetails …
=> [script.embuary.helper] 1.1.6

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/plugin_content.py
=> [script.embuary.helper] 1.1.7

script.game.netwalk/addon.xml, script.game.netwalk/changelog.txt
Since we have a game category in the add-on manager as of Leia, I thought I'd add this game to it as well.
=> [script.game.netwalk] 0.0.6 - added add-on to games category

script.embuary.helper/addon.xml, script.embuary.helper/default.py, script.embuary.helper/resources/language/resource.language.en_gb/strings.po, script.embuary.helper/resources/lib/kodi_monitor.py, script.embuary.helper/resources/lib/library.py, script.embuary.helper/resources/lib/utils.py
- Fixed missing path info value for widgets in info dialog
- Added font change and set info function 
- Removed unused windows hyperion grabber function …
=> [script.embuary.helper] 1.1.9

script.video.randomtv/addon.py, script.video.randomtv/addon.xml
Added Context Menu Item to play tv shows or seasons saved in Favourites
- [ X ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ X ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [ X ] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide …
=> [script.video.randomtv] 1.2.2

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/plugin_content.py
Extended get_similar function to get a new feature running in Embuary …
=> [script.embuary.helper] 1.2.0

script.tubecast/addon.xml, script.tubecast/resources/lib/tubecast/dial.py, script.tubecast/resources/lib/tubecast/ssdp.py, script.tubecast/resources/lib/tubecast/youtube/app.py, script.tubecast/resources/lib/tubecast/youtube/utils.py
=> [script.tubecast] v1.0.8

script.module.cache/addon.xml, script.module.cache/changelog.txt, script.module.cache/lib/cache.py
Sorry to PR so soon, just a couple of tiny bugs that were introduced in the initial RP review (my fault, I should have tested more...)
- bug-fix - Store retrieve method always returning empty Set.
- bug-fix - Sqlite error logging
- Housekeeping
=> [script.module.cache] 1.0.1

script.embuary.helper/addon.xml, script.embuary.helper/default.py, script.embuary.helper/resources/lib/helper.py, script.embuary.helper/resources/lib/library.py, script.embuary.helper/resources/lib/utils.py
- New required feature for upcoming Embuary version
- Fixed wrong parsed info labels
- Fixed cinema mode issues with shuffled playback setting
- Cleanup …
=> [script.embuary.helper] 1.2.2

service.watchedlist/addon.xml, service.watchedlist/changelog.txt, service.watchedlist/lib/watchedlist/utils.py, service.watchedlist/lib/watchedlist/watchedlist.py, service.watchedlist/resources/language/resource.language.en_gb/strings.po
Please merge these minor changes in my addon
=> [service.watchedlist] 1.2.7

script.embuary.helper/addon.xml, script.embuary.helper/default.py, script.embuary.helper/plugin.py, script.embuary.helper/resources/lib/library.py, script.embuary.helper/resources/lib/utils.py, script.embuary.helper/service.py
I'm sorry for the second PR on the same day, but I've deleted one line too much in the last cleanup and a important Embuary function broke.
-> fixed cinema mode
-> added splitline() function
-> added cast splitting
-> added lookforfile function
- This add-on repository has automated code guideline check which could help …
=> [script.embuary.helper] 1.2.8

script.module.uepg/addon.xml, script.module.uepg/epg.py, script.module.uepg/resources/skins/default/1080i/script.module.uepg.guide.xml, script.module.uepg/settings.py, script.module.uepg/uepg.py, script.module.uepg/utils.py
=> [script.module.uepg] 1.0.6

script.module.feedparser/LICENSE, script.module.feedparser/README.rst, script.module.feedparser/addon.xml, script.module.feedparser/changelog.txt, script.module.feedparser/lib/feedparser.py, script.module.feedparser/readme.txt
=> [script.module.feedparser] 5.2.1

script.module.pyhdhr/addon.xml, script.module.pyhdhr/lib/pyhdhr/PyHDHR.py
=> [script.module.pyhdhr] 1.0.7

service.subtitles.subsfactory/addon.xml, service.subtitles.subsfactory/changelog.txt, service.subtitles.subsfactory/service.py
- Addon setted as broken, Subsfactory community has closed!
=> [service.subtitles.subsfactory] 1.1.0

service.subtitles.subsfactory/addon.xml, service.subtitles.subsfactory/changelog.txt
"Backport" of https://github.com/xbmc/repo-scripts/pull/972
=> [service.subtitles.subsfactory] 1.1.0 - broken

script.100fm/addon.xml
Marking the addon as broken as requested by @KarellenX in https://github.com/xbmc/repo-scripts/issues/966
=> [script.100fm] 0.2.4

script.skin.info.service/Utils.py, script.skin.info.service/addon.xml
Sorry for the quick update but I was just informed on the forums about the lack of 4k support so I added it now.
- Add 4k support
- Update version number …
=> [script.skin.info.service] v1.0.5

script.embuary.helper/addon.xml, script.embuary.helper/resources/language/resource.language.es_es/strings.po, script.embuary.helper/resources/language/resource.language.pt_br/strings.po, script.embuary.helper/resources/lib/image.py, script.embuary.helper/resources/lib/json_map.py, script.embuary.helper/resources/lib/library.py, script.embuary.helper/resources/lib/player_monitor.py, script.embuary.helper/resources/lib/utils.py
- fixedcaching issue in blur function
- fixed exception in getsongartworks func
- added calc func
- added missing tag info value
- set shuffled back to false after it was set by the script and playback ended
- This add-on repository has automated code guideline check which could help you improve your coding. You can find …
=> [script.embuary.helper] 1.2.15

script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/config.py, script.module.inputstreamhelper/lib/inputstreamhelper.py, script.module.inputstreamhelper/resources/language/resource.language.nl_nl/strings.po
- Auto install inputstream.adaptive (mediaminister)
- Fix latest Widevine version detection (dagwieers)
- Check for Widevine updates on new release (mediaminister) …
=> [script.module.inputstreamhelper] 0.3.5

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/image.py, script.embuary.helper/resources/lib/player_monitor.py, script.embuary.helper/resources/lib/utils.py, script.embuary.helper/service.py
* Fixed exception in service
* Fixed restarting service monitor
* Fixed split function
* Fixed getkodisetting function
* Also disable the player monitor if service is disabled in the settings
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of …
=> [script.embuary.helper] 1.2.17

script.skin.info.service/addon.xml, script.skin.info.service/default.py
- Add set details support for areas outside library views like the Home Window …
=> [script.skin.info.service] v1.0.6

script.embuary.helper/addon.xml, script.embuary.helper/default.py, script.embuary.helper/resources/language/resource.language.en_gb/strings.po, script.embuary.helper/resources/lib/helper.py, script.embuary.helper/resources/lib/utils.py, script.embuary.helper/resources/settings.xml
* Added 'Get Add-on Setting' function for the upcoming Embuary Skin version
* Changed from PlaMedia to xbmc.Player().Play() …
=> [script.embuary.helper] 1.2.19

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/utils.py, script.embuary.helper/service.py
Hotfix update.
Case sensitive issue. …
=> [script.embuary.helper] 1.2.20

script.embuary.info/README.md, script.embuary.info/addon.xml, script.embuary.info/resources/lib/helper.py, script.embuary.info/resources/lib/tmdb_main.py, script.embuary.info/resources/lib/tmdb_utils.py
- Fixed encoding exception with umlauts in filenames/paths
- Added onback/onclose feature …
=> [script.embuary.info] 1.0.10

script.kodi.loguploader/addon.xml, script.kodi.loguploader/changelog.txt, script.kodi.loguploader/default.py
=> [script.kodi.loguploader] 0.5.0

script.embuary.info/README.md, script.embuary.info/addon.xml, script.embuary.info/resources/language/resource.language.es_es/strings.po, script.embuary.info/resources/language/resource.language.it_it/strings.po, script.embuary.info/resources/language/resource.language.pt_pt/strings.po, script.embuary.info/resources/language/resource.language.sk_sk/strings.po, script.embuary.info/resources/lib/helper.py, script.embuary.info/resources/lib/tmdb_person.py, script.embuary.info/resources/lib/tmdb_utils.py, script.embuary.info/resources/lib/tmdb_video.py, script.embuary.info/resources/settings.xml, script.embuary.info/resources/skins/default/1080i/script-embuary-person.xml, script.embuary.info/resources/skins/default/1080i/script-embuary-video.xml
* updated readme
* updated shipped windows
* added character role property
* added local media count properties
* always write to cache to get rid of broken cache data
* recache on version bumps
* language strings
- This add-on repository has automated code guideline check which could help you improve your coding. You can …
=> [script.embuary.info] 1.0.12

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/helper.py, script.embuary.helper/resources/lib/plugin_content.py, script.embuary.helper/resources/lib/plugin_listing.py
* copy skin nodes function
* get path stats function
* fixed unwanted logging …
=> [script.embuary.helper] 1.2.22

script.embuary.info/README.md, script.embuary.info/addon.xml, script.embuary.info/resources/language/resource.language.de_de/strings.po, script.embuary.info/resources/language/resource.language.en_gb/strings.po, script.embuary.info/resources/lib/helper.py, script.embuary.info/resources/lib/tmdb_person.py, script.embuary.info/resources/lib/tmdb_utils.py, script.embuary.info/resources/settings.xml
- added/improved filter option for show/movie results plus added option to disable them
- fixed missing FSK prefix for DE rating in movies
- added a few more properties like last/next aired episodes, belongs to collection, etc
- This add-on repository has automated code guideline check which could help you improve your …
=> [script.embuary.info] 1.0.13

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/default.py, script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py, script.module.inputstreamhelper/lib/inputstreamhelper/api.py, script.module.inputstreamhelper/lib/inputstreamhelper/config.py, script.module.inputstreamhelper/resources/language/resource.language.de_de/strings.po, script.module.inputstreamhelper/resources/language/resource.language.el_gr/strings.po, script.module.inputstreamhelper/resources/language/resource.language.en_gb/strings.po, script.module.inputstreamhelper/resources/language/resource.language.it_it/strings.po, script.module.inputstreamhelper/resources/language/resource.language.nl_nl/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ru_ru/strings.po, script.module.inputstreamhelper/resources/language/resource.language.sv_se/strings.po, script.module.inputstreamhelper/resources/settings.xml
This release includes urgent fixes for two problems that unfortunately emerged after the 0.4.1 release:
- Fix unresponsive Kodi when opening add-on information pane
- Revert a commit that broke Chrome OS extracting for some platforms
This release also contains a new InputStream Helper information settings page and some small improvements regarding add-on structure and performance.
- [PEP8](https://www.python.org/dev/peps/pep-0008/) …
=> [script.module.inputstreamhelper] 0.4.2

script.module.routing/.gitignore, script.module.routing/.travis.yml, script.module.routing/Makefile, script.module.routing/README.md, script.module.routing/addon.xml, script.module.routing/lib/routing.py, script.module.routing/lib/tests.py, script.module.routing/pylintrc, script.module.routing/requirements.txt
=> [script.module.routing] 0.2.2

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/helper.py, script.embuary.helper/resources/lib/image.py, script.embuary.helper/resources/lib/library.py, script.embuary.helper/resources/lib/player_monitor.py, script.embuary.helper/resources/lib/plugin_content.py, script.embuary.helper/resources/lib/utils.py
- imginfo function
- another select dialog feature
- fixed wrong argument name
- minor tweaks …
=> [script.embuary.helper] 1.2.23

script.embuary.info/README.md, script.embuary.info/addon.xml, script.embuary.info/default.py, script.embuary.info/plugin.py, script.embuary.info/resources/language/resource.language.de_de/strings.po, script.embuary.info/resources/language/resource.language.en_gb/strings.po, script.embuary.info/resources/language/resource.language.es_es/strings.po, script.embuary.info/resources/language/resource.language.hu_hu/strings.po, script.embuary.info/resources/language/resource.language.it_it/strings.po, script.embuary.info/resources/language/resource.language.pt_BR/strings.po, script.embuary.info/resources/language/resource.language.sk_sk/strings.po, script.embuary.info/resources/lib/helper.py, script.embuary.info/resources/lib/main.py, script.embuary.info/resources/lib/person.py, script.embuary.info/resources/lib/season.py, script.embuary.info/resources/lib/utils.py, script.embuary.info/resources/lib/video.py, script.embuary.info/resources/lib/widgets.py, script.embuary.info/resources/settings.xml, script.embuary.info/resources/skins/default/1080i/script-embuary-video.xml
- Added collection items
- Added season items
- Added season dialog
- Added poster images
- Bigger cleanup and improvements …
=> [script.embuary.info] 1.0.16

script.module.dropbox/addon.xml, script.module.dropbox/lib/dropbox/dropbox.py, script.module.dropbox/lib/dropbox/pkg_resources.py, script.module.dropbox/lib/dropbox/session.py
* Fix Windows import errors (@robweber)
* Make qrcode module an optional dependency (@robweber)
=> [script.module.dropbox] 8.4.2

script.module.arlo/README.md, script.module.arlo/addon.xml, script.module.arlo/lib/arlo.py
=> [script.module.arlo] 1.2.27

script.embuary.info/README.md, script.embuary.info/addon.xml, script.embuary.info/resources/language/resource.language.it_it/strings.po, script.embuary.info/resources/language/resource.language.pt_BR/strings.po, script.embuary.info/resources/language/resource.language.sk_sk/strings.po, script.embuary.info/resources/lib/helper.py, script.embuary.info/resources/lib/utils.py, script.embuary.info/resources/settings.xml
- Small hotfix release for partly broken certification function
- New region release info label
- Added missing languages …
=> [script.embuary.info] 1.0.19

script.embuary.info/README.md, script.embuary.info/addon.xml, script.embuary.info/resources/language/resource.language.de_de/strings.po, script.embuary.info/resources/language/resource.language.en_gb/strings.po, script.embuary.info/resources/lib/utils.py, script.embuary.info/resources/lib/widgets.py
- fixed missing year and premiered date for TV shows
- added trending widgets …
=> [script.embuary.info] 1.0.20

script.embuary.helper/addon.xml, script.embuary.helper/plugin.py, script.embuary.helper/resources/lib/helper.py, script.embuary.helper/resources/lib/player_monitor.py, script.embuary.helper/resources/lib/plugin_content.py, script.embuary.helper/resources/lib/plugin_listing.py, script.embuary.helper/resources/lib/utils.py
- Added Container.PluginCategory info label for widgets
- Extended functions to get TV show data by season or episode ID …
=> [script.embuary.helper] 1.2.25

screensaver.google.earth/addon.xml, screensaver.google.earth/default.py, screensaver.google.earth/gui.py
=> [screensaver.google.earth] 1.0.5

script.module.srgssr/README.md, script.module.srgssr/addon.xml, script.module.srgssr/lib/dummycache.py, script.module.srgssr/lib/srgssr.py, script.module.srgssr/lib/utils.py, script.module.srgssr/resources/language/resource.language.de_de/strings.po, script.module.srgssr/resources/language/resource.language.en_gb/strings.po, script.module.srgssr/resources/language/resource.language.fr_fr/strings.po, script.module.srgssr/resources/language/resource.language.it_it/strings.po
- Add feature to search for medias and TV/radio shows.
- Remove `dummycache.py` since `SimpleCache` is now Python 3 compatible. …
=> [script.module.srgssr] 1.7.0

script.embuary.helper/addon.xml, script.embuary.helper/resources/language/resource.language.de_de/strings.po, script.embuary.helper/resources/language/resource.language.en_gb/strings.po, script.embuary.helper/resources/lib/helper.py, script.embuary.helper/resources/lib/image.py, script.embuary.helper/resources/lib/library.py, script.embuary.helper/resources/lib/player_monitor.py, script.embuary.helper/resources/lib/plugin_content.py, script.embuary.helper/resources/lib/plugin_listing.py, script.embuary.helper/resources/lib/utils.py, script.embuary.helper/resources/settings.xml, script.embuary.helper/service.py
- Added: Automatically generate genre thumbnails
- Added: Auto maintaining of addon_data image folder to delete older files to don't waste storage space. Often used images get touched to update the modification date
- Extended: Genre widgets can be filtered by library tag now
- Reworked: Plugin listing & auto detection for library tags
- Reworked: Image functions
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is …
=> [script.embuary.helper] 1.2.28

script.hdhomerun.view/addon.xml, script.hdhomerun.view/changelog.txt, script.hdhomerun.view/lib/hdhr/storageservers.py, script.hdhomerun.view/lib/player.py, script.hdhomerun.view/resources/language/English/strings.po
Fix seeking recorded videos
Update some internal request methods …
=> [script.hdhomerun.view] 2019.9.15

service.subtitles.supersubtitles/addon.xml, service.subtitles.supersubtitles/service.py
- fix/ignore some character encoding errors …
=> [service.subtitles.supersubtitles] 0.0.24

script.embuary.info/addon.xml, script.embuary.info/resources/language/resource.language.es_es/strings.po, script.embuary.info/resources/language/resource.language.it_it/strings.po, script.embuary.info/resources/language/resource.language.nl_NL/strings.po, script.embuary.info/resources/language/resource.language.pt_BR/strings.po, script.embuary.info/resources/language/resource.language.zh_CN/strings.po, script.embuary.info/resources/lib/helper.py, script.embuary.info/resources/lib/utils.py, script.embuary.info/resources/lib/widgets.py
- Fixed "trending movies" widget
- Fixed "XFILE::CFileFactory::CreateLoader" log spamming with widgets
Edit:
- Disabled "memory" cache to avoid crashes on Android systems (I guess it's related to it). 
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the …
=> [script.embuary.info] 1.0.22

script.module.libswr/addon.xml
The content migrated to the ARD Mediathek, the scraper is not needed anymore. …
=> [script.module.libswr] 1.0.1

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/changelog.txt, service.xbmc.versioncheck/resources/language/English/strings.po, service.xbmc.versioncheck/resources/versions.txt
=> [service.xbmc.versioncheck] v0.4.7

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/default.py, script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py, script.module.inputstreamhelper/lib/inputstreamhelper/api.py, script.module.inputstreamhelper/lib/inputstreamhelper/config.py, script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py, script.module.inputstreamhelper/lib/inputstreamhelper/unicodehelper.py, script.module.inputstreamhelper/resources/language/resource.language.el_gr/strings.po, script.module.inputstreamhelper/resources/language/resource.language.en_gb/strings.po, script.module.inputstreamhelper/resources/language/resource.language.fr_fr/strings.po, script.module.inputstreamhelper/resources/language/resource.language.it_it/strings.po, script.module.inputstreamhelper/resources/language/resource.language.nl_nl/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ru_ru/strings.po, script.module.inputstreamhelper/resources/language/resource.language.sv_se/strings.po, script.module.inputstreamhelper/resources/settings.xml
- Added French translation
- Updated translations
- Ensure Kodi 19 compatibility
- Configurable temporary download directory for devices with limited space
- Configurable Widevine CDM update frequency
- Fix add-on settings crashes when InputStream Adaptive is missing
- Improve unicode character support
- Some code structure improvements
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise but …
=> [script.module.inputstreamhelper] 0.4.3

script.module.trakt/addon.xml, script.module.trakt/changelog.txt, script.module.trakt/lib/CHANGES.rst, script.module.trakt/lib/trakt/core/helpers.py, script.module.trakt/lib/trakt/core/http.py, script.module.trakt/lib/trakt/interfaces/users/__init__.py, script.module.trakt/lib/trakt/interfaces/users/lists/__init__.py, script.module.trakt/lib/trakt/objects/episode.py, script.module.trakt/lib/trakt/objects/movie.py, script.module.trakt/lib/trakt/objects/rating.py, script.module.trakt/lib/trakt/objects/season.py, script.module.trakt/lib/trakt/objects/show.py, script.module.trakt/lib/trakt/version.py
Small update adding two features
=> [script.module.trakt] 3.1.0

script.embuary.info/README.md, script.embuary.info/addon.xml, script.embuary.info/plugin.py, script.embuary.info/resources/language/resource.language.hu_hu/strings.po, script.embuary.info/resources/lib/helper.py, script.embuary.info/resources/lib/main.py, script.embuary.info/resources/lib/utils.py, script.embuary.info/resources/lib/widgets.py
- added search by dbid incl. fallback logic if unique id is not present
- improved widget listing
- cleanup …
=> [script.embuary.info] 1.1.2

script.module.addon.signals/addon.xml, script.module.addon.signals/changelog.txt, script.module.addon.signals/lib/AddonSignals.py
=> [script.module.addon.signals] 0.0.4

script.xbmc.lcdproc/addon.xml, script.xbmc.lcdproc/changelog.txt, script.xbmc.lcdproc/resources/lib/lcdproc.py
- Allow LCDproc protocol version 0.4 …
=> [script.xbmc.lcdproc] 3.0.6

script.embuary.info/README.md, script.embuary.info/addon.xml, script.embuary.info/resources/language/resource.language.en_gb/strings.po, script.embuary.info/resources/language/resource.language.it_it/strings.po, script.embuary.info/resources/language/resource.language.nl_NL/strings.po, script.embuary.info/resources/language/resource.language.ru_RU/strings.po, script.embuary.info/resources/lib/helper.py, script.embuary.info/resources/lib/main.py, script.embuary.info/resources/lib/person.py, script.embuary.info/resources/lib/utils.py, script.embuary.info/resources/lib/video.py, script.embuary.info/resources/settings.xml
- fixed "year" argument for tv show queries
- added optional exact search option
- added option to hide upcoming items by day delta value
Edit:
Fixed small possible exception with the new day delta filter
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the …
=> [script.embuary.info] 1.1.8

script.module.python.twitch/addon.xml, script.module.python.twitch/changelog.txt, script.module.python.twitch/resources/lib/twitch/api/usher.py, script.module.python.twitch/resources/lib/twitch/api/v5/games.py, script.module.python.twitch/resources/lib/twitch/api/v5/videos.py, script.module.python.twitch/resources/lib/twitch/parser.py, script.module.python.twitch/resources/lib/twitch/queries.py, script.module.python.twitch/resources/lib/twitch/scraper.py
2.0.10
[upd] allow overriding headers for all hidden api calls
2.0.9
[upd] allow overriding headers for usher and hidden api calls
[fix] decode byte responses in scraper
[fix] usher/parser error handling
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the …
=> [script.module.python.twitch] v2.0.10

script.module.youtube.dl/addon.xml, script.module.youtube.dl/changelog.txt, script.module.youtube.dl/lib/YDStreamExtractor.py, script.module.youtube.dl/lib/yd_private_libs/servicecontrol.py, script.module.youtube.dl/resources/language/German/strings.po, script.module.youtube.dl/service.py
Fix some stupid stuff that won't play well with PR #1204 
Add German translation …
=> [script.module.youtube.dl] 19.912.1

script.artistslideshow-helper/addon.xml
Requested by the author in https://github.com/xbmc/repo-scripts/issues/1203
=> [script.artistslideshow-helper] broken

script.logviewer/addon.xml, script.logviewer/changelog.txt, script.logviewer/resources/language/English/strings.po, script.logviewer/resources/language/Portuguese (Brazil)/strings.po, script.logviewer/resources/language/Portuguese/strings.po, script.logviewer/resources/lib/logreader.py, script.logviewer/resources/lib/logviewer.py, script.logviewer/resources/lib/navigation.py, script.logviewer/resources/lib/service.py, script.logviewer/resources/lib/utils.py, script.logviewer/resources/settings.xml
- **General**
- Version number: 2.1.0
- URL: 
- Python 3 compatibility
- Fix log error detection service after kodi's migration to libfmt
=> [script.logviewer] 2.1.0

script.tubecast/addon.xml, script.tubecast/resources/lib/kodi/kodilogging.py, script.tubecast/resources/lib/kodi/utils.py, script.tubecast/resources/lib/tubecast/kodicast.py, script.tubecast/resources/lib/tubecast/ssdp.py, script.tubecast/resources/lib/tubecast/utils.py, script.tubecast/resources/lib/tubecast/youtube/app.py, script.tubecast/resources/lib/tubecast/youtube/utils.py
- **General**
- Version number: 1.2.0
- URL: 
[new] Support for python3
[fix] Queues autoplayback
=> [script.tubecast] 1.2.0

script.common.plugin.cache/addon.xml, script.common.plugin.cache/changelog.txt, script.common.plugin.cache/resources/lib/service.py, script.common.plugin.cache/resources/lib/storage_server/StorageServer.py
[fix] shutdown taking longer than 5 seconds
[fix] ignore encoding issues for socket data …
=> [script.common.plugin.cache] 2.6.1

script.module.six/addon.xml, script.module.six/lib/six.py
Updates the six module to the latest version
=> [script.module.six] 1.13.0

script.kodi.android.update/addon.xml, script.kodi.android.update/default.py, script.kodi.android.update/resources/language/resource.language.en_gb/strings.po, script.kodi.android.update/resources/settings.xml, script.kodi.android.update/select.py, script.kodi.android.update/service.py
=> [script.kodi.android.update] 1.1.7

script.kodi.windows.update/addon.xml, script.kodi.windows.update/default.py, script.kodi.windows.update/resources/language/resource.language.en_gb/strings.po, script.kodi.windows.update/service.py
=> [script.kodi.windows.update] 1.1.1

script.module.addon.signals/README.md, script.module.addon.signals/addon.xml, script.module.addon.signals/changelog.txt, script.module.addon.signals/lib/AddonSignals.py
=> [script.module.addon.signals] 0.0.5

script.metadata.editor/addon.xml, script.metadata.editor/resources/lib/functions.py, script.metadata.editor/resources/lib/helper.py, script.metadata.editor/resources/lib/rating_updater.py
small hotfix if tmdb id is wrong or tmdb is not returning a result …
=> [script.metadata.editor] 1.1.2

script.module.xbmcswift2/README, script.module.xbmcswift2/README.md, script.module.xbmcswift2/addon.xml, script.module.xbmcswift2/changelog.txt, script.module.xbmcswift2/lib/xbmcswift2/__init__.py, script.module.xbmcswift2/lib/xbmcswift2/actions.py, script.module.xbmcswift2/lib/xbmcswift2/common.py, script.module.xbmcswift2/lib/xbmcswift2/constants.py, script.module.xbmcswift2/lib/xbmcswift2/listitem.py, script.module.xbmcswift2/lib/xbmcswift2/logger.py, script.module.xbmcswift2/lib/xbmcswift2/module.py, script.module.xbmcswift2/lib/xbmcswift2/plugin.py, script.module.xbmcswift2/lib/xbmcswift2/request.py, script.module.xbmcswift2/lib/xbmcswift2/urls.py, script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py
- **General**
- Version number: 2.5.0
- URL: 
=> [script.module.xbmcswift2] 2.5.0

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/cinema_mode.py, script.embuary.helper/resources/lib/image.py, script.embuary.helper/resources/lib/utils.py
- Fixed cinema mode trailers
- Fixed indentation error …
=> [script.embuary.helper] 1.3.8

script.embuary.info/README.md, script.embuary.info/addon.xml, script.embuary.info/resources/language/resource.language.it_it/strings.po, script.embuary.info/resources/language/resource.language.nl_NL/strings.po, script.embuary.info/resources/language/resource.language.ru_RU/strings.po, script.embuary.info/resources/language/resource.language.sk_sk/strings.po, script.embuary.info/resources/lib/main.py, script.embuary.info/resources/lib/person.py
- Added optional combined list (movies + tvshows).
- Mute exception errors if skins don't want to show all available tmdb information. …
=> [script.embuary.info] 1.2.0

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/cinema_mode.py, script.embuary.helper/resources/lib/helper.py, script.embuary.helper/resources/lib/image.py, script.embuary.helper/resources/lib/library.py, script.embuary.helper/resources/lib/player_monitor.py, script.embuary.helper/resources/lib/plugin_listing.py
Some fixes for Python 3 compatiblity plus support for ListItem.Art(logo) if whitelisted in advancedsettings and available …
=> [script.embuary.helper] 1.3.9

script.module.phate89/addon.xml, script.module.phate89/changelog.txt, script.module.phate89/lib/phate89lib/kodiutils.py, script.module.phate89/lib/phate89lib/rutils.py, script.module.phate89/lib/phate89lib/staticutils.py
Added support for python 3.0 and new function for other addon updates …
=> [script.module.phate89] 1.2.0

script.module.simplecache/addon.xml, script.module.simplecache/lib/simplecache.py
=> [script.module.simplecache] 1.0.18

script.lazytv/addon.xml, script.lazytv/default.py, script.lazytv/resources/addon_clone.xml, script.lazytv/resources/episode_exporter.py, script.lazytv/resources/language/resource.language.en_GB/strings.po, script.lazytv/resources/main.py, script.lazytv/resources/main_service.py, script.lazytv/resources/selector.py, script.lazytv/resources/settings.xml, script.lazytv/service.py
added optional ordering of smartplaylist …
=> [script.lazytv] 3.0.1

script.tubecast/README.md, script.tubecast/addon.xml, script.tubecast/resources/lib/tubecast/chromecast.py, script.tubecast/resources/lib/tubecast/ssdp.py, script.tubecast/resources/lib/tubecast/youtube/app.py, script.tubecast/resources/lib/tubecast/youtube/kodibrigde.py, script.tubecast/resources/lib/tubecast/youtube/player.py
- **General**
- Version number: 1.3.0
- URL: 
[new] avoid reverse dns from bottle (contrib karl34)
[new] respect current time in setPlaylist commands (contrib siku2)
[fix] fix addon shutdown (contrib siku2)
=> [script.tubecast] 1.3.0

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/plugin_content.py
Hotfix for logic issue in nextup widgets …
=> [script.embuary.helper] 1.4.2

script.module.pathtools/LICENSE, script.module.pathtools/README, script.module.pathtools/addon.xml, script.module.pathtools/lib/pathtools/__init__.py, script.module.pathtools/lib/pathtools/path.py, script.module.pathtools/lib/pathtools/patterns.py, script.module.pathtools/lib/pathtools/version.py
=> [script.module.pathtools] 0.1.2

context.embuary.info/addon.py, context.embuary.info/addon.xml
Fixed wrong results by using DBID instead of IMDBnumber (can be everything, not only imdb) …
=> [context.embuary.info] 1.0.1

script.metadata.editor/addon.xml, script.metadata.editor/context.py, script.metadata.editor/resources/language/resource.language.nl_NL/strings.po
=> [script.metadata.editor] 2.0.6

script.module.xbmcswift2/addon.xml, script.module.xbmcswift2/changelog.txt, script.module.xbmcswift2/lib/xbmcswift2/storage.py
- **General**
- Version number: 2.5.1
- URL: 
=> [script.module.xbmcswift2] 2.5.1

script.tubecast/README.md, script.tubecast/addon.xml, script.tubecast/resources/language/resource.language.en_gb/strings.po, script.tubecast/resources/lib/kodi/kodilogging.py, script.tubecast/resources/lib/service.py, script.tubecast/resources/lib/tubecast/chromecast.py, script.tubecast/resources/lib/tubecast/dial.py, script.tubecast/resources/lib/tubecast/ssdp.py, script.tubecast/resources/lib/tubecast/youtube/app.py, script.tubecast/resources/lib/tubecast/youtube/player.py, script.tubecast/resources/lib/tubecast/youtube/utils.py, script.tubecast/resources/lib/tubecast/youtube/volume.py, script.tubecast/resources/settings.xml
- **General**
- Version number: 1.4.1
- URL: 
[fix] use random port (contrib siku2)
[new] various improvements (contrib siku2)
[improvement] improve command parser
=> [script.tubecast] 1.4.1

script.module.arlo/addon.xml, script.module.arlo/lib/arlo.py
Upgrade to v 1.2.33
Use patched version of sseclient (ssearlo) due to bug in sseclient.
NOTE:
3 items need to be merged at the same time
- [script.module.ssearlo] 0.0.22
- [script.module.arlo] 1.2.33
- [plugin.video.arlowview] 1.1.0
- [ x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [x ] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the …
=> [script.module.arlo] 1.2.33

script.module.watchdog/LICENSE, script.module.watchdog/README.rst, script.module.watchdog/addon.xml, script.module.watchdog/lib/watchdog/__init__.py, script.module.watchdog/lib/watchdog/events.py, script.module.watchdog/lib/watchdog/observers/__init__.py, script.module.watchdog/lib/watchdog/observers/api.py, script.module.watchdog/lib/watchdog/observers/fsevents.py, script.module.watchdog/lib/watchdog/observers/fsevents2.py, script.module.watchdog/lib/watchdog/observers/inotify.py, script.module.watchdog/lib/watchdog/observers/inotify_buffer.py, script.module.watchdog/lib/watchdog/observers/inotify_c.py, script.module.watchdog/lib/watchdog/observers/kqueue.py, script.module.watchdog/lib/watchdog/observers/polling.py, script.module.watchdog/lib/watchdog/observers/read_directory_changes.py, script.module.watchdog/lib/watchdog/observers/winapi.py, script.module.watchdog/lib/watchdog/tricks/__init__.py, script.module.watchdog/lib/watchdog/utils/__init__.py, script.module.watchdog/lib/watchdog/utils/bricks.py, script.module.watchdog/lib/watchdog/utils/compat.py, script.module.watchdog/lib/watchdog/utils/delayed_queue.py, script.module.watchdog/lib/watchdog/utils/dirsnapshot.py, script.module.watchdog/lib/watchdog/utils/echo.py, script.module.watchdog/lib/watchdog/utils/platform.py, script.module.watchdog/lib/watchdog/utils/unicode_paths.py, script.module.watchdog/lib/watchdog/utils/win32stat.py, script.module.watchdog/lib/watchdog/version.py, script.module.watchdog/lib/watchdog/watchmedo.py
=> script.module.watchdog

script.module.clouddrive.common/addon.xml, script.module.clouddrive.common/clouddrive/common/remote/oauth2.py, script.module.clouddrive.common/clouddrive/common/remote/request.py, script.module.clouddrive.common/clouddrive/common/service/player.py, script.module.clouddrive.common/clouddrive/common/ui/addon.py, script.module.clouddrive.common/clouddrive/common/utils.py, script.module.clouddrive.common/resources/language/resource.language.en_gb/strings.po
=> [script.module.clouddrive.common] 1.2.10

script.sharethetv/addon.xml
Requested by @KarellenX in https://github.com/xbmc/repo-scripts/pull/1303
=> [script.sharetv] broken

script.artistslideshow/addon.xml, script.artistslideshow/default.py, script.artistslideshow/resources/language/resource.language.en_gb/strings.po, script.artistslideshow/resources/lib/artistslideshow.py, script.artistslideshow/resources/plugins/fanarttv.py, script.artistslideshow/resources/plugins/lastfm.py, script.artistslideshow/resources/plugins/theaudiodb.py, script.artistslideshow/resources/settings.xml
v.3.2.0
- added option to pause slideshow when playback pauses
- logic change to load first slideshow image sooner
- override slideshow no longer resets at each song change
- fix for potential runaway loop
- fix for slow slideshow change when artist changes
- fix for AS not reloading settings properly when in daemon mode
- fixes for miscellaneous UTF8 errors
- internal change to the way the main thread talks to the slideshow thread
Note that once this one is cleared, I'll submit another to the Matrix branch with the updated python requirement and a higher version number (as per the forum post regarding this).
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi …
=> [script.artistslideshow] 3.2.0

script.module.python.twitch/addon.xml, script.module.python.twitch/changelog.txt, script.module.python.twitch/resources/lib/twitch/parser.py
=> [script.module.python.twitch] 2.0.11

script.metadata.editor/addon.xml, script.metadata.editor/resources/language/resource.language.tr_TR/strings.po, script.metadata.editor/resources/lib/editor.py, script.metadata.editor/resources/lib/rating_updater.py
* drop "dateadded" and "lastplayed" as editable fields for shows (linked to episodes)
* fixed encoding issue …
=> [script.metadata.editor] 2.0.7

script.embuary.info/README.md, script.embuary.info/addon.xml, script.embuary.info/default.py, script.embuary.info/plugin.py, script.embuary.info/resources/language/resource.language.de_de/strings.po, script.embuary.info/resources/language/resource.language.en_gb/strings.po, script.embuary.info/resources/lib/helper.py, script.embuary.info/resources/lib/localdb.py, script.embuary.info/resources/lib/main.py, script.embuary.info/resources/lib/nextaired.py, script.embuary.info/resources/lib/omdb.py, script.embuary.info/resources/lib/person.py, script.embuary.info/resources/lib/season.py, script.embuary.info/resources/lib/tmdb.py, script.embuary.info/resources/lib/trakt.py, script.embuary.info/resources/lib/tvdb.py, script.embuary.info/resources/lib/video.py, script.embuary.info/resources/lib/widgets.py, script.embuary.info/resources/settings.xml, script.embuary.info/resources/skins/default/1080i/script-embuary-person.xml, script.embuary.info/resources/skins/default/1080i/script-embuary-video.xml, script.embuary.info/service.py
* added "next aired"
* use plugin routing
* fixed minor issues …
=> [script.embuary.info] 1.2.3

script.embuary.info/addon.xml, script.embuary.info/resources/language/resource.language.ru_RU/strings.po, script.embuary.info/resources/lib/helper.py, script.embuary.info/resources/lib/nextaired.py, script.embuary.info/resources/lib/widgets.py, script.embuary.info/service.py
* Next aired: UTC<->Local timezone logic issue hotfix
* Next aired: improved caching …
=> [script.embuary.info] 1.2.4

script.module.clouddrive.common/addon.xml, script.module.clouddrive.common/clouddrive/common/export.py, script.module.clouddrive.common/clouddrive/common/service/export.py, script.module.clouddrive.common/clouddrive/common/ui/addon.py, script.module.clouddrive.common/clouddrive/common/ui/dialog.py, script.module.clouddrive.common/clouddrive/common/ui/utils.py, script.module.clouddrive.common/clouddrive/common/utils.py, script.module.clouddrive.common/resources/language/resource.language.en_gb/strings.po, script.module.clouddrive.common/resources/skins/default/1080i/export-main-dialog.xml
=> [script.module.clouddrive.common] 1.2.11

script.embuary.info/addon.xml, script.embuary.info/resources/lib/helper.py
Dead people everywhere caused by a wrong date handling.
(actor deathday property fix) …
=> [script.embuary.info] 1.2.5

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/player_monitor.py, script.embuary.helper/resources/lib/plugin_content.py, script.embuary.helper/resources/lib/service_monitor.py, script.embuary.helper/resources/lib/utils.py
* use monitor instead of longer xmbc.sleep()
* fixed not working bluring on skin change
* only blur player icon if enabled
* cleanup …
=> [script.embuary.helper] 1.4.3

service.xbmc.versioncheck/LICENSES/Apache-2.0.txt, service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/changelog.txt, service.xbmc.versioncheck/resources/lib/version_check/distro/__init__.py, service.xbmc.versioncheck/resources/lib/version_check/distro/distro.py, service.xbmc.versioncheck/resources/lib/version_check/service.py, service.xbmc.versioncheck/resources/versions.txt
=> [service.xbmc.versioncheck] 0.5.4

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/player_monitor.py
=> [script.embuary.helper] 1.4.4

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/player_monitor.py
=> [script.embuary.helper] 2.0.1

script.module.routing/addon.xml
=> [script.module.routing] 0.2.3+matrix.1

service.subtitles.opensubtitles/README.md, service.subtitles.opensubtitles/addon.xml, service.subtitles.opensubtitles/changelog.txt, service.subtitles.opensubtitles/service.py
service.subtitles.opensubtitles v5.1.1
- Fixed issue with language flag icons …
=> [service.subtitles.opensubtitles] 5.1.1

script.sublissimo/addon.xml, script.sublissimo/resources/language/resource.language.en_gb/strings.po, script.sublissimo/resources/lib/play_along_file.py, script.sublissimo/resources/lib/script.py, script.sublissimo/resources/lib/sync_by_frame_rate.py, script.sublissimo/resources/lib/syncwizard.py
- New: frame rate conversion on the fly
- New: play modified subtitle directly on video
- Minor bugfixes …
=> [script.sublissimo] 0.0.2

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/image.py
Fixed issues with image:// paths, which are pointing to file embedded thumbs. …
=> [script.embuary.helper] 1.4.5

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/image.py
Fixed issues with image:// paths, which are pointing to file embedded thumbs. …
=> [script.embuary.helper] 2.0.2

script.module.python.twitch/addon.xml, script.module.python.twitch/changelog.txt, script.module.python.twitch/resources/lib/twitch/api/usher.py, script.module.python.twitch/resources/lib/twitch/parser.py, script.module.python.twitch/resources/lib/twitch/queries.py
=> [script.module.python.twitch] 2.0.12

script.module.python.twitch/addon.xml, script.module.python.twitch/resources/lib/twitch/api/usher.py, script.module.python.twitch/resources/lib/twitch/parser.py, script.module.python.twitch/resources/lib/twitch/queries.py
=> [script.module.python.twitch] 2.0.12+matrix.1

script.module.beautifulsoup4/AUTHORS.txt, script.module.beautifulsoup4/LICENSE, script.module.beautifulsoup4/NEWS.txt, script.module.beautifulsoup4/README.md, script.module.beautifulsoup4/addon.xml, script.module.beautifulsoup4/lib/bs4/__init__.py, script.module.beautifulsoup4/lib/bs4/builder/__init__.py, script.module.beautifulsoup4/lib/bs4/builder/_html5lib.py, script.module.beautifulsoup4/lib/bs4/builder/_htmlparser.py, script.module.beautifulsoup4/lib/bs4/builder/_lxml.py, script.module.beautifulsoup4/lib/bs4/dammit.py, script.module.beautifulsoup4/lib/bs4/diagnose.py, script.module.beautifulsoup4/lib/bs4/element.py, script.module.beautifulsoup4/lib/bs4/formatter.py, script.module.beautifulsoup4/lib/bs4/testing.py
we're currently quite a few versions behind, so let's update beautifulsoup4 to the latest version.
this needs a new dependency: [script.module.soupsieve](https://github.com/xbmc/repo-scripts/pull/1363).
=> [script.module.beautifulsoup4] 4.8.2+matrix.1

script.plex/addon.xml, script.plex/changelog.txt, script.plex/lib/windows/seekdialog.py
This should be the last update of this add-on against Kodi 17. Just fixes one annoying bug. …
=> [script.plex] 0.1.8

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py, script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py, script.module.inputstreamhelper/lib/inputstreamhelper/unicodes.py, script.module.inputstreamhelper/lib/inputstreamhelper/utils.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py, script.module.inputstreamhelper/resources/language/resource.language.es_es/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ro_ro/strings.po, script.module.inputstreamhelper/resources/settings.xml
- **General**
- Version number: 0.4.5+matrix.1
- URL: 
v0.4.5 (2020-04-07)
- Added Spanish and Romanian translations
- Added support for Kodi 19 Matrix "pre-release" builds
- Fix Widevine backups when using an external drive
- Various fixes for Widevine installation on ARM devices
=> [script.module.inputstreamhelper@matrix] 0.4.5+matrix.1

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py, script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py, script.module.inputstreamhelper/lib/inputstreamhelper/unicodes.py, script.module.inputstreamhelper/lib/inputstreamhelper/utils.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py, script.module.inputstreamhelper/resources/language/resource.language.es_es/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ro_ro/strings.po, script.module.inputstreamhelper/resources/settings.xml
- **General**
- Version number: 0.4.5
- URL: 
v0.4.5 (2020-04-07)
- Added Spanish and Romanian translations
- Added support for Kodi 19 Matrix "pre-release" builds
- Fix Widevine backups when using an external drive
- Various fixes for Widevine installation on ARM devices
=> [script.module.inputstreamhelper] 0.4.5

script.module.pyqrcode/addon.xml
=> [script.module.pyqrcode] 1.2.1+matrix.2

service.subtitles.legendasdivx/addon.xml, service.subtitles.legendasdivx/changelog.txt, service.subtitles.legendasdivx/service.py
Since vfs.rar got fixed by Alwinus, extraction code changed to work accordingly. …
=> [service.subtitles.legendasdivx] v0.3.0

script.module.xbmcswift2/README.md, script.module.xbmcswift2/addon.xml, script.module.xbmcswift2/changelog.txt, script.module.xbmcswift2/lib/xbmcswift2/common.py, script.module.xbmcswift2/lib/xbmcswift2/listitem.py, script.module.xbmcswift2/lib/xbmcswift2/plugin.py, script.module.xbmcswift2/lib/xbmcswift2/request.py, script.module.xbmcswift2/lib/xbmcswift2/urls.py, script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py
- **General**
- Version number: 13.0.0
=> [script.module.xbmcswift2@gotham] 13.0.0

script.globalsearch/addon.xml, script.globalsearch/changelog.txt, script.globalsearch/default.py, script.globalsearch/lib/defs.py, script.globalsearch/lib/gui.py
script is currently broken due to the removal of some deprecated api methods.
globalsearch was still using iconImage / thumbnailImage in one place. …
=> [script.globalsearch] 9.0.3

service.scrobbler.librefm/addon.xml, service.scrobbler.librefm/changelog.txt, service.scrobbler.librefm/default.py, service.scrobbler.librefm/lib/librefm.py, service.scrobbler.librefm/resources/language/resource.language.en_GB/strings.po, service.scrobbler.librefm/resources/settings.xml
new version:
- mainly a code refactor to get a small entry point
- remove deprecated startup argument in addon.xml 
- add news section to addon.xml
=> [service.scrobbler.librefm] 4.0.4

script.plex/addon.xml
=> [script.plex] 0.3.0

script.playalbum/README.txt, script.playalbum/addon.xml, script.playalbum/changelog.txt, script.playalbum/default.py, script.playalbum/lib/playalbum.py
updated version:
- code refactor to get a small entry-point.
- cleanup addon.xml …
=> [script.playalbum] 4.0.2

script.favourites/addon.xml, script.favourites/changelog.txt, script.favourites/lib/favourites.py
crash fix when user has no favourites. …
=> [script.favourites] 8.1.1

script.openweathermap.maps/addon.xml, script.openweathermap.maps/changelog.txt, script.openweathermap.maps/lib/maps.py
crash fix when weather maps fail to download …
=> [script.openweathermap.maps] 1.0.5

script.artistslideshow/addon.xml, script.artistslideshow/resources/language/resource.language.es_es/strings.po, script.artistslideshow/resources/plugins/lastfm.py
v.3.2.2
- fix for crash if Artist Information folder is stored on a network volume
- Spanish translations …
=> [script.artistslideshow] 3.2.2

weather.ozweather/addon.xml, weather.ozweather/changelog.txt, weather.ozweather/resources/lib/weatherzone.py
Minor update to deal with upstream scraper changes.
There is some whitespace changes in here too - sorry, it's the beginnings of some Python 3 / Leia work.
(I would appreciate if this could just get merged as is to keep folks getting their weather - this is a Python 2 version, for Krypton and below.... I will prepare a Python 3 / Leia version separately in due course).
=> [weather.ozweather] 1.0.2

script.artistslideshow/addon.xml, script.artistslideshow/resources/language/resource.language.es_es/strings.po, script.artistslideshow/resources/plugins/lastfm.py
v.3.2.102
- fix for crash if Artist Information folder is stored on a network volume
- Spanish translations
This is identical to the code approved for Leia in PR #1471. The only changes are to the version number and dependency versions.
- This add-on repository has automated code guideline check which could help you …
=> [script.artistslideshow] 3.2.102

weather.multi/addon.xml, weather.multi/changelog.txt, weather.multi/lib/conversions.py, weather.multi/lib/providers/yahoo.py, weather.multi/lib/weather.py
changes since the last version:
- fix location search
- fix yahoo daily weather …
=> [weather.multi] 0.0.4

script.embuary.helper/addon.xml, script.embuary.helper/resources/language/resource.language.es_ES/strings.po, script.embuary.helper/resources/lib/helper.py, script.embuary.helper/resources/lib/image.py, script.embuary.helper/resources/lib/json_map.py, script.embuary.helper/resources/lib/library.py, script.embuary.helper/resources/lib/plugin_content.py, script.embuary.helper/resources/lib/service_monitor.py
- **General**
- Version number: 2.0.3
=> [script.embuary.helper@matrix] 2.0.3

script.artistslideshow/README.md, script.artistslideshow/addon.xml, script.artistslideshow/default.py, script.artistslideshow/resources/lib/artistslideshow.py, script.artistslideshow/resources/lib/xlogger.py
Changes in logging to accommodate new logging requirements in Kodi 19. (just as an FYI, I won't be submitting this as an update for Kodi 18. Next time I do an update the code will come back into sync for both versions).
- This add-on repository has automated code guideline check which could help you improve your coding. …
=> [script.artistslideshow] 3.2.103

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/library.py
- **General**
- Version number: 1.4.7
=> [script.embuary.helper@leia] 1.4.7

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/helper.py, script.embuary.helper/resources/lib/library.py
- **General**
- Version number: 2.0.4
=> [script.embuary.helper@matrix] 2.0.4

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/player_monitor.py, script.embuary.helper/resources/lib/service_monitor.py
- **General**
- Version number: 2.0.5
=> [script.embuary.helper@matrix] 2.0.5

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/service_monitor.py
- **General**
- Version number: 1.4.8
=> [script.embuary.helper@leia] 1.4.8

service.subtitles.legendasdivx/addon.xml, service.subtitles.legendasdivx/changelog.txt, service.subtitles.legendasdivx/service.py
Login before search required.
Added origin\type of subtitle to the list. …
=> [service.subtitles.legendasdivx] v0.4.0

script.module.blinker/addon.xml
=> [script.module.blinker] 1.4.0+matrix.2

script.module.iso8601/addon.xml
=> [script.module.iso8601] 0.1.12+matrix.2

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py, script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py, script.module.inputstreamhelper/lib/inputstreamhelper/unicodes.py, script.module.inputstreamhelper/lib/inputstreamhelper/utils.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py, script.module.inputstreamhelper/resources/language/resource.language.de_de/strings.po, script.module.inputstreamhelper/resources/language/resource.language.el_gr/strings.po, script.module.inputstreamhelper/resources/language/resource.language.en_gb/strings.po, script.module.inputstreamhelper/resources/language/resource.language.es_es/strings.po, script.module.inputstreamhelper/resources/language/resource.language.fr_fr/strings.po, script.module.inputstreamhelper/resources/language/resource.language.hr_hr/strings.po, script.module.inputstreamhelper/resources/language/resource.language.hu_hu/strings.po, script.module.inputstreamhelper/resources/language/resource.language.it_it/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ja_JP/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ko_KR/strings.po, script.module.inputstreamhelper/resources/language/resource.language.nl_nl/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ro_ro/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ru_ru/strings.po, script.module.inputstreamhelper/resources/language/resource.language.sv_se/strings.po
- **General**
- Version number: 0.4.7+matrix.1
v0.4.7 (2020-05-03)
- Fix hardlink on Windows
- Fix support for unicode chars in paths
- Show remaining time during Widevine installation on ARM devices
=> [script.module.inputstreamhelper@matrix] 0.4.7+matrix.1

script.embuary.info/addon.xml, script.embuary.info/resources/language/resource.language.es_ES/strings.po, script.embuary.info/resources/lib/helper.py
- **General**
- Version number: 2.0.2
=> [script.embuary.info@matrix] 2.0.2

service.librarywatchdog/addon.xml, service.librarywatchdog/core/emitters.py, service.librarywatchdog/core/main.py, service.librarywatchdog/core/polling.py, service.librarywatchdog/core/polling_local.py, service.librarywatchdog/core/polling_xbmc.py, service.librarywatchdog/core/settings.py, service.librarywatchdog/core/utils.py
=> [service.librarywatchdog] 1.1.0+matrix.1

service.librarywatchdog/addon.xml, service.librarywatchdog/core/main.py
=> [service.librarywatchdog] 1.1.1+matrix.1

script.logviewer/addon.xml, script.logviewer/resources/language/English/strings.po, script.logviewer/resources/language/Portuguese (Brazil)/strings.po, script.logviewer/resources/language/Portuguese/strings.po
- **General**
- Version number: 2.1.3+gotham.1
- URL: https://github.com/i96751414/script.logviewer
- Fix Portuguese translations
=> [script.logviewer@gotham] 2.1.3+gotham.1

script.module.autocompletion/addon.xml, script.module.autocompletion/lib/AutoCompletion.py
- **General**
- Version number: 2.0.1
- URL: https://github.com/sualfred/script.module.autocompletion
=> [script.module.autocompletion@matrix] 2.0.1

script.module.arlo/addon.xml, script.module.arlo/lib/arlo.py
Version upgrade from 1.2.33 to 1.2.35 …
=> [script.module.arlo] 1.2.35 - matrix

script.module.python.twitch/addon.xml, script.module.python.twitch/resources/lib/twitch/api/parameters.py, script.module.python.twitch/resources/lib/twitch/api/v5/streams.py, script.module.python.twitch/resources/lib/twitch/log.py
equivalent: #1548
diff: https://github.com/MrSprigster/script.module.python.twitch/compare/matrix …
=> [script.module.python.twitch] 2.0.14+matrix.1

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/library.py, script.embuary.helper/resources/lib/player_monitor.py
- **General**
- Version number: 2.0.6
=> [script.embuary.helper@matrix] 2.0.6

script.module.python.twitch/addon.xml, script.module.python.twitch/changelog.txt, script.module.python.twitch/resources/lib/twitch/api/parameters.py, script.module.python.twitch/resources/lib/twitch/api/v5/streams.py, script.module.python.twitch/resources/lib/twitch/log.py
=> [script.module.python.twitch] 2.0.14

service.subtitles.traduttorianonimi/addon.xml
Addon removed because the source website is not available anymore.
=> [service.subtitles.traduttorianonimi] 2.3.0

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/resources/lib/version_check/common.py, service.xbmc.versioncheck/resources/lib/version_check/json_interface.py, service.xbmc.versioncheck/resources/versions.txt
equivalent: #1555
matrix diff: https://github.com/XBMC-Addons/service.xbmc.versioncheck/compare/matrix …
=> [service.xbmc.versioncheck] 0.5.5+matrix.1

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/changelog.txt, service.xbmc.versioncheck/resources/lib/version_check/common.py, service.xbmc.versioncheck/resources/lib/version_check/json_interface.py, service.xbmc.versioncheck/resources/versions.txt
equivalent: #1556
matrix diff: https://github.com/XBMC-Addons/service.xbmc.versioncheck/compare/matrix …
=> [service.xbmc.versioncheck] 0.5.5

weather.gismeteo/addon.xml, weather.gismeteo/changelog.txt, weather.gismeteo/default.py, weather.gismeteo/resources/libs/__init__.py
- **General**
- Version number: 0.4.2+matrix.1
v0.4.2 (2020-05-21)
- Fixed identified bugs
=> [weather.gismeteo@matrix] 0.4.2+matrix.1

script.module.arlo/addon.xml, script.module.arlo/lib/arlo.py
Upgrade from v 1.2.33 to 1.2.35
- [ X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- This add-on repository has automated code guideline check which could help you improve your coding. You can find …
=> [script.module.arlo] 1.2.35

weather.gismeteo/addon.xml, weather.gismeteo/changelog.txt, weather.gismeteo/default.py, weather.gismeteo/resources/libs/__init__.py
- **General**
- Version number: 0.4.2
v0.4.2 (2020-05-21)
- Fixed identified bugs
=> [weather.gismeteo@krypton] 0.4.2

script.sublissimo/addon.xml
- New version number for Matrix.  …
=> [script.sublissimo] 1.0.4

script.sublissimo/addon.xml, script.sublissimo/resources/lib/play_along_file.py, script.sublissimo/resources/lib/script.py, script.sublissimo/resources/lib/sync_by_frame_rate.py, script.sublissimo/resources/lib/syncwizard.py
- Small fixes which were needed in the Matrix version, are now changed for Leia as well.  …
=> [script.sublissimo] 0.0.4

weather.multi/README.txt, weather.multi/addon.xml, weather.multi/changelog.txt, weather.multi/lib/providers/yahoo.py
something has changed in the way yahoo provides their weather data (see: https://github.com/xbmc/repo-scripts/pull/1572)
since weather.multi also uses the yahoo api, this addon needs to be updated as well.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find …
=> [weather.multi] 0.0.5

script.logviewer/addon.xml, script.logviewer/resources/lib/logviewer.py, script.logviewer/resources/lib/utils.py
- **General**
- Version number: 2.1.4+matrix.1
- URL: https://github.com/i96751414/script.logviewer
- Updated to support Matrix log format
=> [script.logviewer@matrix] 2.1.4+matrix.1

service.subtitles.subsceneplus/addon.xml, service.subtitles.subsceneplus/resources/language/resource.language.en_gb/strings.po, service.subtitles.subsceneplus/resources/lib/Subscene.py, service.subtitles.subsceneplus/service.py
This pull request updates the Subsceneplus addon.
The updated version contains:
- Support for TV-Series
- Support for user selection where the decisions cannot be made automatically.
- Some bug fixes
=> [service.subtitles.subsceneplus] 1.1.22

service.watchedlist/addon.xml, service.watchedlist/lib/watchedlist/watchedlist.py, service.watchedlist/resources/language/resource.language.de_de/strings.po, service.watchedlist/resources/language/resource.language.en_gb/strings.po, service.watchedlist/resources/language/resource.language.he_il/strings.po
I discovered another bug in my addon related to a change in `DialogProgress.update` introduced in Kodi Matrix
=> [service.watchedlist] 1.3.1

script.module.trakt/addon.xml, script.module.trakt/lib/CHANGES.rst, script.module.trakt/lib/trakt/interfaces/__init__.py, script.module.trakt/lib/trakt/interfaces/lists/__init__.py, script.module.trakt/lib/trakt/interfaces/users/__init__.py, script.module.trakt/lib/trakt/interfaces/users/lists/__init__.py, script.module.trakt/lib/trakt/interfaces/users/profile.py, script.module.trakt/lib/trakt/interfaces/users/watched.py, script.module.trakt/lib/trakt/mapper/core/base.py, script.module.trakt/lib/trakt/mapper/list.py, script.module.trakt/lib/trakt/mapper/sync.py, script.module.trakt/lib/trakt/objects/__init__.py, script.module.trakt/lib/trakt/objects/list/__init__.py, script.module.trakt/lib/trakt/objects/list/base.py, script.module.trakt/lib/trakt/objects/list/custom.py, script.module.trakt/lib/trakt/objects/list/public.py, script.module.trakt/lib/trakt/objects/media.py, script.module.trakt/lib/trakt/objects/user.py, script.module.trakt/lib/trakt/objects/video.py, script.module.trakt/lib/trakt/version.py
- **General**
- Add-on name: trakt.py
- Add-on ID: script.module.trakt
- Version number: 4.2.0+matrix.1
- URL: https://github.com/Razzeee/script.module.trakt
Packed for Kodi from https://github.com/fuzeman/trakt.py
=> [script.module.trakt@matrix] 4.2.0+matrix.1

script.module.trakt/addon.xml, script.module.trakt/lib/CHANGES.rst, script.module.trakt/lib/trakt/interfaces/__init__.py, script.module.trakt/lib/trakt/interfaces/lists/__init__.py, script.module.trakt/lib/trakt/interfaces/users/__init__.py, script.module.trakt/lib/trakt/interfaces/users/lists/__init__.py, script.module.trakt/lib/trakt/interfaces/users/profile.py, script.module.trakt/lib/trakt/interfaces/users/watched.py, script.module.trakt/lib/trakt/mapper/core/base.py, script.module.trakt/lib/trakt/mapper/list.py, script.module.trakt/lib/trakt/mapper/sync.py, script.module.trakt/lib/trakt/objects/__init__.py, script.module.trakt/lib/trakt/objects/list/__init__.py, script.module.trakt/lib/trakt/objects/list/base.py, script.module.trakt/lib/trakt/objects/list/custom.py, script.module.trakt/lib/trakt/objects/list/public.py, script.module.trakt/lib/trakt/objects/media.py, script.module.trakt/lib/trakt/objects/user.py, script.module.trakt/lib/trakt/objects/video.py, script.module.trakt/lib/trakt/version.py
- **General**
- Add-on name: trakt.py
- Add-on ID: script.module.trakt
- Version number: 4.2.0
- URL: https://github.com/Razzeee/script.module.trakt
Packed for Kodi from https://github.com/fuzeman/trakt.py
=> [script.module.trakt@gotham] 4.2.0

script.service.janitor/addon.xml, script.service.janitor/changelog.txt, script.service.janitor/default.py, script.service.janitor/resources/language/resource.language.en_gb/strings.po, script.service.janitor/resources/language/resource.language.fr_fr/strings.po, script.service.janitor/resources/language/resource.language.nl_nl/strings.po, script.service.janitor/resources/language/resource.language.pl_pl/strings.po, script.service.janitor/settings.py, script.service.janitor/utils.py
- [FIX] Improved unicode support
- [FIX] Correctly match excluded paths that contain user credentials …
=> [script.service.janitor] 4.4.1

script.module.t1mlib/addon.xml, script.module.t1mlib/lib/t1mlib.py
=> script.module.t1mlib 4.0.1

context.copytostorage/addon.xml
Fixes https://github.com/xbmc/repo-scripts/issues
=> [context.copytostorage] 1.0.1/broken

script.module.t1mlib/addon.xml, script.module.t1mlib/lib/t1mlib.py
=> script.module.t1mlib 4.0.2

script.skin.info.service/addon.xml, script.skin.info.service/default.py
Change deprecated xbmc.abortRequested …
=> [script.skin.info.service] 1.1.1

script.skinshortcuts/addon.xml, script.skinshortcuts/resources/lib/library.py
=> [script.skinshortcuts] v1.1.2

service.library.data.provider/addon.xml, service.library.data.provider/resources/lib/data.py, service.library.data.provider/resources/lib/library.py
Change deprecated xbmc.abortRequested …
=> [service.library.data.provider] v0.4.1

script.module.t1mlib/addon.xml, script.module.t1mlib/lib/t1mlib.py, script.module.t1mlib/readme.txt
=> matrix script.module.t1mlib 4.0.4

script.module.libzdf/addon.xml, script.module.libzdf/lib/libzdfjsonparser.py
Small update to prevent an exception in case content is removed but still listed.
=> [script.module.libzdf] v5.0.1

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/resources/settings.xml, service.xbmc.versioncheck/resources/versions.txt
- add Kodi 18.8 stable release
- add Kodi 19.0 alpha1 release …
=> [service.xbmc.versioncheck] 0.5.6+matrix.1

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/changelog.txt, service.xbmc.versioncheck/resources/versions.txt
- add Kodi 18.8 stable release
- add Kodi 19.0 alpha1 release …
=> [service.xbmc.versioncheck] 0.5.6

script.module.t1mlib/addon.xml, script.module.t1mlib/lib/t1mlib.py, script.module.t1mlib/readme.txt
=> [script.module.t1mlib] 4.0.6

script.module.autocompletion/addon.xml, script.module.autocompletion/lib/AutoCompletion.py
- **General**
- Version number: 2.0.2
- URL: https://github.com/sualfred/script.module.autocompletion
=> [script.module.autocompletion@matrix] 2.0.2

script.module.codequick/addon.xml, script.module.codequick/lib/codequick/support.py
Fix bug with watched flags not working.
=> [script.module.codequick] 0.9.14

script.skin.info.service/Utils.py, script.skin.info.service/addon.xml
Fix set runtime - thanks scott967 …
=> [script.skin.info.service] 1.1.2

script.module.python.twitch/addon.xml
Just a minor update for forum and source locations …
=> [script.module.python.twitch] v2.0.15+matrix.1

script.module.python.twitch/addon.xml, script.module.python.twitch/changelog.txt
Just a minor update for forum and source locations …
=> [script.module.python.twitch] v2.0.15

script.sublissimo/addon.xml, script.sublissimo/resources/language/resource.language.en_gb/strings.po, script.sublissimo/resources/lib/script.py
- Added mask for .srt and .sub files.
- Added validity check to make sure a subtitle is valid.  …
=> [script.sublissimo] 0.0.5

script.module.dropbox_auth/addon.xml, script.module.dropbox_auth/authenticate.py, script.module.dropbox_auth/resources/utils.py
Updated deprecated log levels as requested in [xbmc PR 18346](https://github.com/xbmc/xbmc/pull/18346).
=> [script.module.dropbox_auth] 8.4.3

service.watchedlist/addon.xml, service.watchedlist/lib/watchedlist/utils.py
Updated deprecated log levels as requested in [xbmc PR 18346](https://github.com/xbmc/xbmc/pull/18346).
=> [service.watchedlist] 1.3.2

script.keymap/addon.xml, script.keymap/resources/lib/editor.py, script.keymap/resources/lib/keymap.py
fixed remaining while loops that were pointed out during Matrix code review …
=> [script.keymap] 1.1.3

script.cu.lrclyrics/README.txt, script.cu.lrclyrics/addon.xml, script.cu.lrclyrics/changelog.txt, script.cu.lrclyrics/lib/culrcscrapers/darklyrics/lyricsScraper.py, script.cu.lrclyrics/lib/culrcscrapers/syair/lyricsScraper.py, script.cu.lrclyrics/lib/embedlrc.py, script.cu.lrclyrics/lib/gui.py, script.cu.lrclyrics/lib/utils.py
- fix broken DarkLyrics scraper
- improved support for embedded lyrics …
=> [script.cu.lrclyrics] 6.2.4

script.module.xbmcswift2/addon.xml, script.module.xbmcswift2/lib/xbmcswift2/logger.py
- **General**
- Version number: 19.0.1
Remove LOGSEVERE and LOGNOTICE log levels to comply to https://github.com/xbmc/xbmc/pull/18346
=> [script.module.xbmcswift2@matrix] 19.0.1

script.skinshortcuts/addon.xml, script.skinshortcuts/resources/lib/xmlfunctions.py
=> [script.skinshortcuts] v1.1.3

context.item.extras/addon.xml
This is a version bump only to make it easier to do maintenance releases on Leia. Matrix on will be 1.4.0+ and Leia will stay at 1.3.x. …
=> context.item.extras] 1.4.0

script.xbmc.lcdproc/addon.xml, script.xbmc.lcdproc/changelog.txt, script.xbmc.lcdproc/resources/lib/common.py, script.xbmc.lcdproc/resources/lib/lcdbase.py, script.xbmc.lcdproc/resources/lib/lcdproc.py
- replace LOGNOTICE with LOGINFO, remove LOGSEVERE
- use translatePath from xbmcvfs instead of xbmc …
=> [script.xbmc.lcdproc] 3.90.1

context.item.extras/addon.py, context.item.extras/addon.xml, context.item.extras/plugin.py
fix for encoding issues on Leia. Note that all Matrix and later versions will be 1.4.x. The Leia branch will have maintenance updates only and remain on 1.3.x …
=> [context.item.extras]1.3.4

script.module.addon.signals/addon.xml, script.module.addon.signals/lib/AddonSignals.py
=> [script.module.addon.signals] 0.0.6+matrix.1

script.module.xbmcswift2/addon.xml, script.module.xbmcswift2/lib/xbmcswift2/__init__.py, script.module.xbmcswift2/lib/xbmcswift2/plugin.py, script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py
- **General**
- Version number: 19.0.2
Move xbmc.translatepath to xbmcvfs.translatepath
=> [script.module.xbmcswift2@matrix] 19.0.2

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/resources/lib/version_check/apt_daemon_handler.py, service.xbmc.versioncheck/resources/lib/version_check/common.py, service.xbmc.versioncheck/resources/lib/version_check/service.py, service.xbmc.versioncheck/resources/versions.txt
=> [service.xbmc.versioncheck] v0.5.7+matrix.1

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/changelog.txt, service.xbmc.versioncheck/resources/lib/version_check/apt_daemon_handler.py, service.xbmc.versioncheck/resources/lib/version_check/common.py, service.xbmc.versioncheck/resources/lib/version_check/service.py, service.xbmc.versioncheck/resources/versions.txt
=> [service.xbmc.versioncheck] v0.5.7

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/resources/lib/version_check/service.py
fixup: https://github.com/xbmc/repo-scripts/pull/1703#issuecomment-704612430 …
=> [service.xbmc.versioncheck] v0.5.8+matrix.1

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/resources/lib/version_check/service.py
fixup: https://github.com/xbmc/repo-scripts/pull/1703#issuecomment-704612430 …
=> [service.xbmc.versioncheck] v0.5.8

script.module.clouddrive.common/addon.xml, script.module.clouddrive.common/clouddrive/common/account.py, script.module.clouddrive.common/clouddrive/common/db.py, script.module.clouddrive.common/clouddrive/common/export.py, script.module.clouddrive.common/clouddrive/common/remote/oauth2.py, script.module.clouddrive.common/clouddrive/common/remote/provider.py, script.module.clouddrive.common/clouddrive/common/remote/request.py, script.module.clouddrive.common/clouddrive/common/service/export.py, script.module.clouddrive.common/clouddrive/common/service/player.py, script.module.clouddrive.common/clouddrive/common/service/source.py, script.module.clouddrive.common/clouddrive/common/ui/addon.py, script.module.clouddrive.common/clouddrive/common/ui/dialog.py, script.module.clouddrive.common/clouddrive/common/ui/utils.py, script.module.clouddrive.common/clouddrive/common/utils.py, script.module.clouddrive.common/resources/language/resource.language.en_gb/strings.po, script.module.clouddrive.common/resources/language/resource.language.he_il/strings.po, script.module.clouddrive.common/resources/language/resource.language.pt_br/strings.po, script.module.clouddrive.common/resources/skins/default/1080i/export-main-dialog.xml
- Fix corruption on configurations
- Fix export …
=> [script.module.clouddrive.common] 1.3.2

script.rss.editor/addon.xml, script.rss.editor/lib/xmlParser.py
not much, just incorporating the xbmcvfs.translatePath() change. …
=> [script.rss.editor] 4.0.2

service.scrobbler.lastfm/addon.xml, service.scrobbler.lastfm/changelog.txt, service.scrobbler.lastfm/lib/utils.py, service.scrobbler.lastfm/resources/settings.xml
bugfix:
- due to a missing setting, the addon would crash on new installs …
=> [service.scrobbler.lastfm] 4.0.3

context.item.extras/addon.xml, context.item.extras/plugin.py
fix for crash with certain use cases …
=> [context.item.extras] 1.4.1

context.item.extras/addon.xml, context.item.extras/plugin.py
fix for crash with certain use cases …
=> [context.items.extras] 1.3.6

weather.gismeteo/addon.xml, weather.gismeteo/changelog.txt, weather.gismeteo/default.py, weather.gismeteo/resources/language/resource.language.en_gb/strings.po, weather.gismeteo/resources/language/resource.language.ru_ru/strings.po, weather.gismeteo/resources/libs/__init__.py, weather.gismeteo/resources/libs/gismeteo.py, weather.gismeteo/resources/libs/simpleplugin.py, weather.gismeteo/resources/libs/simpleweather.py, weather.gismeteo/resources/settings.xml
- **General**
- Version number: 0.5.2
v0.5.2 (2020-10-15)
- Fixed bug with parsing XML data
v0.5.1 (2020-06-01)
- Added the ability to display Gismeteo icons
=> [weather.gismeteo@krypton] 0.5.2

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/resources/lib/version_check/common.py, service.xbmc.versioncheck/resources/versions.txt
- add Kodi 18.9 release
- fixup Kodi 19 pre alpha2 translatePath …
=> [service.xbmc.versioncheck] v0.5.9+matrix.1

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/changelog.txt, service.xbmc.versioncheck/resources/lib/version_check/common.py, service.xbmc.versioncheck/resources/versions.txt
- add Kodi 18.9 release
- fixup Kodi 19 pre alpha2 translatePath …
=> [service.xbmc.versioncheck] v0.5.9

script.skinshortcuts/addon.xml, script.skinshortcuts/resources/lib/datafunctions.py, script.skinshortcuts/resources/lib/gui.py, script.skinshortcuts/resources/lib/library.py, script.skinshortcuts/resources/lib/nodefunctions.py, script.skinshortcuts/resources/lib/skinshortcuts.py, script.skinshortcuts/resources/lib/template.py, script.skinshortcuts/resources/lib/xmlfunctions.py
xbmc.translatePath --> xbmcvfs.translatePath
Fix SyntaxWarning "is not" with a literal in kodi.log …
=> [script.skinshortcuts] v1.1.4

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/resources/versions.txt
=> [service.xbmc.versioncheck] v0.5.10+matrix.1

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/changelog.txt, service.xbmc.versioncheck/resources/versions.txt
=> [service.xbmc.versioncheck] v0.5.10

script.module.adobepass/addon.xml, script.module.adobepass/lib/adobepass/adobe.py
- **General**
- Add-on name: adobepass
- Add-on ID: script.module.adobepass
- Version number: 2020.11.6+matrix.1
- URL: https://github.com/eracknaphobia/script.module.adobepass
Simplify Logins authentication services that use adobe primetime (formely adobe pass)
=> [script.module.adobepass@matrix] 2020.11.6+matrix.1

script.embuary.info/addon.xml, script.embuary.info/resources/lib/tmdb.py
- **General**
- Version number: 2.0.4
=> [script.embuary.info@matrix] 2.0.4

script.module.adobepass/addon.xml, script.module.adobepass/lib/adobepass/adobe.py
- **General**
- Add-on name: adobepass
- Add-on ID: script.module.adobepass
- Version number: 2020.11.6
- URL: https://github.com/eracknaphobia/script.module.adobepass
Simplify Logins authentication services that use adobe primetime (formely adobe pass)
=> [script.module.adobepass@krypton] 2020.11.6

service.subtitles.rvm.addic7ed/addic7ed/core.py, service.subtitles.rvm.addic7ed/addic7ed/exception_logger.py, service.subtitles.rvm.addic7ed/addic7ed/utils.py, service.subtitles.rvm.addic7ed/addon.xml, service.subtitles.rvm.addic7ed/main.py
- **General**
- Version number: 3.1.3+matrix.1
v.3.1.3:
- Internal changes.
=> [service.subtitles.rvm.addic7ed@matrix] 3.1.3+matrix.1

service.subtitles.opensubtitles/addon.xml, service.subtitles.opensubtitles/changelog.txt, service.subtitles.opensubtitles/resources/lib/OSUtilities.py, service.subtitles.opensubtitles/resources/lib/__init__.py, service.subtitles.opensubtitles/service.py
Sending on the behalf of the maintainer (@juokelis)
Fixes were sent upstream (and merged) in https://github.com/juokelis/service.subtitles.opensubtitles/pull/2
=> [service.subtitles.opensubtitles] 5.1.2

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/changelog.txt, service.xbmc.versioncheck/resources/versions.txt
=> [service.xbmc.versioncheck] v0.5.11

script.module.simplecache/README.md, script.module.simplecache/addon.xml, script.module.simplecache/lib/simplecache.py
- **General**
- Add-on name: Simple Cache Module
- Add-on ID: script.module.simplecache
- Version number: 1.0.19
- URL: https://github.com/sualfred/script.module.simplecache
Provides a simple file- and memory based cache for Kodi addons. Based on the original work of Marcelveldt.
=> [script.module.simplecache@leia] 1.0.19

script.module.simplecache/README.md, script.module.simplecache/addon.xml, script.module.simplecache/lib/simplecache.py
- **General**
- Add-on name: Simple Cache Module
- Add-on ID: script.module.simplecache
- Version number: 2.0.2
- URL: https://github.com/sualfred/script.module.simplecache
Provides a simple file- and memory based cache for Kodi addons. Based on the original work of Marcelveldt.
=> [script.module.simplecache@matrix] 2.0.2

script.embuary.info/addon.xml, script.embuary.info/resources/lib/helper.py
- **General**
- Version number: 2.0.5
=> [script.embuary.info@matrix] 2.0.5

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/library.py, script.embuary.helper/resources/lib/plugin_content.py
- **General**
- Version number: 1.4.9
=> [script.embuary.helper@leia] 1.4.9

script.embuary.info/addon.xml, script.embuary.info/resources/lib/helper.py
- **General**
- Version number: 1.2.8
=> [script.embuary.info@leia] 1.2.8

script.trakt/addon.xml, script.trakt/changelog.txt, script.trakt/resources/lib/traktapi.py
=> [script.trakt] 3.2.6

script.module.tubed.api/addon.xml, script.module.tubed.api/resources/lib/src/tubed_api/__init__.py, script.module.tubed.api/resources/lib/src/tubed_api/oauth/client.py, script.module.tubed.api/resources/lib/src/tubed_api/v3/query.py
Quick follow up to allow module users to apply http referer api key restrictions …
=> [script.module.tubed.api] v1.0.1

service.iptv.manager/CHANGELOG.md, service.iptv.manager/addon.xml, service.iptv.manager/resources/lib/modules/iptvsimple.py
- **General**
- Add-on name: IPTV Manager
- Add-on ID: service.iptv.manager
- Version number: 0.2.2+matrix.1
- URL: https://github.com/add-ons/service.iptv.manager
This add-on integrates IPTV Channels from other Add-ons in the Kodi PVR.
v0.2.2 (2020-12-07)
- Relax version restriction for IPTV Simple.
- Process credits.
=> [service.iptv.manager@matrix] 0.2.2+matrix.1

script.module.xbmcswift2/addon.xml, script.module.xbmcswift2/lib/xbmcswift2/listitem.py
- **General**
- Version number: 19.0.4
Add support for offscreen in Listitems
=> [script.module.xbmcswift2@matrix] 19.0.4

script.module.xbmcswift2/addon.xml, script.module.xbmcswift2/lib/xbmcswift2/listitem.py
- **General**
- Version number: 13.0.2
=> [script.module.xbmcswift2@gotham] 13.0.2

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/resources/lib/version_check/service.py, service.xbmc.versioncheck/resources/lib/version_check/viewer.py, service.xbmc.versioncheck/resources/versions.txt
=> [service.xbmc.versioncheck] v0.5.12+matrix.1

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/changelog.txt, service.xbmc.versioncheck/resources/lib/version_check/service.py, service.xbmc.versioncheck/resources/lib/version_check/viewer.py, service.xbmc.versioncheck/resources/versions.txt
Don't merge until beta2 is available from https://kodi.tv/download …
=> [service.xbmc.versioncheck] v0.5.12

script.module.xbmcswift2/addon.xml, script.module.xbmcswift2/changelog.txt, script.module.xbmcswift2/lib/xbmcswift2/listitem.py
- **General**
- Version number: 13.0.3
=> [script.module.xbmcswift2@gotham] 13.0.3

service.subtitles.subdivx/README.md, service.subtitles.subdivx/addon.xml, service.subtitles.subdivx/changelog.txt, service.subtitles.subdivx/resources/language/English/strings.po, service.subtitles.subdivx/resources/language/Spanish (Argentina)/strings.po, service.subtitles.subdivx/service.py
Update add-on to make it work again after subdivx.com switch to HTTPS. Start preparing for Python 3 port.
=> [service.subtitles.subdivx] 0.3.6

script.module.tubed.api/addon.xml, script.module.tubed.api/resources/lib/src/tubed_api/usher/lib/mpeg_dash.py
=> [script.module.tubed.api] v1.0.2

script.transmission/addon.xml, script.transmission/player.py, script.transmission/resources/language/resource.language.ca_es/strings.po, script.transmission/resources/language/resource.language.de_de/strings.po, script.transmission/resources/language/resource.language.en_gb/strings.po, script.transmission/resources/language/resource.language.es_es/strings.po, script.transmission/resources/language/resource.language.hu_hu/strings.po, script.transmission/resources/language/resource.language.ko_kr/strings.po, script.transmission/resources/language/resource.language.nb_no/strings.po, script.transmission/resources/language/resource.language.ru_ru/strings.po, script.transmission/resources/language/resource.language.uk_ua/strings.po, script.transmission/resources/lib/common.py, script.transmission/resources/lib/gui.py, script.transmission/resources/lib/main.py, script.transmission/resources/lib/transmissionrpc/__init__.py, script.transmission/resources/lib/transmissionrpc/client.py, script.transmission/resources/lib/transmissionrpc/constants.py, script.transmission/resources/lib/transmissionrpc/error.py, script.transmission/resources/lib/transmissionrpc/httphandler.py, script.transmission/resources/lib/transmissionrpc/session.py, script.transmission/resources/lib/transmissionrpc/torrent.py, script.transmission/resources/lib/transmissionrpc/utils.py, script.transmission/resources/skins/Default/720p/script-Transmission-main.xml
Version 1.0.2
* Fix torrent progress bar in main screen (thanks @AnonTester)
* Fix error with missing ETA on stalled torrents (thanks @AnonTester)
* Fix KeyError on torrent removal
* Add localization for new strings
=> [script.transmission] 1.0.2

service.subtitles.supersubtitles/addon.xml, service.subtitles.supersubtitles/service.py
- Update python3 exception handling
=> [service.subtitles.supersubtitles@matrix] 0.0.26

script.xbmcbackup/addon.xml, script.xbmcbackup/launcher.py, script.xbmcbackup/resources/language/resource.language.en_gb/strings.po, script.xbmcbackup/resources/lib/advanced_editor.py, script.xbmcbackup/resources/lib/authorizers.py, script.xbmcbackup/resources/lib/backup.py, script.xbmcbackup/resources/lib/guisettings.py, script.xbmcbackup/resources/lib/scheduler.py, script.xbmcbackup/resources/lib/utils.py, script.xbmcbackup/resources/lib/vfs.py, script.xbmcbackup/resources/settings.xml
__Fixes__
* swapped ```xbmc.translatePath``` for ```xbmcvfs.translatePath``` where needed
* fixed calls to ```xbmcgui.Dialog().ok()``` as method now takes 2 args instead of multiple message args
* fixed import of oauth package that prevented Dropbox authorization
__Additions__
Updated how Kodi settings are backed up and restored. Now uses JSON GetSettings to dump all settings on backup and then JSON SetSettingValue to set settings on restore. This can be toggled with new setting in the addon settings. This removes the need to parse the guisettings file manually anymore. 
- [add-on …
=> [script.xbmcbackup] 1.6.4

script.module.kodiswift/addon.xml, script.module.kodiswift/lib/kodiswift/listitem.py
1. enable script.module.kodiswift to support python 2 and python 3 by incorporating the six package.
2. add supports on subtitles.
=> [script.module.kodiswift] 0.0.9

script.module.kodiswift/addon.xml, script.module.kodiswift/changelog.txt, script.module.kodiswift/lib/kodiswift/common.py, script.module.kodiswift/lib/kodiswift/request.py, script.module.kodiswift/lib/kodiswift/urls.py
improves python 2,3 compatibility by replacing original functions with six.moves functions.
=> [script.module.kodiswift] 0.0.11

script.module.soupsieve/addon.xml, script.module.soupsieve/lib/soupsieve/__meta__.py, script.module.soupsieve/lib/soupsieve/css_match.py, script.module.soupsieve/lib/soupsieve/css_parser.py, script.module.soupsieve/lib/soupsieve/css_types.py, script.module.soupsieve/lib/soupsieve/util.py
module updated to latest version …
=> [script.module.soupsieve] 2.1.0+matrix.1

service.master.lock/addon.xml, service.master.lock/resources/language/resource.language.en_gb/strings.po, service.master.lock/resources/lib/lockmonitor.py, service.master.lock/resources/settings.xml
* Added: Option to navigate to the Home screen after locking. …
=> [service.master.lock] v1.0.1+matrix.1

service.master.lock/addon.xml, service.master.lock/resources/language/resource.language.en_gb/strings.po, service.master.lock/resources/lib/lockmonitor.py, service.master.lock/resources/settings.xml
* Added: Option to navigate to the Home screen after locking. …
=> [service.master.lock] v1.0.1

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/resources/versions.txt
Don't merge until rc1 is available from https://kodi.tv/download …
=> [service.xbmc.versioncheck] v0.5.13+matrix.1

screensaver.digitalclock/README.md, screensaver.digitalclock/addon.xml, screensaver.digitalclock/default.py, screensaver.digitalclock/resources/skins/default/720p/skin.ace2.xml, screensaver.digitalclock/resources/skins/default/720p/skin.aeon.tajo.xml, screensaver.digitalclock/resources/skins/default/720p/skin.aeonmq8.xml, screensaver.digitalclock/resources/skins/default/720p/skin.aura.xml, screensaver.digitalclock/resources/skins/default/720p/skin.bello.7.xml, screensaver.digitalclock/resources/skins/default/720p/skin.embuary-leia.xml, screensaver.digitalclock/resources/skins/default/720p/skin.madnox.xml, screensaver.digitalclock/resources/skins/default/720p/skin.quartz.xml
Added support for several skins and fixed a bug …
=> [screensaver.digitalclock] 6.0.1

screensaver.digitalclock/README.md, screensaver.digitalclock/addon.xml, screensaver.digitalclock/default.py, screensaver.digitalclock/resources/skins/default/720p/skin.ace2.xml, screensaver.digitalclock/resources/skins/default/720p/skin.aeon.tajo.xml, screensaver.digitalclock/resources/skins/default/720p/skin.aeonmq8.xml, screensaver.digitalclock/resources/skins/default/720p/skin.aura.xml, screensaver.digitalclock/resources/skins/default/720p/skin.bello.7.xml, screensaver.digitalclock/resources/skins/default/720p/skin.embuary-leia.xml, screensaver.digitalclock/resources/skins/default/720p/skin.madnox.xml, screensaver.digitalclock/resources/skins/default/720p/skin.quartz.xml
Added support for several skins and fixed a bug …
=> [screensaver.digitalclock] 5.1.1

script.sublissimo/addon.xml, script.sublissimo/resources/language/resource.language.en_gb/strings.po, script.sublissimo/resources/lib/script.py, script.sublissimo/resources/lib/sync_by_frame_rate.py, script.sublissimo/resources/lib/syncwizard.py
=> [script.sublissimo@matrix] 1.0.6

script.sublissimo/addon.xml, script.sublissimo/resources/lib/script.py, script.sublissimo/resources/lib/sync_by_frame_rate.py, script.sublissimo/resources/lib/syncwizard.py
=> [script.sublissimo] 0.0.6

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/changelog.txt, service.xbmc.versioncheck/resources/lib/version_check/viewer.py, service.xbmc.versioncheck/resources/versions.txt
=> [service.xbmc.versioncheck] v0.5.13

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/plugin_content.py
- **General**
- Version number: 1.5.0
=> [script.embuary.helper@leia] 1.5.0

script.embuary.info/addon.xml, script.embuary.info/resources/lib/tmdb.py
- **General**
- Version number: 2.0.6
=> [script.embuary.info@matrix] 2.0.6

script.embuary.info/addon.xml, script.embuary.info/resources/lib/tmdb.py
- **General**
- Version number: 1.2.9
=> [script.embuary.info@leia] 1.2.9

script.cu.lrclyrics/addon.xml, script.cu.lrclyrics/changelog.txt, script.cu.lrclyrics/lib/culrcscrapers/azlyrics/lyricsScraper.py, script.cu.lrclyrics/lib/culrcscrapers/genius/lyricsScraper.py, script.cu.lrclyrics/lib/culrcscrapers/minilyrics/lyricsScraper.py, script.cu.lrclyrics/lib/culrcscrapers/syair/lyricsScraper.py, script.cu.lrclyrics/lib/gui.py, script.cu.lrclyrics/lib/utils.py, script.cu.lrclyrics/resources/language/resource.language.en_GB/strings.po, script.cu.lrclyrics/resources/settings.xml, script.cu.lrclyrics/resources/skins/Default/1080i/script-cu-lrclyrics-main.xml
fix compatibility with python 3.9 and some other improvements... …
=> [script.cu.lrclyrics] 6.3.7

script.module.dropbox_auth/addon.xml, script.module.dropbox_auth/authenticate.py
Please merge this minor fix regarding interface change in Kodi Matrix for xbmcgui.Dialog.ok
=> [script.module.dropbox_auth] 8.4.4

script.embuary.info/addon.xml, script.embuary.info/resources/lib/nextaired.py
- **General**
- Version number: 1.3.0
=> [script.embuary.info@leia] 1.3.0

script.embuary.info/addon.xml, script.embuary.info/resources/lib/nextaired.py
- **General**
- Version number: 2.0.7
=> [script.embuary.info@matrix] 2.0.7

service.subtitles.subdivx/addon.xml, service.subtitles.subdivx/changelog.txt, service.subtitles.subdivx/service.py
Fix search results parsing bug.
=> [service.subtitles.subdivx] 0.3.7

script.module.libzdf/addon.xml, script.module.libzdf/lib/libzdf.py, script.module.libzdf/lib/libzdfjsonparser.py, script.module.libzdf/lib/libzdfjsonparser2.py
Maintenance release. Some API endpoints changed.
=> [script.module.libzdf] v5.0.2

script.plex/addon.xml, script.plex/changelog.txt, script.plex/lib/_included_packages/plexnet/video.py
Fix for error causing playback failure …
=> [script.plex] 0.3.3

script.plex/addon.xml, script.plex/changelog.txt, script.plex/lib/_included_packages/plexnet/video.py
Fix for error causing playback failure …
=> [script.plex] 0.2.3

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/changelog.txt, service.xbmc.versioncheck/resources/versions.txt
=> [service.xbmc.versioncheck] v0.5.14

script.module.phate89/addon.xml, script.module.phate89/changelog.txt, script.module.phate89/lib/phate89lib/kodiutils.py, script.module.phate89/lib/phate89lib/rutils.py, script.module.phate89/lib/phate89lib/staticutils.py
- **General**
- Add-on name: phate89 helper module
- Add-on ID: script.module.phate89
- Version number: 1.2.1
- Kodi/repository version: jarvis
- URL: https://github.com/phate89/script.module.phate89
Helper module for addons
=> [script.module.phate89@jarvis] 1.2.1

script.adzapper/addon.xml, script.adzapper/changelog.txt, script.adzapper/resources/language/resource.language.en_gb/strings.po, script.adzapper/resources/language/resource.language.pl_pl/strings.po, script.adzapper/resources/settings.xml
v1.0.2 (2021-02-22)
- Added feature to open keymap editor from within addon settings
- Added polish translation, thx to Atamans
- [X ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [X ] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0
- …
=> [script.adzapper] 1.0.2

script.module.t1mlib/addon.xml, script.module.t1mlib/lib/t1mlib.py, script.module.t1mlib/readme.txt
=> [script.module.t1mlib] 4.0.7

script.cu.lrclyrics/addon.xml, script.cu.lrclyrics/changelog.txt, script.cu.lrclyrics/lib/embedlrc.py, script.cu.lrclyrics/lib/gui.py, script.cu.lrclyrics/resources/language/resource.language.ja_JP/strings.po
this fixes support for embedded lyrics. …
=> [script.cu.lrclyrics] 6.3.9

script.radioparadise/CHANGELOG.md, script.radioparadise/addon.xml, script.radioparadise/service.py
Added automatic stream restart in case of playback issues. …
=> [script.radioparadise] 1.0.1

service.subtitles.napisy24pl/addon.xml, service.subtitles.napisy24pl/resources/lib/NapisyUtils.py
Fix for extraction of zip files on Windows
=> [service.subtitles.napisy24pl] 3.0.4

script.module.codequick/addon.xml, script.module.codequick/lib/codequick/route.py, script.module.codequick/lib/urlquick.py
=> [script.module.codequick] 1.0.2+matrix.1

script.module.codequick/addon.xml, script.module.codequick/lib/codequick/route.py, script.module.codequick/lib/urlquick.py
=> [script.module.codequick] 1.0.2

script.module.xbmcswift2/addon.xml, script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py
- **General**
- Version number: 19.0.5
Fix error in loop
=> [script.module.xbmcswift2@matrix] 19.0.5

weather.yahoo/addon.xml, weather.yahoo/changelog.txt, weather.yahoo/default.py
the addon no longer works due to changes at yahoo's end.
marking it as broken. …
=> [weather.yahoo] 5.1.0

script.xbmcbackup/addon.xml, script.xbmcbackup/resources/language/resource.language.en_gb/strings.po, script.xbmcbackup/resources/lib/advanced_editor.py, script.xbmcbackup/resources/lib/backup.py, script.xbmcbackup/resources/lib/vfs.py, script.xbmcbackup/resources/settings.xml
Added
- added Expert setting to change location of zip file temp location as it's being built or extracted
Changed
- updated ```settings.xml``` to match new [Kodi settings syntax](https://kodi.wiki/view/Add-on_settings_conversion), including visibility levels
Fixed
- when restoring from a zip file the command to delete the extracted directory was incorrect
- ```Dialog().yesno()``` no longer takes line1 arg, changed to message
- …
=> [script.xbmcbackup] 1.6.5

script.module.youtube.dl/addon.xml, script.module.youtube.dl/changelog.txt, script.module.youtube.dl/lib/YDStreamExtractor.py, script.module.youtube.dl/lib/YDStreamUtils.py, script.module.youtube.dl/lib/YoutubeDLWrapper.py, script.module.youtube.dl/lib/main.py, script.module.youtube.dl/lib/yd_private_libs/servicecontrol.py, script.module.youtube.dl/lib/yd_private_libs/updater.py, script.module.youtube.dl/lib/yd_private_libs/util.py, script.module.youtube.dl/lib/youtube_dl/extractor/bbc.py, script.module.youtube.dl/lib/youtube_dl/extractor/ninecninemedia.py, script.module.youtube.dl/lib/youtube_dl/extractor/rds.py, script.module.youtube.dl/lib/youtube_dl/extractor/youtube.py, script.module.youtube.dl/lib/youtube_dl/version.py, script.module.youtube.dl/service.py
Same changelog and codebase than https://github.com/xbmc/repo-scripts/pull/1910 …
=> [script.module.youtube.dl@matrix] 21.303.0+matrix.1

script.trakt/addon.xml, script.trakt/resources/lib/kodiUtilities.py, script.trakt/resources/lib/rating.py, script.trakt/resources/lib/scrobbler.py, script.trakt/resources/lib/service.py, script.trakt/resources/lib/sqlitequeue.py, script.trakt/resources/lib/syncEpisodes.py, script.trakt/resources/lib/utilities.py
- **General**
- Version number: 3.4.0 …
=> [script.trakt@matrix] 3.4.0

script.module.youtube.dl/addon.xml, script.module.youtube.dl/changelog.txt, script.module.youtube.dl/lib/YDStreamExtractor.py, script.module.youtube.dl/lib/YDStreamUtils.py, script.module.youtube.dl/lib/YoutubeDLWrapper.py, script.module.youtube.dl/lib/main.py, script.module.youtube.dl/lib/yd_private_libs/servicecontrol.py, script.module.youtube.dl/lib/youtube_dl/extractor/bbc.py, script.module.youtube.dl/lib/youtube_dl/extractor/ninecninemedia.py, script.module.youtube.dl/lib/youtube_dl/extractor/rds.py, script.module.youtube.dl/lib/youtube_dl/extractor/youtube.py, script.module.youtube.dl/lib/youtube_dl/version.py, script.module.youtube.dl/service.py
Updated youtube-dl core to 2021.03.03
Add merge capability (thanks jmzambon) …
=> [script.module.youtube.dl@leia] 21.303.0

.github/workflows/addon-checker.yml
Adds addon-checker via github actions
=> [repo-scripts][matrix] Enable addon-checker via github actions

.github/workflows/addon-checker.yml
Add addon-checker via github actions
=> [repo-scripts][leia] Add addon-checker via github actions

.github/workflows/addon-checker.yml
Adds addon-checker via github actions
=> [repo-scripts][krypton] Add addon-checker via github actions

.github/workflows/addon-checker.yml
Adds addon-checker via github actions
=> [repo-scripts][jarvis] Add addon-checker via github actions

.github/workflows/addon-checker.yml
Add addon-checker via github actions
=> [repo-scripts][isengard] Add addon-checker via github actions

.github/workflows/addon-checker.yml
Adds addon-checker via github actions
=> [repo-scripts][helix] Add addon-checker via github actions

.github/workflows/addon-checker.yml
Add addon-checker via github actions
=> [repo-scripts][gotham] Add addon-checker via github actions

script.module.soupsieve/addon.xml
Fixes https://github.com/xbmc/repo-scripts/issues/1943 https://github.com/xbmc/xbmc/issues/19455
=> [script.module.soupsieve] 1.9.6+leia.1

script.artistslideshow/addon.xml, script.artistslideshow/changelog.txt, script.artistslideshow/resources/language/resource.language.sr_rs@latin/strings.po, script.artistslideshow/resources/lib/xlogger.py
- fix for Python3 logging issue
- new translations …
=> [script.artistslideshow] v3.3.1

script.module.trakt/addon.xml, script.module.trakt/lib/CHANGES.rst, script.module.trakt/lib/trakt/core/helpers.py, script.module.trakt/lib/trakt/interfaces/movies/__init__.py, script.module.trakt/lib/trakt/interfaces/shows/__init__.py, script.module.trakt/lib/trakt/objects/movie.py, script.module.trakt/lib/trakt/objects/show.py, script.module.trakt/lib/trakt/version.py
- **General**
- Add-on name: trakt.py
- Add-on ID: script.module.trakt
- Version number: 4.4.0+matrix.1
- URL: https://github.com/Razzeee/script.module.trakt
Packed for Kodi from https://github.com/fuzeman/trakt.py
=> [script.module.trakt@matrix] 4.4.0+matrix.1

script.module.autocompletion/addon.xml, script.module.autocompletion/lib/AutoCompletion.py
- **General**
- Version number: 2.0.3
- URL: https://github.com/sualfred/script.module.autocompletion
=> [script.module.autocompletion@matrix] 2.0.3

script.module.arrow/addon.xml
- **General**
- Add-on name: arrow
- Add-on ID: script.module.arrow
- Version number: 1.0.3.1
- URL: https://github.com/Razzeee/script.module.arrow
Packed for Kodi from https://github.com/crsmithdev/arrow
=> [script.module.arrow@matrix] 1.0.3.1

script.harmony.control/addon.xml, script.harmony.control/changelog.txt, script.harmony.control/resources/lib/api/harmony.py
- fix for logging error
(also started using Visual Studio Code, so some reformatting - I suspect that's gonna happen for awhile)
=> [script.harmony.control] 0.2.2+matrix.1

script.speedfaninfo/addon.xml, script.speedfaninfo/changelog.txt, script.speedfaninfo/default.py, script.speedfaninfo/resources/lib/kodisettings.py, script.speedfaninfo/resources/lib/spid.py, script.speedfaninfo/resources/lib/spidsettings.py, script.speedfaninfo/resources/lib/xlogger.py
- fix for incorrect logging levels that somehow crept into the code
- updated to use xbmcvfs.translatePath for forward compatibility
- formatting updates (from using VS Code and pylint)
=> [script.speedfaninfo] 1.2.1+matrix.1

script.harmony.control/addon.xml, script.harmony.control/changelog.txt, script.harmony.control/resources/lib/api/harmony.py
- fix for logging error
(also started using Visual Code Studio, so some formatting changes - I suspect that is going to happen for awhile)
=> [script.harmony.control] 0.2.2

script.harmony.control/addon.xml, script.harmony.control/changelog.txt, script.harmony.control/default.py, script.harmony.control/resources/lib/api/harmony.py, script.harmony.control/resources/lib/fileops.py, script.harmony.control/resources/lib/harmonycontrol.py, script.harmony.control/resources/lib/hcdialog.py, script.harmony.control/resources/lib/hcsettings.py, script.harmony.control/resources/lib/kodisettings.py, script.harmony.control/resources/lib/xlogger.py
v.0.2.3
- fix for crash when running activity
- formatting changes from switch to Visual Code Studio
=> [script.harmonycontrol] 0.2.3+matrix.1

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/cinema_mode.py, script.embuary.helper/resources/lib/helper.py, script.embuary.helper/resources/lib/image.py, script.embuary.helper/resources/lib/library.py, script.embuary.helper/resources/lib/plugin_content.py, script.embuary.helper/resources/lib/plugin_listing.py, script.embuary.helper/resources/lib/service_monitor.py, script.embuary.helper/resources/lib/utils.py
- **General**
- Version number: 2.0.7
=> [script.embuary.helper@matrix] 2.0.7

script.harmony.control/addon.xml, script.harmony.control/changelog.txt, script.harmony.control/default.py, script.harmony.control/resources/lib/api/harmony.py, script.harmony.control/resources/lib/api/url.py, script.harmony.control/resources/lib/fileops.py, script.harmony.control/resources/lib/harmonycontrol.py, script.harmony.control/resources/lib/hcdialog.py, script.harmony.control/resources/lib/hcsettings.py, script.harmony.control/resources/lib/kodisettings.py, script.harmony.control/resources/lib/xlogger.py
v.0.2.3
- fix for crash when running activity
- formatting changes from switch to Visual Code Studio
=> [script.harmonycontrol] 0.2.3

script.embuary.helper/addon.xml, script.embuary.helper/resources/lib/service_monitor.py
- **General**
- Version number: 2.0.8
=> [script.embuary.helper@matrix] 2.0.8

script.embuary.info/addon.xml, script.embuary.info/resources/lib/helper.py, script.embuary.info/resources/lib/season.py, script.embuary.info/resources/lib/tmdb.py
- **General**
- Version number: 2.0.8
=> [script.embuary.info@matrix] 2.0.8

script.embuary.info/addon.xml, script.embuary.info/resources/lib/helper.py, script.embuary.info/resources/lib/season.py, script.embuary.info/resources/lib/tmdb.py
- **General**
- Version number: 1.3.1
=> [script.embuary.info@leia] 1.3.1

service.subtitles.subsceneplus/addon.xml, service.subtitles.subsceneplus/resources/language/resource.language.en_gb/strings.po, service.subtitles.subsceneplus/resources/lib/Subscene.py, service.subtitles.subsceneplus/resources/settings.xml, service.subtitles.subsceneplus/service.py
Moved base domain name into settings so users can download subtitles from mirror sites. such as "subscene.icu"
=> [service.subtitles.subsceneplus] 1.2.9

script.skinshortcuts/addon.xml, script.skinshortcuts/resources/language/resource.language.en_gb/strings.po, script.skinshortcuts/resources/language/resource.language.es_es/strings.po, script.skinshortcuts/resources/lib/library.py, script.skinshortcuts/resources/lib/xmlfunctions.py
=> [script.skinshortcuts] v1.1.5

script.sublissimo/addon.xml, script.sublissimo/main.py, script.sublissimo/resources/language/resource.language.en_gb/strings.po, script.sublissimo/resources/lib/script.py
- Minor Bugfixes
- Load subtitle from the playing video.
- Option added to reset html color-codes in subtitles.  …
=> [script.sublissimo] 0.0.7

script.sublissimo/addon.xml, script.sublissimo/main.py, script.sublissimo/resources/language/resource.language.en_gb/strings.po, script.sublissimo/resources/lib/script.py
- Minor bugfixes
- Load subtitle from the playing video.
- Option added to reset html color-codes in subtitles. …
=> [script.sublissimo] 1.0.7

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/resources/lib/version_check/service.py
=> [service.xbmc.versioncheck] v0.5.16+matrix.1

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/resources/language/resource.language.oc_fr/strings.po, service.xbmc.versioncheck/resources/versions.txt
=> [service.xbmc.versioncheck] v0.5.19+matrix.1

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/changelog.txt, service.xbmc.versioncheck/resources/language/resource.language.oc_fr/strings.po, service.xbmc.versioncheck/resources/versions.txt
=> [service.xbmc.versioncheck] v0.5.19

script.radioparadise/CHANGELOG.md, script.radioparadise/addon.xml, script.radioparadise/radioparadise.py, script.radioparadise/service.py
- Handle missing stream metadata …
=> [script.radioparadise] 1.0.2

script.kodi.loguploader/addon.xml, script.kodi.loguploader/changelog.txt, script.kodi.loguploader/lib/loguploader.py, script.kodi.loguploader/resources/settings.xml
make sure the addon also runs correctly on kodi 20 …
=> [script.kodi.loguploader] 1.0.4

script.openweathermap.maps/addon.xml, script.openweathermap.maps/changelog.txt, script.openweathermap.maps/lib/maps.py
=> [script.openweathermap.maps] 1.0.6

screensaver.picture.slideshow/addon.xml, screensaver.picture.slideshow/changelog.txt, screensaver.picture.slideshow/lib/gui.py, screensaver.picture.slideshow/lib/utils.py, screensaver.picture.slideshow/resources/settings.xml
=> [screensaver.picture.slideshow] 6.3.3

script.module.python.twitch/addon.xml, script.module.python.twitch/changelog.txt, script.module.python.twitch/resources/lib/twitch/api/usher.py, script.module.python.twitch/resources/lib/twitch/parser.py
=> [script.module.python.twitch] v2.0.17

script.module.python.twitch/addon.xml, script.module.python.twitch/changelog.txt, script.module.python.twitch/resources/lib/twitch/api/v5/streams.py
- **General**
- Add-on name: python-twitch for Kodi
- Add-on ID: script.module.python.twitch
- Version number: 2.0.18+matrix.1
- URL: https://github.com/anxdpanic/script.module.python.twitch
python-twitch for Kodi is module for interaction with the Twitch.tv API based on python-twitch by ingwinlu.
[fix] fix v5.streams.by_id request - apo86
=> [script.module.python.twitch@matrix] 2.0.18+matrix.1

script.module.arlo/addon.xml, script.module.arlo/lib/arlo.py, script.module.arlo/lib/eventstream.py, script.module.arlo/lib/request.py
Updated to v1.2.50 of the arlo module (needed for plugin.video.arloview)
- [ x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [ x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide …
=> [script.module.arlo] 1.2.50

weather.ozweather/addon.xml, weather.ozweather/changelog.txt, weather.ozweather/resources/lib/bom/bom_forecast.py
- **General**
- Version number: 2.0.2
v2.0.2
- Minor bugfixes and improvements
=> [weather.ozweather@matrix] 2.0.2

script.module.sseclient/addon.xml, script.module.sseclient/lib/sseclient.py
=> [script.module.sseclient] 0.0.27

script.module.simpleplugin3/addon.xml, script.module.simpleplugin3/changelog.txt, script.module.simpleplugin3/libs/simpleplugin.py, script.module.simpleplugin3/license.txt
- **General**
- Add-on name: SimplePlugin 3
- Add-on ID: script.module.simpleplugin3
- Version number: 3.0.5
- URL: https://github.com/romanvm/script.module.simpleplugin
SimplePlugin micro-framework that simplifies Kodi content plugin programming.
=> [script.module.simpleplugin3@krypton] 3.0.5

script.module.simpleplugin3/addon.xml, script.module.simpleplugin3/changelog.txt, script.module.simpleplugin3/libs/simpleplugin.py, script.module.simpleplugin3/license.txt
- **General**
- Add-on name: SimplePlugin 3
- Add-on ID: script.module.simpleplugin3
- Version number: 3.0.5+matrix.1
- URL: https://github.com/romanvm/script.module.simpleplugin
SimplePlugin micro-framework that simplifies Kodi content plugin programming.
=> [script.module.simpleplugin3@matrix] 3.0.5+matrix.1

targets.cfg
i guess now is as good a time as any, so let's create an addon repo for Kodi Nexus.
i've already created a nexus brach in repo-skins, hopefully our other repo maintainers can take care of the repo(s) they maintain.
- This add-on repository has automated code guideline check which could help you improve your coding. You …
=> add nexus repo

script.sublissimo/addon.xml, script.sublissimo/resources/language/resource.language.en_gb/strings.po, script.sublissimo/resources/lib/script.py, script.sublissimo/resources/lib/subtitle.py
- Minor bugfixes. 
- Fixed some issues with the language file
- Added a fix for .srt-files with encoding issues.  …
=> [script.sublissimo] 1.0.8

script.sublissimo/addon.xml, script.sublissimo/resources/language/resource.language.en_gb/strings.po, script.sublissimo/resources/lib/script.py, script.sublissimo/resources/lib/subtitle.py
- Minor bugfixes.
- Fixed some issues with the language file
-  Added a fix for .srt files with encoding issues. …
=> [script.sublissimo] 0.0.8

script.module.pyqrcode/LICENSE.md, script.module.pyqrcode/addon.xml, script.module.pyqrcode/lib/pyqrcode/__init__.py
fix a possible crash of the kodi logfile uploader on certain systems.
this module is equal to upstream version + PR https://github.com/mnooner256/pyqrcode/pull/51
(the module has been unmaintained for years, so the PR will likely never get merged)
also fixed the license and set the provider-name to the original author.
- …
=> Script.module.pyqrcode 1.2.1+matrix.3

script.service.next-episode/addon.xml, script.service.next-episode/libs/medialibrary.py, script.service.next-episode/libs/nextepisode.py, script.service.next-episode/libs/utils.py
- **General**
- Version number: 1.2.5+matrix.1
1.2.5:
- Fixed crashes when movies do not have IMDB ID.
1.2.4:
=> [script.service.next-episode@matrix] 1.2.5+matrix.1

script.plex/addon.xml, script.plex/lib/_included_packages/plexnet/http.py, script.plex/lib/_included_packages/plexnet/nowplayingmanager.py, script.plex/lib/player.py, script.plex/lib/util.py
Fixes some errors, but mainly fixes an issue with slow/broken playback start :smile:. …
=> [script.plex] 0.3.4

weather.noaa/addon.xml, weather.noaa/changelog.txt, weather.noaa/default.py, weather.noaa/resources/lib/utils.py, weather.noaa/resources/settings.xml
- handle error in temp conversion function when we did not receive a valid temperature from the api
- switch alerts api to use grid location instead of picking zone or county
- pass in "international" units request to api for hourly and daily forcasts if user selected Celcius as their temp unit of choice
- option to pull radar loop (animated gif) instead of static image
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle …
=> [weather.noaa] 2.0.6

script.simkl/addon.xml, script.simkl/resources/lib/engine.py
Added support for third-parties addons …
=> [script.simkl] 3.1.0

script.sublissimo/addon.xml, script.sublissimo/resources/language/resource.language.ko_kr/strings.po
=> [script.sublissimo] 1.1.0

script.sublissimo/addon.xml, script.sublissimo/resources/language/resource.language.ko_kr/strings.po
=> [script.sublissimo] 0.1.0

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py, script.module.inputstreamhelper/lib/inputstreamhelper/config.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py, script.module.inputstreamhelper/resources/language/resource.language.en_gb/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ja_jp/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ko_kr/strings.po
- **General**
- Version number: 0.5.8+matrix.1
v0.5.8 (2021-09-09)
- Simplify Widevine CDM installation on ARM hardware
- Update Japanese and Korean translations
v0.5.7 (2021-07-02)
- Further improve Widevine CDM installation on ARM hardware
v0.5.6 (2021-06-24) …
=> [script.module.inputstreamhelper@matrix] 0.5.8+matrix.1

weather.gismeteo/addon.xml, weather.gismeteo/changelog.txt, weather.gismeteo/resources/libs/gismeteo.py
- **General**
- Version number: 0.6.3+matrix.1
v0.6.3 (2021-09-27)
- Fixed identified bugs
=> [weather.gismeteo@matrix] 0.6.3+matrix.1

weather.gismeteo/addon.xml, weather.gismeteo/changelog.txt, weather.gismeteo/resources/libs/gismeteo.py
- **General**
- Version number: 0.6.3
v0.6.3 (2021-09-27)
- Fixed identified bugs
=> [weather.gismeteo@krypton] 0.6.3

script.module.xbmcswift2/addon.xml, script.module.xbmcswift2/lib/xbmcswift2/plugin.py
Version 19.0.6 (3/10/2021)
-------------
- Add plugin.container_refresh (builtin Container.Refresh)
=> [script.module.xbmcswift2] 19.0.6

script.module.xbmcswift2/addon.xml, script.module.xbmcswift2/changelog.txt, script.module.xbmcswift2/lib/xbmcswift2/plugin.py
Version 13.0.4 (3/10/2021)
-------------
- Add plugin.container_refresh (builtin Container.Refresh)
=> [script.module.xbmcswift2] 13.0.4@gotham

service.watchedlist/addon.xml, service.watchedlist/changelog.txt, service.watchedlist/lib/watchedlist/watchedlist.py
=> [service.watchedlist] 1.3.4

weather.ozweather/addon.xml
=> [weather.ozweather] 1.0.3

weather.ozweather/addon.xml
As requested in https://github.com/xbmc/repo-scripts/issues/2156
Not sure if we want to do this for eden, but shouldn't matter much.
=> [weather.ozweather] 0.4.9

service.librarywatchdog/addon.xml, service.librarywatchdog/core/utils.py
Support the use json.loads both before Python 3.9 and afterwards.
- This add-on repository has automated code guideline check which could help you …
=> [service.librarywatchdog] 1.1.2

script.module.tzlocal/addon.xml
fixes the issues introduced by https://github.com/xbmc/repo-scripts/pull/2122 …
=> [script.module.tzlocal] 3.0.0+matrix.2

service.autostop/README.md, service.autostop/addon.xml, service.autostop/changelog.txt, service.autostop/common.py, service.autostop/resources/language/resource.language.en_gb/strings.po, service.autostop/resources/settings.xml, service.autostop/service.py, service.autostop/utilities.py
Updated Kodi Matrix addon service.autostop v1.0.3.
This update has the following feature enhancements and fixes:
• Extended sleep timer settings to 180 minutes
• Added pause sleep timer adjust option to select what
to do with the sleep timer when playback is paused.
None - Do nothing and sleep counter continues
Pause - Pause sleep timer
Reset - Reset sleep timer to beginning
• Added 0 -180 secs adjustable GUI sleep timer notification
feature with fixed and adjustable sleep timer extension.
• Added event logging option to aid troubleshooting
• Fixed exception bug when Kodi begins but is unable to play a file properly. Autostop will now ignore those playback errors.
-  [X ] My code follows the add-on rules and piracy stance of this project.
-  [X ] I have read the CONTRIBUTING document
- …
=> service.autostop] 1.0.3

service.subtitles.opensubtitles/LICENSE.txt, service.subtitles.opensubtitles/addon.xml, service.subtitles.opensubtitles/changelog.txt, service.subtitles.opensubtitles/resources/language/resource.language.fr_FR/strings.po, service.subtitles.opensubtitles/resources/lib/OSUtilities.py
service.subtitles.opensubtitles v5.1.4
- Adding french translation by [broadcastyourseb](https://github.com/broadcastyourseb)
- Adding license file …
=> [service.subtitles.opensubtitles] 5.1.4

script.reset_watchedstate/addon.xml, script.reset_watchedstate/lib/reset_watchedstate.py, script.reset_watchedstate/resources/settings.xml
Add-on update:
* Fix python error to detect builds named `20.0-ALPHA1`
* created settings dependencies
* version bump
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboa …
=> [script.reset_watchedstate] 0.0.3

weather.ozweather/addon.xml, weather.ozweather/changelog.txt, weather.ozweather/resources/lib/forecast.py
- **General**
- Version number: 2.0.5
v2.0.5
- Improve error handling if the BOM disappears for a bit...
=> [weather.ozweather@matrix] 2.0.5

service.subtitles.subdivx/addon.xml, service.subtitles.subdivx/changelog.txt, service.subtitles.subdivx/service.py
Update to sync with website changes in search handling.
=> [service.subtitles.subdivx] 0.3.8

script.module.simpleplugin3/addon.xml, script.module.simpleplugin3/changelog.txt, script.module.simpleplugin3/libs/simpleplugin.py
- **General**
- Add-on name: SimplePlugin 3
- Add-on ID: script.module.simpleplugin3
- Version number: 3.0.6+matrix.1
- URL: https://github.com/vlmaksime/script.module.simpleplugin
SimplePlugin micro-framework that simplifies Kodi content plugin programming.
- Add compatibiliti for Python 3.10
=> [script.module.simpleplugin3@matrix] 3.0.6+matrix.1

script.module.simpleplugin3/addon.xml, script.module.simpleplugin3/changelog.txt, script.module.simpleplugin3/libs/simpleplugin.py
- **General**
- Add-on name: SimplePlugin 3
- Add-on ID: script.module.simpleplugin3
- Version number: 3.0.6
- URL: https://github.com/vlmaksime/script.module.simpleplugin
SimplePlugin micro-framework that simplifies Kodi content plugin programming.
- Add compatibiliti for Python 3.10
=> [script.module.simpleplugin3@krypton] 3.0.6

script.skipit/addon.xml, script.skipit/resources/language/resource.language.en_gb/strings.po, script.skipit/resources/lib/skipit.py
Minor bugfix and Improved handling when seek beyond the start/end of file or when player is not playing.
- [ X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0
- Kodi …
=> [script.skipit] 1.0.1

script.sublissimo/addon.xml, script.sublissimo/resources/lib/loading/loadfile.py, script.sublissimo/resources/lib/loading/loading.py, script.sublissimo/resources/lib/menu_items/shifting.py, script.sublissimo/resources/lib/menu_items/syncing.py, script.sublissimo/resources/lib/menu_items/synctwosubtitles.py, script.sublissimo/resources/lib/players/player_controller.py
=> [script.sublissimo] 2.0.1

script.sublissimo/addon.xml, script.sublissimo/resources/lib/loadfile.py, script.sublissimo/resources/lib/loading.py, script.sublissimo/resources/lib/player_controller.py, script.sublissimo/resources/lib/shifting.py, script.sublissimo/resources/lib/syncing.py, script.sublissimo/resources/lib/synctwosubtitles.py
=> [script.sublissimo] 0.2.1

script.nhlscores/addon.xml, script.nhlscores/default.py, script.nhlscores/resources/lib/scores.py
- **General**
- Add-on name: NHL Scores
- Add-on ID: script.nhlscores
- Version number: 2022.4.30+matrix.1
- URL: https://github.com/eracknaphobia/script.nhlscores
Live scoring and game updates via kodi notifications
- Run as service
=> [script.nhlscores@matrix] 2022.4.30+matrix.1

service.subtitles.supersubtitles/addon.xml, service.subtitles.supersubtitles/service.py
=> [service.subtitles.supersubtitles@matrix] 0.0.27

script.module.srgssr/README.md, script.module.srgssr/addon.xml, script.module.srgssr/lib/srgssr.py, script.module.srgssr/resources/language/resource.language.de_de/strings.po, script.module.srgssr/resources/language/resource.language.en_gb/strings.po, script.module.srgssr/resources/language/resource.language.fr_fr/strings.po, script.module.srgssr/resources/language/resource.language.it_it/strings.po
- Add support for content presented on homepage
- Add support for topics
- Add support for livestream playback …
=> [script.module.srgssr] 2.1.0

script.module.pyamf/addon.xml, script.module.pyamf/lib/pyamf/util/__init__.py
Fix literal comparison that fails with Python 3.10 …
=> [script.module.pyamf] 0.8.10+matrix.4

script.skipit/addon.xml, script.skipit/changelog.txt, script.skipit/resources/lib/skipit.py
Fixed two race conditions that caused unpredictable behaviour when skipping
- [x ] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide …
=> [script.skipit] 1.0.2

script.myepisodes/addon.xml, script.myepisodes/changelog.txt, script.myepisodes/default.py
Updating due to a deprecated function that got removed in Python 3.9. …
=> [script.myepisodes] 3.0.1

script.myepisodes/addon.xml, script.myepisodes/changelog.txt, script.myepisodes/default.py
Updating due to a typo in previous release. Previous version doesn't work and should be discarded if possible. …
=> [script.myepisodes] 3.0.2

service.upnext/README.md, service.upnext/addon.xml, service.upnext/resources/language/resource.language.hr_hr/strings.po, service.upnext/resources/language/resource.language.ja_jp/strings.po, service.upnext/resources/language/resource.language.ko_kr/strings.po, service.upnext/resources/language/resource.language.ru_ru/strings.po, service.upnext/resources/language/resource.language.sv_se/strings.po, service.upnext/resources/language/resource.language.zh_tw/strings.po, service.upnext/resources/lib/api.py, service.upnext/resources/lib/monitor.py, service.upnext/resources/lib/playbackmanager.py, service.upnext/resources/lib/player.py, service.upnext/resources/lib/playitem.py, service.upnext/resources/skins/default/1080i/script-upnext-upnext.xml
- **General**
- Version number: 1.1.8
v1.1.8 (2022-09-13)
- Never ask if Still Watching? if playedInARow is 0
- Still Watching? checks number of plays not number+1
v1.1.7 (2022-09-03)
- Update check for filename of multi-part episodes
- Check for physical disc or disc image being played
- Translation update to Russian
- Fix CI workflow
v1.1.6 (2022-03-07)
- Fix for missing mediatype video info …
=> [service.upnext@leia] 1.1.8

script.sublissimo/addon.xml, script.sublissimo/resources/language/resource.language.fi_fi/strings.po, script.sublissimo/resources/language/resource.language.it_it/strings.po, script.sublissimo/resources/language/resource.language.zh_cn/strings.po, script.sublissimo/resources/lib/play_along_file.py, script.sublissimo/resources/lib/sync_wizard.py
- Added Chinese, Finnish and Italian translations
- Minor bug fixes …
=> [script.sublissimo] 0.2.2

script.sublissimo/addon.xml, script.sublissimo/resources/language/resource.language.fi_fi/strings.po, script.sublissimo/resources/language/resource.language.it_it/strings.po, script.sublissimo/resources/language/resource.language.zh_cn/strings.po, script.sublissimo/resources/lib/players/play_along_file.py, script.sublissimo/resources/lib/players/sync_wizard.py
- Added Chinese, Finnish and Italian translations
- Minor bug fixes …
=> [script.sublissimo] 2.0.2

script.logviewer/addon.xml, script.logviewer/resources/lib/httpserver.py, script.logviewer/resources/lib/logviewer.py, script.logviewer/resources/templates/webtail.html
- **General**
- Version number: 2.1.6+matrix.1
- URL: https://github.com/i96751414/script.logviewer
- Update log level regular expressions for v20.
- Small code improvements on webtail.
=> [script.logviewer@matrix] 2.1.6+matrix.1

script.xbmc.boblight/addon.xml, script.xbmc.boblight/default.py
```plaintext
- fixed error when trying to display message about missing library
``` …
=> [script.xbmc.boblight] 2.0.20

script.module.srgssr/README.md, script.module.srgssr/addon.xml, script.module.srgssr/lib/srgssr.py
Allows SRG SSR related video plugins to list shows by date again after the website has changed. …
=> [script.module.srgssr] 2.2.1

script.nhlscores/addon.xml, script.nhlscores/resources/lib/scores.py
- **General**
- Add-on name: NHL Scores
- Add-on ID: script.nhlscores
- Version number: 2022.10.5+matrix.1
- URL: https://github.com/eracknaphobia/script.nhlscores
Live scoring and game updates via kodi notifications
- Update to f-strings
=> [script.nhlscores@matrix] 2022.10.5+matrix.1

script.module.bottle/addon.xml, script.module.bottle/lib/bottle.py
Module is crashing in recent nightlies (py 3.11) see https://github.com/enen92/script.tubecast/issues/75
=> [script.module.bottle] 0.12.23

script.module.autocompletion/addon.xml, script.module.autocompletion/lib/AutoCompletion.py
- **General**
- Version number: 2.1.0
- URL: https://github.com/finkleandeinhorn/script.module.autocompletion
=> [script.module.autocompletion@matrix] 2.1.0

script.module.autocompletion/addon.xml, script.module.autocompletion/lib/AutoCompletion.py
- **General**
- Version number: 2.1.1
- URL: https://github.com/finkleandeinhorn/script.module.autocompletion
=> [script.module.autocompletion@matrix] 2.1.1

service.subtitles.subdivx/addon.xml, service.subtitles.subdivx/changelog.txt, service.subtitles.subdivx/service.py
Adapt to new method for sending search query data (POST).
=> [service.subtitles.subdivx@gotham] 0.3.9

weather.noaa/addon.xml, weather.noaa/changelog.txt, weather.noaa/default.py, weather.noaa/resources/lib/utils.py, weather.noaa/resources/settings.xml
- radar images url path changed
- cleanup on alerts
- cleanup on chance of rain logic …
=> [weather.noaa] 2.0.10

script.module.urllib3/addon.xml, script.module.urllib3/lib/urllib3/_version.py, script.module.urllib3/lib/urllib3/connection.py, script.module.urllib3/lib/urllib3/connectionpool.py, script.module.urllib3/lib/urllib3/contrib/pyopenssl.py, script.module.urllib3/lib/urllib3/contrib/securetransport.py, script.module.urllib3/lib/urllib3/packages/six.py, script.module.urllib3/lib/urllib3/response.py, script.module.urllib3/lib/urllib3/util/retry.py, script.module.urllib3/lib/urllib3/util/url.py, script.module.urllib3/lib/urllib3/util/wait.py
urllib3 update to 1.26.13 https://github.com/urllib3/urllib3/releases/tag/1.26.13 …
=> [script.module.urllib3@matrix] 1.26.13+matrix.1

script.timers/addon.xml, script.timers/resources/lib/contextmenu/abstract_set_timer.py, script.timers/resources/lib/contextmenu/set_quick_epg_timer.py, script.timers/resources/lib/player/player.py, script.timers/resources/lib/player/player_utils.py, script.timers/resources/lib/player/playerstatus.py, script.timers/resources/lib/player/playlist.py, script.timers/resources/lib/timer/period.py, script.timers/resources/lib/timer/scheduler.py, script.timers/resources/lib/timer/scheduleraction.py, script.timers/resources/lib/timer/timer.py, script.timers/resources/lib/timer/timerwithperiod.py, script.timers/resources/lib/utils/datetime_utils.py, script.timers/resources/settings.xml
- Bugfix: scheduled timers stop working that are scheduled after Sunday (week change Sun -> Mon)
- Refactoring (more python like code, instance variables, removed getters / setters)
=> [script.timers] 3.3.1

script.wellbeing/addon.xml, script.wellbeing/resources/language/resource.language.de_de/strings.po, script.wellbeing/resources/language/resource.language.en_gb/strings.po, script.wellbeing/resources/lib/wellbeing/player.py, script.wellbeing/resources/lib/wellbeing/wellbeing.py, script.wellbeing/resources/settings.xml
Version 1.2.0 (2022-11-30)
- Added new feature: auto-stop in rest period (simular to a 'deadmanswitch')
- Added help texts
- Refactoring
=> [script.wellbeing] 1.2.0

script.module.pysubs2/addon.xml, script.module.pysubs2/changelog.txt, script.module.pysubs2/lib/pysubs2/whisper.py
Add missing whisper.py file that should have been present in 1.5.0.
=> [script.module.pysubs2] 1.5.1

.github/workflows/addon-checker.yml
=> update workflow to resolve use of deprecated methods

script.timers/addon.xml, script.timers/resources/language/resource.language.de_de/strings.po, script.timers/resources/language/resource.language.en_gb/strings.po, script.timers/resources/lib/contextmenu/abstract_set_timer.py, script.timers/resources/lib/player/player.py, script.timers/resources/lib/player/player_utils.py, script.timers/resources/lib/player/playerstatus.py, script.timers/resources/lib/timer/period.py, script.timers/resources/lib/timer/scheduler.py, script.timers/resources/lib/timer/scheduleraction.py, script.timers/resources/lib/timer/storage.py, script.timers/resources/lib/timer/timer.py, script.timers/resources/lib/timer/timerwithperiod.py, script.timers/resources/lib/utils/datetime_utils.py, script.timers/resources/lib/utils/settings_utils.py, script.timers/resources/settings.xml
v3.4.0 (2023-01-10)
- New feature: Media action in order to pause audio or video, feature request https://github.com/Heckie75/kodi-addon-timers/issues/21
- Reorganized setting levels (simple, standard, advanced, expert)
- Refactoring: moved state to timer object
- Introduced logging (see kodi.log)
=> [script.timers] 3.4.0

script.module.clouddrive.common/addon.xml, script.module.clouddrive.common/clouddrive/common/ui/addon.py
Kodi 20 fix
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting …
=> [script.module.clouddrive.common] 1.4.0

script.module.infotagger/addon.xml, script.module.infotagger/resources/modules/infotagger/listitem.py
Adds an option for internal type checking to avoid Kodi logging of Exception messages from TypeErrors
Adds a reroute for date infolabel to dateadded …
=> [script.module.infotagger] v0.0.4

script.module.srgssr/addon.xml, script.module.srgssr/lib/srgssr.py
Small fix due to change on providers site (fixes the `Homepage` and `Topics` menu) …
=> [script.module.srgssr] 2.2.2

script.timers/addon.xml, script.timers/main.py, script.timers/migration.py, script.timers/resources/language/resource.language.de_de/strings.po, script.timers/resources/language/resource.language.en_gb/strings.po, script.timers/resources/lib/contextmenu/abstract_set_timer.py, script.timers/resources/lib/contextmenu/set_quick_epg_timer.py, script.timers/resources/lib/contextmenu/set_timer.py, script.timers/resources/lib/player/player_utils.py, script.timers/resources/lib/timer/concurrency.py, script.timers/resources/lib/timer/period.py, script.timers/resources/lib/timer/scheduler.py, script.timers/resources/lib/timer/scheduleraction.py, script.timers/resources/lib/timer/storage.py, script.timers/resources/lib/timer/timer.py, script.timers/resources/lib/utils/settings_utils.py, script.timers/resources/lib/utils/vfs_utils.py, script.timers/resources/settings.xml
v3.5.0 (2023-02-07)
- New feature: priority of timers and competitive behavior
- New feature: System action to put playing device on standby via a CEC peripheral
- Fixed issue so that favourites can be scheduled again
=> [script.timers] 3.5.0

script.skin.info.service/Utils.py, script.skin.info.service/addon.xml, script.skin.info.service/default.py
[script.skin.info.service] 1.2.0
Kodi Matrix/Nexus changes …
=> [script.skin.info.service] 1.2.0

service.subtitles.napisy24pl/addon.xml, service.subtitles.napisy24pl/resources/lib/NapisyUtils.py, service.subtitles.napisy24pl/service.py
This release fixes an issue with decode utf-8 of latin text.
closes https://github.com/CaTzil/service.subtitles.napisy24pl/issues/31 …
=> [service.subtitles.napisy24pl] 3.0.6

script.sublissimo/addon.xml, script.sublissimo/resources/language/resource.language.de_de/strings.po, script.sublissimo/resources/language/resource.language.hr_hr/strings.po
- Added Croatian and German translations.  …
=> [script.sublissimo] 2.0.3

script.sublissimo/addon.xml, script.sublissimo/resources/language/resource.language.de_de/strings.po, script.sublissimo/resources/language/resource.language.hr_hr/strings.po
- Added Croatian and German translations.  …
=> [script.sublissimo] 0.2.3

script.radioparadise/CHANGELOG.md, script.radioparadise/README.md, script.radioparadise/addon.xml, script.radioparadise/radioparadise.py, script.radioparadise/resources/language/resource.language.en_gb/strings.po
- Update "Global Mix" name and URLs …
=> [script.radioparadise] 1.0.5

script.module.srgssr/addon.xml, script.module.srgssr/lib/srgssr.py
- **General**
- Add-on name: SRG SSR
- Add-on ID: script.module.srgssr
- Version number: 2.2.3
- URL: https://github.com/goggle/script.module.srgssr
This addon allows a plugin to use the media libraries of SRG SSR.
=> [script.module.srgssr@matrix] 2.2.3

script.module.infotagger/addon.xml, script.module.infotagger/resources/modules/infotagger/listitem.py
Adds a basic factory method to generate class object
Skip count, date, size infolabels as overlooked and currently missing setters for InfoTagVideo/Music/Game 
(see Ref issue: https://github.com/xbmc/xbmc/issues/22752)
Adds a `set_info_tag` function which combines factory with a bandaid fix for overlooked keys. 
Reroutes these keys to old setInfo method as temporary bandaid until resolved upstream
Usage of set_info_tag
``` python
from infotagger.listitem import set_info_tag
info_tag = set_info_tag(listitem, infolabels, tag_type='video')  # tag_type optional and defaults to 'video'
```
- [add-on …
=> [script.module.infotagger] 0.0.7

script.myepisodes/addon.xml, script.myepisodes/changelog.txt, script.myepisodes/default.py, script.myepisodes/kodilogging.py, script.myepisodes/myepisodes.py, script.myepisodes/resources/settings.xml, script.myepisodes/utils.py
+ Important refactor and bug fixes. …
=> [script.myepisodes] 3.2.0

weather.noaa/addon.xml, weather.noaa/changelog.txt, weather.noaa/default.py, weather.noaa/resources/lib/utils.py, weather.noaa/resources/settings.xml
- fix wind-chill calculation
- if we have a direct windchill or headindex value from the api, use that instead of calculating it
- refresh the gridpoint and forecast urls from the lattitude/longitude every couple of days to handle grid changes in the api
- only reset location descriptive name when lat,long is entered
- retry after a minute if there is an error from the api
- fixes when using forecast.weather.gov as the source
- …
=> [weather.noaa] 2.0.11

service.subtitles.legendasdivx/README.md, service.subtitles.legendasdivx/addon.xml, service.subtitles.legendasdivx/changelog.txt, service.subtitles.legendasdivx/service.py
Fix for Nexus;
Search speed up; …
=> [service.subtitles.legendasdivx] 1.0.6

script.module.t1mlib/addon.xml, script.module.t1mlib/lib/t1mlib.py, script.module.t1mlib/readme.txt
Update `script.module.t1mlib` with the following changes
-  use `xbmcfvs.translatePath` instead of removed method `xbmx.translatePath` (Removed here https://github.com/xbmc/xbmc/pull/19301)
- Update t1mlib to use `html.unescape` instead of `html.parser.HTMLParser().unescape` (Removed in Python 3.9 https://github.com/python/cpython/pull/14186)
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best …
=> [script.module.t1mlib] 4.0.8

service.upnext/README.md, service.upnext/addon.xml, service.upnext/resources/language/resource.language.sv_se/strings.po, service.upnext/resources/lib/api.py, service.upnext/resources/lib/monitor.py, service.upnext/resources/lib/playbackmanager.py, service.upnext/resources/lib/playitem.py, service.upnext/resources/lib/utils.py
- **General**
- Version number: 1.1.9+matrix.1
v1.1.8 (2022-09-13)
- Never ask if Still Watching? if playedInARow is 0
- Still Watching? checks number of plays not number+1
v1.1.7 (2022-09-03)
- Update check for filename of multi-part episodes
- Check for physical disc or disc image being played
- Translation update to Russian
- Fix CI workflow
v1.1.6 (2022-03-07)
- Fix for missing mediatype …
=> [service.upnext@matrix] 1.1.9+matrix.1

service.upnext/README.md, service.upnext/addon.xml, service.upnext/resources/language/resource.language.sv_se/strings.po, service.upnext/resources/lib/api.py, service.upnext/resources/lib/monitor.py, service.upnext/resources/lib/playbackmanager.py, service.upnext/resources/lib/playitem.py, service.upnext/resources/lib/utils.py
- **General**
- Version number: 1.1.9
v1.1.8 (2022-09-13)
- Never ask if Still Watching? if playedInARow is 0
- Still Watching? checks number of plays not number+1
v1.1.7 (2022-09-03)
- Update check for filename of multi-part episodes
- Check for physical disc or disc image being played
- Translation update to Russian
- Fix CI workflow
v1.1.6 (2022-03-07)
- Fix for missing mediatype video info …
=> [service.upnext@leia] 1.1.9

weather.metoffice/addon.xml, weather.metoffice/changelog.txt, weather.metoffice/resources/settings.xml, weather.metoffice/src/default.py, weather.metoffice/src/metoffice/astronomy.py, weather.metoffice/src/metoffice/constants.py, weather.metoffice/src/metoffice/properties.py, weather.metoffice/src/metoffice/urlcache.py, weather.metoffice/src/metoffice/utilities.py, weather.metoffice/src/setlocation.py
- Cleaned up memory leaks
- Removed unused imaging code.
- Removed default API key and nudged user to get their own.
=> [weather.metoffice] v4.0.0

service.subtitles.opensubtitles-com/addon.xml, service.subtitles.opensubtitles-com/changelog.txt, service.subtitles.opensubtitles-com/resources/language/resource.language.hu_HU/strings.po, service.subtitles.opensubtitles-com/resources/language/resource.language.sv_SE/strings.po, service.subtitles.opensubtitles-com/resources/lib/data_collector.py, service.subtitles.opensubtitles-com/resources/lib/subtitle_downloader.py
Update for opensubtitles.com (next opensubtitles) with the removal of the 10 sub limitation and fix for portuguese/brazilian flags.
cc @opensubtitlesdev
=> [service.subtitles.opensubtitles-com] 1.0.1

service.subtitles.opensubtitles-com/README.md, service.subtitles.opensubtitles-com/addon.xml, service.subtitles.opensubtitles-com/changelog.txt, service.subtitles.opensubtitles-com/resources/lib/os/provider.py
Added the new "User-Agent"  header required by the opensubtitles.com api
- [ X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0
=> [service.subtitles.opensubtitles-com] 1.0.2

script.module.pyxbmct/addon.xml, script.module.pyxbmct/lib/pyxbmct/addonskin.py, script.module.pyxbmct/lib/pyxbmct/addonwindow.py
- **General**
- Add-on name: PyXBMCt
- Add-on ID: script.module.pyxbmct
- Version number: 1.3.2+matrix.1
- URL: https://github.com/romanvm/script.module.pyxbmct
PyXBMCt is a mini-framework for simple XBMC addon UI buliding. It is similar to PyQt and provides parent windows, a number of UI controls (widgets) and a grid layout manager to place controls.
1.3.2:
- Drop Python 2 compatibility
=> [script.module.pyxbmct@matrix] 1.3.2+matrix.1

script.module.dropbox/addon.xml, script.module.dropbox/lib/dropbox/stone_serializers.py
Contains a fix for a strptime bug as outlined here: https://bugs.python.org/issue27400 
Wasn't sure what to do about the versioning since this is an enhancement to the original library code. Can adjust if needed. 
- This add-on repository has automated code guideline check which could help you improve your coding. You can …
=> [script.module.dropbox] 10.3.1+matrix.1

weather.gismeteo/addon.xml, weather.gismeteo/changelog.txt, weather.gismeteo/default.py, weather.gismeteo/resources/language/resource.language.de_de/strings.po, weather.gismeteo/resources/libs/__init__.py, weather.gismeteo/resources/libs/gismeteo.py, weather.gismeteo/resources/libs/simpleweather/webclient.py
- **General**
- Version number: 0.6.4+matrix.1
v0.6.4 (2023-10-30)[CR]- Adapted to changes in the service API[CR]- Added German translation (kyoforkshomebrews)[CR][CR]v0.6.3 (2021-09-27)[CR]- Fixed identified bugs[CR][CR]v0.6.2 (2021-05-31)[CR]- Updated compatibility with Kodi 19[CR]- Added Icelandic translation (sveinki)[CR][CR]v0.6.1 (2021-04-03)[CR]- SimplePlugin 3 module moved into external addon[CR]- Small changes in the add-on structure [CR]- Added French translation (DavidHenryThoreau)[CR]- Added Swedish translation (Sopor)
=> [weather.gismeteo@matrix] 0.6.4+matrix.1

script.nhlscores/addon.xml, script.nhlscores/resources/lib/scores.py
- **General**
- Add-on name: NHL Scores
- Add-on ID: script.nhlscores
- Version number: 2023.12.27+matrix.1
- URL: https://github.com/eracknaphobia/script.nhlscores
Live scoring and game updates via kodi notifications
- Fixed for upstream api changes
=> [script.nhlscores@matrix] 2023.12.27+matrix.1

weather.multi/addon.xml, weather.multi/lib/weather.py
* Fixed  URL for Yahoo to make service work again (acc. https://forum.kodi.tv/showthread.php?tid=352028&page=16)
=> [weather.multi] 0.0.21

service.subtitles.opensubtitles-com/README.md, service.subtitles.opensubtitles-com/addon.xml, service.subtitles.opensubtitles-com/changelog.txt, service.subtitles.opensubtitles-com/resources/language/resource.language.en_GB/strings.po, service.subtitles.opensubtitles-com/resources/language/resource.language.fr_FR/strings.po, service.subtitles.opensubtitles-com/resources/language/resource.language.hu_HU/strings.po, service.subtitles.opensubtitles-com/resources/language/resource.language.sv_SE/strings.po, service.subtitles.opensubtitles-com/resources/language/resource.language.zh_CN/strings.po, service.subtitles.opensubtitles-com/resources/lib/data_collector.py, service.subtitles.opensubtitles-com/resources/lib/exceptions.py, service.subtitles.opensubtitles-com/resources/lib/file_operations.py, service.subtitles.opensubtitles-com/resources/lib/os/provider.py, service.subtitles.opensubtitles-com/resources/lib/subtitle_downloader.py
Multiple fixes on file path, language submitted by user "[pannal](https://github.com/pannal)" [opensubtitlesdev/service.subtitles.opensubtitles-com](https://github.com/opensubtitlesdev/service.subtitles.opensubtitles-com/pull/)
Improvements of the error messages for the user
* [x ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project.
* [ x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
* [ x] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0
* Submitting your add-on to this specific branch makes it available to any Kodi version equal or …
=> [service.subtitles.opensubtitles-com] 1.0.4

script.simkl/addon.xml, script.simkl/changelog.txt, script.simkl/resources/lib/engine.py
=> [script.simkl] 3.2.2

service.watchedlist/addon.xml, service.watchedlist/lib/watchedlist/watchedlist.py
Changes related to a timestamp bug reported in the [forum](https://forum.kodi.tv/showthread.php?tid=164652&pid=3099646#pid3099646) and on [GitHub](https://github.com/SchapplM/xbmc-addon-service-watchedlist/issues/28#issuecomment-1890145879).
=> [service.watchedlist] 1.3.7

script.module.srgssr/addon.xml, script.module.srgssr/lib/srgssr.py
Fixes the `translatePath` error that some of the users have encountered. …
=> [script.module.srgssr@matrix] 2.2.4

script.copacetic.helper/README.md, script.copacetic.helper/addon.xml, script.copacetic.helper/resources/lib/service/monitor.py, script.copacetic.helper/resources/lib/service/player.py
- Capture setId for playing video
- Add favouritesbrowser to background slideshow monitor
-  …
=> [script.copacetic.helper 1.0.13]

script.timers/addon.xml, script.timers/resources/lib/player/player.py
v3.9.2 (2024-07-21)
- Bugfix: The repeat flag in Timer Addon doesn't work, issue https://github.com/Heckie75/kodi-addon-timers/issues/39
=> [script.timers] 3.9.2
