xbmc/repo-scripts

script.xbmc.boblight/addon.xml, script.xbmc.boblight/changelog.txt, script.xbmc.boblight/resources/lib/tools.py
2.0.13
- [feature] - enable androidx86 support 
- pull from kodi.tv instead of xbmc.org
confirmed working here:
http://forum.kodi.tv/showthread.php?tid=226426&pid=2000449#pid2000449
=> [script.xbmc.boblight] 2.0.13

script.common.plugin.cache/addon.xml, script.common.plugin.cache/changelog.txt, script.common.plugin.cache/lib/StorageServer.py
This fixes the annoying error when common cache fails to start due to too long socket path when calling bind. It uses the same approach like for win32 and android for ios and tvos now too. (with a small refactor to not dupe that code too much...)
=> [script.common.plugin.cache] 2.5.6

script.xbmc.boblight/addon.xml, script.xbmc.boblight/changelog.txt, script.xbmc.boblight/resources/lib/tools.py
fixed aarch64 detection (nvidia shield)
=> [script.xbmc.boblight] 2.0.16

service.skin.widgets/addon.xml, service.skin.widgets/changelog.txt, service.skin.widgets/default.py
Circular references aren't collected by the garbage collector.
Fixes this warning on shutdown:
```
DEBUG: ADDON: Stopping service addons.
DEBUG: Skin Widgets: script version 0.0.30 stopped
INFO: CPythonInvoker(0, /Users/anaconda/Library/Application Support/Kodi/addons/service.skin.widgets/default.py): script successfully run
DEBUG: CPythonInvoker(0, /Users/anaconda/Library/Application Support/Kodi/addons/service.skin.widgets/default.py): script termination took 489ms
WARNING: CPythonInvoker(0, /Users/anaconda/Library/Application Support/Kodi/addons/service.skin.widgets/default.py): the python script "/Users/anaconda/Library/Application Support/Kodi/addons/service.skin.widgets/default.py" has left several classes in memory that we couldn't clean up. The classes include: …
```
=> [service.skin.widgets] 0.0.31 - Fix circular reference warnings on shutdown

service.nextup.notification/addon.xml, service.nextup.notification/resources/lib/Player.py
Sorry for the quick additional PR, found a critical bug with the last changes. I put back the sleeps for the ones that are under a second.
=> [service.nextup.notification] 1.0.20

service.subtitles.legendasdivx/addon.xml, service.subtitles.legendasdivx/changelog.txt, service.subtitles.legendasdivx/service.py
Android\Linux crash solved. _temp variable not decoded to utf-8 by default.
=> [service.subtitles.legendasdivx] 0.2.8

service.subtitles.traduttorianonimi/addon.xml, service.subtitles.traduttorianonimi/changelog.txt, service.subtitles.traduttorianonimi/resources/lib/TraduttoriAnonimi.py, service.subtitles.traduttorianonimi/resources/lib/utils.py, service.subtitles.traduttorianonimi/service.py
Hi. The version of my addon (2.0.3) merged 15 hours ago. works only on Windows and Linux but not on android devices (tested on Android 5.1.1 with kodi 16.1 apk downloaded from kodi.tv) because version of logging module is lower than "0.5.1.2", so now i fixed my addon and now is compatibile with lower versions of logging (removing "getChild()"), another thing, python 2.6 requires that "{}".format(something) must have and integer like this => ("{0}".format(something), so if fixed also this.
-Why the SAME version of kodi uses different version of python on android ???
=> [service.subtitles.traduttorianonimi] 2.0.4

script.module.dropbox/addon.xml, script.module.dropbox/changelog.txt, script.module.dropbox/lib/dropbox/rest.py
Hi, this fixes a problem the android version of Kodi (or its Python interpreter) had with the dropbox rest API code.
=> [script.module.dropbox] 2.2.2

script.screensaver.football.panel/addon.xml, script.screensaver.football.panel/changelog.txt, script.screensaver.football.panel/interface.py
Currently the start times for the matches are incorrect since XML Soccer (the site thesportsdb uses to grab information) started to provide the match times based on UTC instead of the former GMT.
This is a really simple commit to fix it.
Regards
=> [script.screensaver.football.panel] 1.3.1

script.screensaver.football.panel/addon.xml, script.screensaver.football.panel/changelog.txt, script.screensaver.football.panel/interface.py, script.screensaver.football.panel/resources/language/English/strings.po, script.screensaver.football.panel/resources/language/Portuguese/strings.po, script.screensaver.football.panel/resources/lib/cache.py, script.screensaver.football.panel/resources/lib/common_addon.py, script.screensaver.football.panel/resources/settings.xml
This PR implements some caching mechanisms for team logos and league data as requested by @zag2me in http://forum.kodi.tv/showthread.php?tid=258252&pid=2408318#pid2408318 in order to reduce the database server load.
Many thanks
=> [script.screensaver.football.panel] 1.4.0

script.module.kodiswift/addon.xml, script.module.kodiswift/changelog.txt, script.module.kodiswift/lib/kodiswift/listitem.py, script.module.kodiswift/lib/kodiswift/xbmcmixin.py
- Made `listitem.playable` use it's own property to allow `is_folder` and `playable` to be independent
- Make sure list item has 'as_tuple' method
=> [script.module.kodiswift] 0.0.7

service.subtitles.subscenter/addon.xml, service.subtitles.subscenter/changelog.txt, service.subtitles.subscenter/service.py
Add the ability to search for subs when not playing videos. …
=> [service.subtitles.subscenter] v4.1.1

service.subtitles.subtitle/addon.xml, service.subtitles.subtitle/changelog.txt, service.subtitles.subtitle/service.py
Add the option for using the addon when kodi isn't playing
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuesly …
=> [service.subtitles.subtitle] v4.5.0

service.subtitles.torec/addon.xml, service.subtitles.torec/changelog.txt, service.subtitles.torec/resources/lib/SubtitleHelper.py, service.subtitles.torec/resources/lib/TorecSubtitlesDownloader.py, service.subtitles.torec/service.py, service.subtitles.torec/tests/tvshow_tests.py
- Improvement for the option of using the addon when kodi is not playing (@burekas7)
- Add support for local tvshow content (@burekas7)
- Fix bug for last episode in a season that didn't return results. (@burekas7)
- This add-on repository has automated code guideline check which could help you improve your coding. You …
=> [service.subtitles.torec] 1.2.1

service.subtitles.supersubtitles/addon.xml, service.subtitles.supersubtitles/changelog.txt, service.subtitles.supersubtitles/resources/language/English/strings.po, service.subtitles.supersubtitles/service.py
- open file browse dialog if automatic search failed in unpacked dir
- change rating calculation logic
- remove VideoPlayer.Year usage …
=> [service.subtitles.supersubtitles] 0.0.22

weather.ozweather/addon.xml, weather.ozweather/changelog.txt, weather.ozweather/default.py
OzWeather 0.8.9 
Bugfix if user sets no radar code for a location
Remove stray use of print
=> [weather.ozweather] 0.8.9

service.kn.switchtimer/addon.xml, service.kn.switchtimer/changelog.txt, service.kn.switchtimer/handler.py, service.kn.switchtimer/resources/language/Dutch/strings.po, service.kn.switchtimer/resources/language/English/strings.po, service.kn.switchtimer/resources/language/German/strings.po, service.kn.switchtimer/resources/language/Portuguese/strings.po, service.kn.switchtimer/resources/settings.xml, service.kn.switchtimer/service.py
Changelog:
2.0.2
- create settings path if not exists. This avoids IOExceptions when writing timers and the addon
wasn't configured yet.
=> [service.kn.switchtimer] 2.0.2 update

script.module.t1mlib/addon.xml, script.module.t1mlib/changelog.txt, script.module.t1mlib/lib/t1mlib.py, script.module.t1mlib/readme.txt
Fix for timeouts on Kodi 17.0 on android
[script.module.t1mlib] 1.0.18
- [x ] Each add-on submission should be a single commit with using the following style: [sciprt.foo.bar] v1.0.0
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide …
=> [script.module.t1mlib] 1.0.18

screensaver.atv4/addon.xml, screensaver.atv4/atv.py, screensaver.atv4/changelog.txt, screensaver.atv4/resources/language/English/strings.po, screensaver.atv4/resources/language/Portuguese/strings.po, screensaver.atv4/resources/lib/downloader.py, screensaver.atv4/resources/settings.xml, screensaver.atv4/resources/skins/default/1080i/screensaver-atv4-trans.xml, screensaver.atv4/resources/skins/default/1080i/screensaver-atv4.xml, screensaver.atv4/resources/skins/default/720p/screensaver-atv4-trans.xml, screensaver.atv4/resources/skins/default/720p/screensaver-atv4.xml, screensaver.atv4/screensaver.py, screensaver.atv4/service.py, screensaver.atv4/trans.py
-Changed overall screensaver init logic (made it a video addon so when the screensaver deactivates it just calls the video addon). Current logic is wrong, lead to errors and playback stuttering.
-Implemented DPMS so users can pause or stop the video if a certain playback time is reached (plus trigger DPMS or display off via cec) - in order to avoid wasted cpu cycles.
=> [screensaver.atv4] 1.4.0

README.md
The markdown syntax of the hyperlinks was incorrect in README.md.
=> Fixed hyperlinks

script.video.randomtv/README.md, script.video.randomtv/addon.py, script.video.randomtv/addon.xml, script.video.randomtv/resources/language/resource.language.en_gb/strings.po, script.video.randomtv/resources/settings.xml
v1.1.0 (28 April 2017)
- Added Auto Stop Feature
- Replaced xbmc.sleep with xbmc.Monitor().waitForAbort …
=> [script.video.randomtv] 1.1.0

script.video.randomtv/addon.py, script.video.randomtv/addon.xml, script.video.randomtv/resources/settings.xml
v1.1.2 (30 April 2017)
- Fixed Bugs in AutoStop Feature
- Fixed Bug where Playlist would be shuffled after each video ended
- Added Empty Window to prevent Kodi from being displayed between Playlist Shuffles
=> [script.video.randomtv] 1.1.2

script.playrandomvideos/README.md, script.playrandomvideos/addon.xml, script.playrandomvideos/changelog.txt, script.playrandomvideos/resources/lib/listitembuilder.py
- set dbid and mediatype for ListItems as required by Krypton. …
=> [script.playrandomvideos] 1.1.2

service.kn.switchtimer/addon.xml, service.kn.switchtimer/addtimer.py, service.kn.switchtimer/changelog.txt, service.kn.switchtimer/deltimer.py, service.kn.switchtimer/handler.py, service.kn.switchtimer/service.py
Update to v2.0.3:
- Introduction and usage of module dateutil as a more robust date/time calculation/conversion between various time formats. …
=> [service.kn.switchtimer] v2.0.3

service.subtitles.subtituloses/addon.xml, service.subtitles.subtituloses/changelog.txt, service.subtitles.tusubtitulo/addon.xml, service.subtitles.tusubtitulo/changelog.txt
Both addons are not maintained anymore since both webpages either changed or went down so none of them work anymore.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboar …
=> [service.subtitles.subtituloses] and [service.subtitles.tusubtitulo] broken

script.xbmc.boblight/addon.xml, script.xbmc.boblight/changelog.txt, script.xbmc.boblight/resources/lib/tools.py
Sorry about that rapid bump. The detection of the 64bit runtime returned true whenever a 64bit Windows was installed and didn't distinguish between kodi being 32bit or 64bit. I thought i have tested this but i didn't.
This fixes the detection.
=> [script.xbmc.boblight] 2.0.18

script.tag-generator/addon.xml
Oauth version number is 2.0.1 not 2.1.0. This incorrect version number prevented tag-generator from updating.  …
=> [script.tag-generator] 0.5.2

.gitmodules, .travis.yml, README.md
Adds the new addon-check python tool and runs it via travis.
=> Add addon-check as submodule and setup travis-ci

weather.ozweather/addon.xml, weather.ozweather/changelog.txt, weather.ozweather/resources/lib/weatherzone.py
Fix for minor cut and paste error
I pulled the changes to upstream (`git pull upstream gotham`) in my repo-scripts clone before doing this...but the instructions are broken/missing something - the only way I can get a clean single commit is to re-fork and set up the whole subtree thing again each time, and that's just  too much work/time....Aus internet is generally shit and it takes up to half an hour to clone xbmc-scripts each time.
Please can someone properly fix these instructions?   (http://kodi.wiki/view/HOW-TO:Create_add-on_PRs_using_Git_Subtree_Merging).  They are not currently dealing with, when doing updates, how to properly incorporate the upstream changes that may have happened in the meantime, such that when one commits a new update, you don't get a bunch of these extra …
=> [weather.ozweather] v0.9.7

script.module.buggalo/README.md, script.module.buggalo/addon.xml, script.module.buggalo/changelog.txt, script.module.buggalo/lib/buggalo.py, script.module.buggalo/lib/buggalo_client.py, script.module.buggalo/lib/buggalo_gui.py
Following the discussion in https://github.com/xbmc/repo-scripts/pull/679#discussion_r156290860, I would like to merge an update to script.module.buggalo. The addon does not seem to be maintained any more. The addon does not seem to be used by more than 3 addons, but it is in my opinion very helpful for more efficient addon development.
As described in my PR https://github.com/twinther/script.module.buggalo/pull/6 and in the new [buggalo Readme](https://github.com/SchapplM/script.module.buggalo/blob/email_ssl/README.md), for bug report emails to work, login credentials to an email server have to be placed in plain text in the source code of the addons.
Ideally, every developer would create email accounts for his addons and set a different password for the smtp authentification than for …
=> [script.module.buggalo] 1.1.7

service.watchedlist/addon.xml, service.watchedlist/changelog.txt, service.watchedlist/lib/watchedlist/watchedlist.py, service.watchedlist/resources/language/resource.language.de_de/strings.po, service.watchedlist/resources/language/resource.language.en_gb/strings.po
minor fix and extended exception-handling.
I got some bug report emails where `SystemExit` exception was raised.
I guess this comes from the user exiting Kodi by the shutdown menu.
However I do not understand, why the bug report dialogue can still be displayed (the whole bug report process takes a few seconds).
Also I put `monitor.waitForAbort` everywhere, so exiting Kodi should not raise an exception in python.
Is catching `SystemExit` manually the right solution here?
=> [service.watchedlist] 1.2.4

script.artistslideshow/addon.xml, script.artistslideshow/changelog.txt, script.artistslideshow/default.py, script.artistslideshow/resources/common/fileops.py, script.artistslideshow/resources/common/url.py, script.artistslideshow/resources/common/xlogger.py, script.artistslideshow/resources/language/English/strings.po, script.artistslideshow/resources/plugins/fanarttv.py, script.artistslideshow/resources/plugins/theaudiodb.py, script.artistslideshow/resources/settings.xml
- updated AS to save and use unhashed artist and image names
- created upgrade routine to rename hashed artist and image names
- included new option to ONLY use local artist path for storage
- cleaned up folder path creation routines
- removed old download exclusion logic in favor of new _imgdb.nfo history
- [x ] Each add-on submission should be a single commit with using the following style: [script.foo.bar] v1.0.0
=> [script.artistslideshow] v2.1.0

script.common.plugin.cache/addon.xml, script.common.plugin.cache/changelog.txt, script.common.plugin.cache/lib/StorageServer.py
Fix `self` usage in non instance methods
@Lunatixz @rmrector should fix the issue reported at #746
=> [script.common.plugin.cache] 2.5.10

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/changelog.txt, script.module.inputstreamhelper/lib/config.py, script.module.inputstreamhelper/lib/inputstreamhelper.py, script.module.inputstreamhelper/resources/language/resource.language.de_de/strings.po, script.module.inputstreamhelper/resources/language/resource.language.en_gb/strings.po, script.module.inputstreamhelper/resources/settings.xml
2018.01.29 v0.3.0
+ Bug fix: module left xbmcaddon class in memory
+ Keep Widevine CDM up-to-date with the latest version available (Kodi 18 and higher)
+ Check for missing depending libraries by parsing the output from ldd
+ Use older Widevine binaries on Kodi Krypton (fixes nss/nspr dependency issues)
- This add-on …
=> [script.module.inputstreamhelper] 0.3.0

script.artistslideshow/addon.xml, script.artistslideshow/changelog.txt, script.artistslideshow/default.py, script.artistslideshow/resources/common/fileops.py, script.artistslideshow/resources/common/transforms.py, script.artistslideshow/resources/common/url.py, script.artistslideshow/resources/common/xlogger.py, script.artistslideshow/resources/language/English/strings.po, script.artistslideshow/resources/plugins/fanarttv.py, script.artistslideshow/resources/plugins/theaudiodb.py, script.artistslideshow/resources/settings.xml
v.2.1.1
- added option to download artist thumb from theaudiodb.com
- added option to store service information files in local artist path
- change to cache timing including decreased cache time if donating to image services
- rearranged settings
- fixes to exception handling syntax to be consistent with Python3
- refactored some common functions
- change to fileops common module for compatibility with Windows Store version of Kodi
- [ x ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ x ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [ x ] Each add-on submission should be a single commit with using the …
=> [script.artistslideshow] 2.1.1

script.module.kodi-six/addon.xml, script.module.kodi-six/libs/kodi_six/utils.py
Removed patching `__init__` methods because it screws with class MRO in case of complex inheritance scheme. …
=> [script.module.kodi-six] 0.0.2

service.subtitles.subdivx/addon.xml, service.subtitles.subdivx/changelog.txt, service.subtitles.subdivx/service.py
Compatibility with Kodi 18. This means we now depend (only for Kodi 18) on the `vfs.libarchive` binary addon (by spiff.)
Add Spanish entries to `addon.xml`.
Remove temporary directories used during decompression of downloaded files.
- This add-on repository has automated code guideline check which could help you improve …
=> [service.subtitles.subdivx] 0.3.0

service.subtitles.subscene/addon.xml, service.subtitles.subscene/resources/lib/ordinal.py, service.subtitles.subscene/service.py
When searching for subtitles for a TV show that contains more than 29 seasons, the error below can be seen in the logs:
```
12:08:36.047 T:1364964256   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.IndexError'>
Error Contents: list index out of range
Traceback (most recent call last):
File "/storage/.kodi/addons/service.subtitles.subscene/service.py", line 532, in <module>
search(item)
File "/storage/.kodi/addons/service.subtitles.subscene/service.py", line 355, in search
search_tvshow(item['tvshow'], item['season'], item['episode'], item['3let_language'], filename)
File "/storage/.kodi/addons/service.subtitles.subscene/service.py", line 307, in …
```
=> [service.subtitles.subscene] v1.7.2

service.subtitles.subdivx/addon.xml, service.subtitles.subdivx/changelog.txt, service.subtitles.subdivx/service.py
Fix a race condition with a Kodi API call introduced in v0.3.0 which causes problems for many users. Also, reduce verbosity of old temporary dirs non-fatal removal failures.
=> [service.subtitles.subdivx] 0.3.2

script.xbmc.lcdproc/addon.xml, script.xbmc.lcdproc/changelog.txt, script.xbmc.lcdproc/main.py, script.xbmc.lcdproc/resources/LCD.xml.defaults, script.xbmc.lcdproc/resources/lib/charset_hd44780.py, script.xbmc.lcdproc/resources/lib/charset_map_hd44780_a02.py, script.xbmc.lcdproc/resources/lib/common.py, script.xbmc.lcdproc/resources/lib/extraicons.py, script.xbmc.lcdproc/resources/lib/infolabels.py, script.xbmc.lcdproc/resources/lib/lcdbase.py, script.xbmc.lcdproc/resources/lib/lcdproc.py, script.xbmc.lcdproc/resources/lib/lcdproc_extra_base.py, script.xbmc.lcdproc/resources/lib/lcdproc_extra_imon.py, script.xbmc.lcdproc/resources/lib/lcdproc_extra_mdm166a.py, script.xbmc.lcdproc/resources/lib/settings.py
From changelog.txt and addon.xml:
3.0.1
- Imports cleaned up
- Compatibility with Python 3
Re py3 compat: Tested with Python2.7 on Gentoo and Ubuntu 18, and Python3.5 and 3.6 on Gentoo. Everything working without issues, no need for any future imports or such things. The only "compat" thing needed is the different handling of xbmc.GetInfoLabel() in infolabels.py:InfoLabel_GetInfoLabel(), which for some reason works without the need to call .decode() on my Gentoo system, but would bail out on Ubuntu with a conversion error, where it believes it should decode from ascii (where umlauts don't fit in 7 bits).
**EDIT**: "Tested with Python 3.5 and 3.6" means runtime-tested with Kodi built from the feature_python3 branch.
=> [script.xbmc.lcdproc] 3.0.1

script.myepisodes/addon.xml
Mark addon as broken; a new version will be available for Krypton and up.
=> [script.myepisodes] 1.2.8: mark as broken

script.myepisodes/addon.xml
The bump is here to avoid marking the addon in Helix as broken too (its
version being 1.2.6; it should be enough)
=> [script.myepisodes] 1.2.7: mark as broken

context.artwork.downloader.auto/addon.xml
Version bump. I went with 1.0.1-broken because newer versions do exist in my dev repo to work with Artwork Beef. …
=> [context.artwork.downloader.auto] 1.0.1-broken

service.subsmangler/README.md, service.subsmangler/addon.xml, service.subsmangler/changelog.txt, service.subsmangler/resources/language/resource.language.cs_cz/strings.po, service.subsmangler/resources/language/resource.language.de_de/strings.po, service.subsmangler/resources/language/resource.language.en_gb/strings.po, service.subsmangler/resources/language/resource.language.hu_hu/strings.po, service.subsmangler/resources/language/resource.language.pl_pl/strings.po, service.subsmangler/resources/language/resource.language.sk_sk/strings.po, service.subsmangler/resources/lib/common.py, service.subsmangler/resources/lib/contextmenu.py, service.subsmangler/resources/lib/smangler.py, service.subsmangler/resources/regexdef.def, service.subsmangler/resources/settings.xml
- add ability to convert subtitles without enforcing .ass format (and therefore adding custom font/background color and opacity). In this case file is saved in SubRip format.
=> [service.subsmangler] 1.3.0

script.myepisodes/addon.xml, script.myepisodes/changelog.txt, script.myepisodes/default.py
Update due to some changes introduced in Leia in the hookup of the player playback, it created a bug with remote content media server (SMB/NFS) which introduced an enough latency to trigged the problem (basically, the length of the video was always 0 because the player was ready but not the content).
- This add-on …
=> [script.myepisodes] 2.0.1

service.subtitles.rvm.addic7ed/addic7ed/core.py, service.subtitles.rvm.addic7ed/addic7ed/parser.py, service.subtitles.rvm.addic7ed/addon.xml
- **General**
- Version number: 3.0.4
- URL: https://https://github.com/romanvm/service.addic7ed
v.3.0.4:
- Synced subs are shown first in the list.
- Unfinished translations are hidden from users that aren't logged in.
- Fixed parsing translated episode pages (non-English).
- Fixed re-synced subtitles marked as "sync".
=> [service.subtitles.rvm.addic7ed] 3.0.4

script.module.codequick/addon.xml, script.module.codequick/lib/codequick/listing.py
Some feature requests
- Allow to disable automatic setting of fanart, thumbnail or icon images.
- Allow for plugin paths as folders in set_callback.
- Allow for a callback path to be passed instead of a function
=> [script.module.codequick] 0.9.9

script.module.urllib3/addon.xml, script.module.urllib3/changelog.txt, script.module.urllib3/lib/CHANGES.rst, script.module.urllib3/lib/urllib3/__init__.py, script.module.urllib3/lib/urllib3/util/ssl_.py, script.module.urllib3/lib/urllib3/util/url.py
* Bump [`urllib3`](https://pypi.org/project/urllib3/) to version 1.25.2. See upstream [`CHANGES.rst`](https://github.com/urllib3/urllib3/blob/1.25.2/CHANGES.rst) for upstream changes.
This update fixes at least one bug from upstream urllib3 1.25.1 known to affect Kodi users: https://github.com/Freso/script.module.urllib3/issues/2
=> [script.module.urllib3] 1.25.2

PULL_REQUEST_TEMPLATE.md
The current/old PR template asks for commits to use “vX.Y.Z” in commits adding add‐ons to the repository, but in actuality the vast majority of commits use “X.Y.Z” without the “v”[1]. This is just a small change to make the template reflect actual usage.
[1]
https://github.com/xbmc/repo-scripts/commits/leia
https://github.com/xbmc/repo-scripts/commits/krypton
etc.
=> Update PR template for de facto commit name style

screensaver.kaster/addon.xml, screensaver.kaster/resources/lib/screensaver.py, screensaver.kaster/resources/lib/screensaverutils.py, screensaver.kaster/resources/skins/default/1080i/screensaver-kaster.xml
- **General**
- Version number: 1.2.7
- URL: https://https://github.com/enen92/screensaver.kaster
v1.2.7
[fix] File extensions in uppercase
[new] Add aura skin font support
=> [screensaver.kaster] 1.2.7

script.module.urllib3/LICENSE.txt, script.module.urllib3/addon.xml, script.module.urllib3/changelog.txt, script.module.urllib3/lib/CHANGES.rst, script.module.urllib3/lib/CONTRIBUTORS.txt, script.module.urllib3/lib/README.rst, script.module.urllib3/lib/urllib3/__init__.py, script.module.urllib3/lib/urllib3/connection.py, script.module.urllib3/lib/urllib3/packages/rfc3986/__init__.py, script.module.urllib3/lib/urllib3/packages/rfc3986/misc.py
* Bump [`urllib3`](https://pypi.org/project/urllib3/) to version 1.25.3. See upstream [`CHANGES.rst`](https://github.com/urllib3/urllib3/blob/1.25.3/CHANGES.rst) for upstream changes.
This update reduced the initiation time when `import`ing the `urllib3` module, which especially affects Kodi users on low‐end platforms like Raspberry Pis. See also https://github.com/xbmc/repo-scripts/pull/1054
=> [script.module.urllib3] 1.25.3

script.module.kodi-six/addon.xml, script.module.kodi-six/libs/kodi_six/utils.py, script.module.kodi-six/libs/kodi_six/xbmc.py, script.module.kodi-six/libs/kodi_six/xbmcaddon.py, script.module.kodi-six/libs/kodi_six/xbmcdrm.py, script.module.kodi-six/libs/kodi_six/xbmcgui.py, script.module.kodi-six/libs/kodi_six/xbmcplugin.py, script.module.kodi-six/libs/kodi_six/xbmcvfs.py
- **General**
- Version number: 0.1.0
- URL: https://https://github.com/romanvm/kodi.six
0.1.0:
0.0.3:
- Added xbmcdrm module.
=> [script.module.kodi-six] 0.1.0

script.module.kodi-six/addon.xml, script.module.kodi-six/libs/kodi_six/utils.py, script.module.kodi-six/libs/kodi_six/xbmc.py, script.module.kodi-six/libs/kodi_six/xbmcaddon.py, script.module.kodi-six/libs/kodi_six/xbmcgui.py, script.module.kodi-six/libs/kodi_six/xbmcplugin.py, script.module.kodi-six/libs/kodi_six/xbmcvfs.py
- **General**
- Version number: 0.0.4
- URL: https://https://github.com/romanvm/kodi.six
0.1.0:
=> [script.module.kodi-six] 0.0.4

script.video.randomtv/README.md, script.video.randomtv/addon.py, script.video.randomtv/addon.xml, script.video.randomtv/resources/language/resource.language.en_gb/strings.po
Updated addon to add context menu to allow the ability to play a specific tv show / season with RandomTV
- [ X ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ X ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md) document
- [ X ] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0
- Kodi …
=> [script.video.randomtv] 1.2.1

screensaver.kaster/addon.xml, screensaver.kaster/resources/language/resource.language.fr_fr/strings.po, screensaver.kaster/resources/lib/screensaver.py, screensaver.kaster/resources/skins/default/1080i/screensaver-kaster.xml
- **General**
- Version number: 1.2.8
- URL: https://https://github.com/enen92/screensaver.kaster
v1.2.8
[new] French translation
[new] Support for box skin fonts
=> [screensaver.kaster] 1.2.8

script.maps.browser/addon.xml
Addon is broken. Unmaintained and doesn't work since Jarvis. Requested by @KarellenX in https://github.com/xbmc/repo-scripts/issues/965. @phil65 please resubmit to higher repository branches if you plan to continue working on this addon. The upcoming web-browser feature of Kodi might help creating an addon with a better UX and easier to maintain.
=> [script.maps.browser] 1.0.1

script.module.cache/addon.xml, script.module.cache/changelog.txt
Just updated the python version to 2.25.0 
see: https://github.com/xbmc/repo-scripts/pull/1115 …
=> [script.module.cache] 1.0.3

script.module.kodi-six/addon.xml, script.module.kodi-six/libs/kodi_six/utils.py
- **General**
- Version number: 0.1.1
0.1.1
- Fixed UnicodeDecodeErrors when Kodi API returns non-UTF-8 byte strings.
0.1.0:
0.0.3:
- Added xbmcdrm module.
=> [script.module.kodi-six] 0.1.1

script.module.kodi-six/addon.xml, script.module.kodi-six/libs/kodi_six/utils.py
- **General**
- Version number: 0.1.2
0.1.2:
- Use different method for Unicode error handling.
0.1.1:
- Fixed UnicodeDecodeErrors when Kodi API returns non-UTF-8 byte strings.
0.1.0:
0.0.3:
- Added xbmcdrm module.
=> [script.module.kodi-six] 0.1.2

service.linuxwhatelse.notify/addon.xml, service.linuxwhatelse.notify/addon/routes/notification.py
Bugfix for windows systems where writing images in non-binary format apparently causes corruption
Provided through [this issue](https://github.com/linuxwhatelse/service.linuxwhatelse.notify/issues/2)
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the …
=> [service.linuxwhatelse.notify] 2.2.2

script.module.kodi-six/addon.xml, script.module.kodi-six/libs/kodi_six/utils.py
- **General**
- Version number: 0.0.5
0.0.5:
- Fixed Unicode decode errors when Kodi API returns non-UTF-8 byte strings.
0.0.4:
=> [script.module.kodi-six] 0.0.5

screensaver.kaster/addon.xml, screensaver.kaster/resources/lib/kodiutils.py, screensaver.kaster/resources/lib/screensaver.py, screensaver.kaster/resources/lib/screensaverutils.py
- **General**
- Version number: 1.3.0
- URL: 
v1.3.0
[new] Trivial python3 fixes
=> [screensaver.kaster] 1.3.0

script.module.arrow/addon.xml
As I needed to push a fix I named this 0.12.2 even if that version does not exist.
=> [script.module.arrow] 0.12.2

script.module.pyxbmct/addon.xml, script.module.pyxbmct/lib/pyxbmct/addonskin.py, script.module.pyxbmct/lib/pyxbmct/addonwindow.py
- **General**
- Add-on name: PyXBMCt
- Add-on ID: script.module.pyxbmct
- Version number: 1.3.1
- URL: https://github.com/romanvm/script.module.pyxbmct
PyXBMCt is a mini-framework for simple XBMC addon UI buliding. It is similar to PyQt and provides parent windows, a number of UI controls (widgets) and a grid layout manager to place controls.
1.3.1:
- Fix incompatibility with newer Python 3 Kodi builds
- Replace future library with six for Python 3 compatibility
=> [script.module.pyxbmct] 1.3.1

script.module.kodi-six/addon.xml, script.module.kodi-six/libs/kodi_six/utils.py
- **General**
- Version number: 0.1.3
0.1.3:
- Fix non-UTF-8 byte string decoding in Python 2.
=> [script.module.kodi-six] 0.1.3

script.module.kodi-six/addon.xml, script.module.kodi-six/libs/kodi_six/utils.py
- **General**
- Version number: 0.0.7
0.0.7:
- Use dict function instead of dictionary comprehension for compatibility with Python 2.6.
0.0.6:
- Replace surrogateescape error handler with replace.
-
=> [script.module.kodi-six] 0.0.7

script.tag-generator/addon.xml
Leia repo generator has been broken for 2 months...
Tag generator includes a clearlogo and points to a jpeg file that doesn't exist. Correct file is has png extension. 
Wondering why addon-checker let this one pass. @Razzeee for reference (I'll look later)
Thanks to @kib for the server support.
Cross-reference: https://github.com/xbmc/repo-scripts/pull/1252
=> [script.tag-generator] Fix broken leia repo generator

service.subtitles.rvm.addic7ed/addic7ed/core.py, service.subtitles.rvm.addic7ed/addic7ed/utils.py, service.subtitles.rvm.addic7ed/addon.xml
- **General**
- Version number: 3.1.2
v.3.1.2:
- Fixed manual search (thanks to [B]quthla[/B].
=> [service.subtitles.rvm.addic7ed] 3.1.2

targets.cfg
the addon repo currently lists both python2 and python 3 addons in Kodi Matrix.
all python 2 addons will ofcourse not work in Matrix, and shouldn't be listed.
this change will make sure only addons with xbmc.python set to 3.0.0 will be listed in the addon manager.
this should be merged once https://github.com/xbmc/xbmc/pull/17188 gets merged.
=> [Matrix] set xbmc.python to 3.0.0

script.audio.mixer/addon.xml, script.audio.mixer/default.py, script.audio.mixer/lib/alsaMixerCore.py, script.audio.mixer/lib/gui.py, script.audio.mixer/lib/osascriptCore.py
not much to see here... mainly getting rid of sys.path.append() 
since we discourage the use of it, we should at least make sure our own addons don't use it. …
=> [script.audio.mixer] 5.1.0

script.module.chardet/addon.xml
=> [script.module.chardet] 3.0.4+matrix.2

script.module.cryptography/addon.xml
=> [script.module.cryptography] 2.8.0+matrix.2

script.module.bottle/addon.xml
=> [script.module.bottle] 0.12.18+matrix.2

script.module.oauthlib/addon.xml
=> [script.module.oauthlib] 3.1.0+matrix.2

script.module.future/addon.xml
=> [script.module.future] 0.17.1+matrix.2

script.module.html5lib/addon.xml
=> [script.module.html5lib] 1.0.1+matrix.2

script.module.six/addon.xml
=> [script.module.six] 1.14.0+matrix.2

script.module.mechanize/addon.xml
=> [script.module.mechanize] 0.4.3+matrix.2

script.module.simplejson/addon.xml
=> [script.module.simplejson] 3.17.0+matrix.2

script.module.oauth2/addon.xml
=> [script.module.oauth2] 1.9.0+matrix.2

script.module.oauth2client/addon.xml
=> [script.module.oauth2client] 4.1.3+matrix.2

script.module.pyamf/addon.xml
=> [script.module.pyamf] 0.8.10+matrix.2

script.module.sgmllib3k/addon.xml
=> [script.module.sgmllib3k] 1.0.0+matrix.2

script.module.pytz/addon.xml
=> [script.module.pytz] 2019.3.0+matrix.2

script.module.pyjwt/addon.xml
=> [script.module.pyjwt] 1.7.1+matrix.2

script.module.pylast/addon.xml
=> [script.module.pylast] 3.2.0+matrix.2

script.module.requests_oauthlib/addon.xml
=> [script.module.requests_oauthlib] 1.3.0+matrix.2

script.module.pymysql/addon.xml
=> [script.module.pymysql] 0.9.3+matrix.2

script.module.trakt/addon.xml
=> [script.module.trakt] 3.1.0+matrix.2

script.module.unidecode/addon.xml
=> [script.module.unidecode] 1.1.1+matrix.2

script.module.uritemplate/addon.xml
=> [script.module.uritemplate] 3.0.1+matrix.2

script.module.feedparser/addon.xml
=> [script.module.feedparser] 6.0.0+matrix.2

script.module.html2text/addon.xml
=> [script.module.html2text] 2020.1.16+matrix.2

script.module.m3u8/addon.xml
=> [script.module.m3u8] 0.5.4+matrix.2

script.module.webencodings/addon.xml
=> [script.module.webencodings] 0.5.1+matrix.2

script.module.yaml/addon.xml
=> [script.module.yaml] 5.3.0+matrix.2

script.module.livestreamer/addon.xml
=> [script.module.livestreamer] 1.12.2+matrix.2

script.module.web-pdb/addon.xml, script.module.web-pdb/main.py, script.module.web-pdb/resources/language/resource.language.en_gb/strings.po
- **General**
- Add-on name: Web-PDB
- Add-on ID: script.module.web-pdb
- Version number: 1.5.4
- URL: https://github.com/romanvm/kodi.web-pdb
Provides a web-UI for Python's built-in PDB debugger for remote debugging Kodi addons.
- 1.5.4: Fix info dialog in Kodi "Matrix".
- 1.5.3: Fix a rare issue when a debugger session cannot be started.
=> [script.module.web-pdb] 1.5.4

script.module.web-pdb/addon.xml, script.module.web-pdb/main.py, script.module.web-pdb/resources/language/resource.language.en_gb/strings.po
- **General**
- Add-on name: Web-PDB
- Add-on ID: script.module.web-pdb
- Version number: 1.5.4+matrix.1
- URL: https://github.com/romanvm/kodi.web-pdb
Provides a web-UI for Python's built-in PDB debugger for remote debugging Kodi addons.
- 1.5.4: Fix info dialog in Kodi "Matrix".
- 1.5.3: Fix a rare issue when a debugger session cannot be started.
=> [script.module.web-pdb@matrix] 1.5.4+matrix.1

script.tubecast/addon.xml
- **General**
- Version number: 1.4.3
[ci] Simplified CI
=> [script.tubecast@krypton] 1.4.3

script.tubecast/addon.xml
- **General**
- Version number: 1.4.3+matrix.1
[ci] Simplified CI
=> [script.tubecast@matrix] 1.4.3+matrix.1

script.module.pymysql/addon.xml
drop the cryptography dependency.
it's an optional dependency (https://github.com/PyMySQL/PyMySQL/blob/master/CHANGELOG#L7), so i don't expect any issues.
=> [script.module.pymysql] 3.1.0+matrix.3

script.module.oauthlib/addon.xml
drop the cryptography dependency.
i've no experience with this addon, but apparently it has always worked fine without it.
we currently have it in jarvis without this dependency.
perhaps only this method will not work without it:
https://github.com/xbmc/repo-scripts/blob/jarvis/script.module.oauthlib/lib/oauthlib/oauth1/rfc5849/signature.py#L581
=> [script.module.oauthlib] 3.1.0+matrix.3

script.tubecast/addon.xml, script.tubecast/resources/language/resource.language.es_es/strings.po, script.tubecast/resources/lib/tubecast/youtube/player.py
- **General**
- Version number: 1.4.4+matrix.1
[new] Add spanish translation (tks roliverosc)
[fix] Playlist doesn't continue after second video (tks NextLight)
=> [script.tubecast@matrix] 1.4.4+matrix.1

script.tubecast/addon.xml, script.tubecast/resources/language/resource.language.es_es/strings.po, script.tubecast/resources/lib/tubecast/youtube/player.py
- **General**
- Version number: 1.4.4
[new] Add spanish translation (tks roliverosc)
[fix] Playlist doesn't continue after second video (tks NextLight)
=> [script.tubecast@krypton] 1.4.4

service.autosubs/addon.xml, service.autosubs/resources/lib/autosubs.py
Fixed issue with ignored Exception settings. There was redundant service-like checking of playing file. Now left only on event 'onPlayBackStarted' …
=> [service.autosubs] 1.1.1

script.module.actionhandler/addon.xml
The fact that this addon (no longer maintained) does not define xbmc.python as a requirement makes it available in the matrix branch. This makes the addon checker to fail while validating the krypton branch because this one has a lower version (and users can't migrate). This PR makes sure it won't be available in matrix.
Found with https://github.com/xbmc/addon-check/pull/234
=> [script.module.actionhandler] 1.0.4

screensaver.qlock/addon.xml, screensaver.qlock/changelog.txt
This is a version bump to screensaver.qlock just to make sure that the addon has a higher version than the one in gotham (that will be bumped to 0.0.5). Reason is that the gotham version does not depend on xbmc.python, making it available in matrix.
Found with https://github.com/xbmc/addon-check/pull/234
@ronie for your information since you were the last one touching this addon
=> [screensaver.qlock] 0.0.6

screensaver.qlock/addon.xml
This makes sure the addon depends on `xbmc.python` to avoid it showing on matrix.
Depends: https://github.com/xbmc/repo-scripts/pull/1520
Found with: https://github.com/xbmc/addon-check/pull/234
=> [screensaver.qlock] 0.0.5

script.module.pyserial/addon.xml
Adds the missing icon to assets.
=> [script.module.pyserial] 3.4.0+matrix.2

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py, script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py, script.module.inputstreamhelper/lib/inputstreamhelper/unicodes.py, script.module.inputstreamhelper/lib/inputstreamhelper/utils.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py, script.module.inputstreamhelper/resources/language/resource.language.de_de/strings.po, script.module.inputstreamhelper/resources/language/resource.language.el_gr/strings.po, script.module.inputstreamhelper/resources/language/resource.language.en_gb/strings.po, script.module.inputstreamhelper/resources/language/resource.language.es_es/strings.po, script.module.inputstreamhelper/resources/language/resource.language.fr_fr/strings.po, script.module.inputstreamhelper/resources/language/resource.language.hr_hr/strings.po, script.module.inputstreamhelper/resources/language/resource.language.hu_hu/strings.po, script.module.inputstreamhelper/resources/language/resource.language.it_it/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ja_JP/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ko_KR/strings.po, script.module.inputstreamhelper/resources/language/resource.language.nl_nl/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ro_ro/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ru_ru/strings.po, script.module.inputstreamhelper/resources/language/resource.language.sv_se/strings.po
- **General**
- Version number: 0.4.7
v0.4.7 (2020-05-03)
- Fix hardlink on Windows
- Fix support for unicode chars in paths
- Show remaining time during Widevine installation on ARM devices
=> [script.module.inputstreamhelper@krypton] 0.4.7

script.kodi.loguploader/addon.xml, script.kodi.loguploader/changelog.txt, script.kodi.loguploader/lib/loguploader.py
paste.kodi.tv now allows file uploads up to 2MB.
this change is needed to make use of the new, increased limit.  …
=> [script.kodi.loguploader] 1.0.3

script.kodi.loguploader/addon.xml, script.kodi.loguploader/changelog.txt, script.kodi.loguploader/default.py
paste.kodi.tv now allows file uploads up to 2MB.
this change is needed to make use of the new, increased limit. …
=> [script.kodi.loguploader] 0.6.0

screensaver.picture.slideshow/addon.xml, screensaver.picture.slideshow/changelog.txt, screensaver.picture.slideshow/lib/gui.py, screensaver.picture.slideshow/lib/utils.py, screensaver.picture.slideshow/resources/skins/default/1080i/script-python-slideshow.xml
changes:
- converted screensaver to 1080p
- improve reading/writing cache file
- add support for more image extensions
- retrieve fanart from the art table …
=> [screensaver.picture.slideshow] 6.3.0

script.module.qrcode/addon.xml
This addon was imported in #1289 and #1407 to matrix from previous Kodi versions (#1171 in isengard). From my assumption for matrix never tested by clean install.
The dependency script.module.pil does not exist in matrix, but is not needed anyway, since it is included in this addon (verified on Ubuntu 18.04). No current maintainer is known to me, therefore the explanation here.
=> [script.module.qrcode] 6.1.0+matrix.3

script.module.codequick/addon.xml, script.module.codequick/lib/codequick/listing.py, script.module.codequick/lib/codequick/support.py, script.module.codequick/lib/codequick/youtube.py, script.module.codequick/lib/urlquick.py
- Attempt fix for 'import _strptime' failure.
- Run method now returns the exception that was raise when error occurs
- 'set_callback' now excepts a path to a callback.
- No need to always import callback modules. Modules are auto loaded based on the specified path.
=> [script.module.codequick] 0.9.12

script.xbmcbackup/addon.xml, script.xbmcbackup/resources/lib/backup.py
Fixes issue where the ```validatePath()``` function was moved from the ```xbmc``` module to the ```xbmcvfs``` module in Matrix.  …
=> [script.xbmcbackup] 1.6.3

screensaver.kaster/addon.xml, screensaver.kaster/entrypoint.py, screensaver.kaster/resources/lib/kodiutils.py, screensaver.kaster/resources/lib/screensaver.py, screensaver.kaster/resources/lib/screensaverutils.py
- **General**
- Version number: 1.3.3+matrix.1
v1.3.3
[fix] CPU usage
[fix] HTTP request number in case of 429 status code
[cosmetic] SPDX headers
=> [screensaver.kaster@matrix] 1.3.3+matrix.1

screensaver.kaster/addon.xml, screensaver.kaster/entrypoint.py, screensaver.kaster/resources/lib/kodiutils.py, screensaver.kaster/resources/lib/screensaver.py, screensaver.kaster/resources/lib/screensaverutils.py
- **General**
- Version number: 1.3.3
v1.3.3
[fix] CPU usage
[fix] HTTP request number in case of 429 status code
[cosmetic] SPDX headers
=> [screensaver.kaster@krypton] 1.3.3

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py, script.module.inputstreamhelper/lib/inputstreamhelper/config.py, script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py, script.module.inputstreamhelper/lib/inputstreamhelper/unicodes.py, script.module.inputstreamhelper/lib/inputstreamhelper/utils.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm_chromeos.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py, script.module.inputstreamhelper/resources/language/resource.language.de_de/strings.po, script.module.inputstreamhelper/resources/language/resource.language.el_gr/strings.po, script.module.inputstreamhelper/resources/language/resource.language.en_gb/strings.po, script.module.inputstreamhelper/resources/language/resource.language.es_es/strings.po, script.module.inputstreamhelper/resources/language/resource.language.fr_fr/strings.po, script.module.inputstreamhelper/resources/language/resource.language.hr_hr/strings.po, script.module.inputstreamhelper/resources/language/resource.language.hu_hu/strings.po, script.module.inputstreamhelper/resources/language/resource.language.it_it/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ja_JP/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ko_KR/strings.po, script.module.inputstreamhelper/resources/language/resource.language.nl_nl/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ro_ro/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ru_ru/strings.po, script.module.inputstreamhelper/resources/language/resource.language.sv_se/strings.po, script.module.inputstreamhelper/resources/settings.xml
- **General**
- Version number: 0.5.0+matrix.1
- Support resuming interrupted downloads on unreliable internet connections
- Reshape InputStream Helper information dialog
- Updated Dutch, English, French, German, Greek, Hungarian, Romanian, Russian, Spanish and …
=> [script.module.inputstreamhelper@matrix] 0.5.0+matrix.1

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py, script.module.inputstreamhelper/lib/inputstreamhelper/config.py, script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py, script.module.inputstreamhelper/lib/inputstreamhelper/unicodes.py, script.module.inputstreamhelper/lib/inputstreamhelper/utils.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm_chromeos.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py, script.module.inputstreamhelper/resources/language/resource.language.de_de/strings.po, script.module.inputstreamhelper/resources/language/resource.language.el_gr/strings.po, script.module.inputstreamhelper/resources/language/resource.language.en_gb/strings.po, script.module.inputstreamhelper/resources/language/resource.language.es_es/strings.po, script.module.inputstreamhelper/resources/language/resource.language.fr_fr/strings.po, script.module.inputstreamhelper/resources/language/resource.language.hr_hr/strings.po, script.module.inputstreamhelper/resources/language/resource.language.hu_hu/strings.po, script.module.inputstreamhelper/resources/language/resource.language.it_it/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ja_JP/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ko_KR/strings.po, script.module.inputstreamhelper/resources/language/resource.language.nl_nl/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ro_ro/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ru_ru/strings.po, script.module.inputstreamhelper/resources/language/resource.language.sv_se/strings.po, script.module.inputstreamhelper/resources/settings.xml
- **General**
- Version number: 0.5.0
- Support resuming interrupted downloads on unreliable internet connections
- Reshape InputStream Helper information dialog
- Updated Dutch, English, French, German, Greek, Hungarian, Romanian, Russian, Spanish and Swedish …
=> [script.module.inputstreamhelper@krypton] 0.5.0

service.subtitles.subsceneplus/addon.xml, service.subtitles.subsceneplus/service.py
This is a hot-fix for a bug introduced in the previous version. The previous version was only tested with TV-Shows and not movies. Sorry for not performing the proper tests.
=> [service.subtitles.subsceneplus] 1.1.23

targets.cfg
Leia skins will not work correctly, due to the GUI Engine changes in Matrix
and/or fail to install due to their dependency on addons that have not been ported to py3.
as requested by @jjd-uk
=> stop listing Leia compatible skins in the Matrix repo

script.module.libarte/addon.xml, script.module.libarte/lib/libarte.py, script.module.libarte/lib/libartewebjsonparser.py
Small touch-ups of my Arte.tv scraper to avoid exceptions when the set language is set to anything but "de" or "fr".
=> [script.module.libarte] 2.0.1

script.trakt/addon.xml, script.trakt/resources/lib/sync.py, script.trakt/resources/lib/syncEpisodes.py, script.trakt/resources/lib/syncMovies.py, script.trakt/resources/lib/traktapi.py
- **General**
- Version number: 3.3.2 …
=> [script.trakt@matrix] 3.3.2

script.module.codequick/addon.xml, script.module.codequick/lib/codequick/__init__.py, script.module.codequick/lib/codequick/listing.py, script.module.codequick/lib/codequick/resolver.py, script.module.codequick/lib/codequick/script.py, script.module.codequick/lib/codequick/search.py, script.module.codequick/lib/codequick/support.py, script.module.codequick/lib/codequick/youtube.py
Mostly prep work for version 1.0.0
- Deprecate the use of class based callbacks.
- Deprecate ability to pass playable url to listitem.set_callback(), use listitem.set_path() instead.
- Deprecate ability to pass a path to a callback when calling listitem.set_callback(), use a callback reference instead.
- Functions that except callbacks can also except a callback reference object. Better for performance.
- Ability to get and set listitem params as attributes, e.g. item.info.genre = "Science Fiction".
- Listitem objects are now fully pickable.
=> [script.module.codequick] 0.9.13

script.service.checkpreviousepisode/README.md, script.service.checkpreviousepisode/addon.xml, script.service.checkpreviousepisode/changelog.txt, script.service.checkpreviousepisode/default.py
- **General**
- Add-on name: Kodi Check Previous Episode
- Add-on ID: script.service.checkpreviousepisode
- Version number: 0.4.2
- URL: https://github.com/bossanova808/script.service.checkpreviousepisode
This service helps prevent spoilers by checking if the previous episode in a series has been watched. If not, it will pause playback and warn you.  Specific shows can be marked to be ignored if episode order does not matter.
Updated for Matrix logging changes (LOGNOTICE -> LOGINFO)
=> [script.service.checkpreviousepisode@matrix] 0.4.2

script.service.next-episode/addon.xml, script.service.next-episode/libs/logger.py
- **General**
- Version number: 1.2.2+matrix.1
1.2.2:
- Replaced deprecated logging level.
1.2.1:
- Fixed library sync when TMDB is used as a TV shows scraper.
- Fixed UI dialogs in Kodi 19 "Matrix".
=> [script.service.next-episode@matrix] 1.2.2+matrix.1

script.tvmaze.scrobbler/addon.xml, script.tvmaze.scrobbler/libs/tvmaze_api.py
- **General**
- Version number: 1.0.1+matrix.1 …
=> [script.tvmaze.scrobbler@matrix] 1.0.1+matrix.1

script.service.next-episode/addon.xml, script.service.next-episode/libs/logger.py
- **General**
- Version number: 1.2.2
1.2.2:
- Replaced deprecated logging level.
1.2.1:
- Fixed library sync when TMDB is used as a TV shows scraper.
- Fixed UI dialogs in Kodi 19 "Matrix".
=> [script.service.next-episode@krypton] 1.2.2

script.tvmaze.scrobbler/addon.xml, script.tvmaze.scrobbler/libs/tvmaze_api.py
- **General**
- Version number: 1.0.1 …
=> [script.tvmaze.scrobbler@leia] 1.0.1

script.service.next-episode/addon.xml, script.service.next-episode/service.py
- **General**
- Version number: 1.2.3+matrix.1
1.2.3:
- Fix broken service.
=> [script.service.next-episode@matrix] 1.2.3+matrix.1

script.metadata.editor/addon.xml, script.metadata.editor/default.py, script.metadata.editor/resources/language/resource.language.es_ES/strings.po, script.metadata.editor/resources/lib/helper.py, script.metadata.editor/resources/lib/nfo_updater.py, script.metadata.editor/resources/lib/rating_updater.py
- **General**
- Add-on name: Metadata Editor
- Add-on ID: script.metadata.editor
- Version number: 3.0.1
- URL: https://github.com/sualfred/script.metadata.editor
Helper script to edit basic metadata information of library items with support to automatically update the .nfo file of movies, TV shows, episodes and music videos.
=> [script.metadata.editor@matrix] 3.0.1

script.metadata.editor/addon.xml, script.metadata.editor/default.py, script.metadata.editor/resources/language/resource.language.es_ES/strings.po, script.metadata.editor/resources/lib/nfo_updater.py
- **General**
- Add-on name: Metadata Editor
- Add-on ID: script.metadata.editor
- Version number: 2.0.9
- URL: https://github.com/sualfred/script.metadata.editor
Helper script to edit basic metadata information of library items with support to automatically update the .nfo file of movies, TV shows, episodes and music videos.
=> [script.metadata.editor@leia] 2.0.9

script.service.next-episode/addon.xml, script.service.next-episode/service.py
- **General**
- Version number: 1.2.3
1.2.3:
- Fix broken service.
=> [script.service.next-episode@krypton] 1.2.3

script.tubecast/README.md, script.tubecast/addon.xml, script.tubecast/resources/language/resource.language.en_gb/strings.po, script.tubecast/resources/language/resource.language.pt_pt/strings.po, script.tubecast/resources/lib/kodi/utils.py, script.tubecast/resources/lib/tubecast/youtube/app.py, script.tubecast/resources/settings.xml
- **General**
- Version number: 1.4.5+matrix.1
[fix] missing ctt key (tks romainreignier)
[fix] add default id if friendlyname is missing
=> [script.tubecast@matrix] 1.4.5+matrix.1

script.tubecast/README.md, script.tubecast/addon.xml, script.tubecast/resources/language/resource.language.en_gb/strings.po, script.tubecast/resources/language/resource.language.pt_pt/strings.po, script.tubecast/resources/lib/kodi/utils.py, script.tubecast/resources/lib/tubecast/youtube/app.py, script.tubecast/resources/settings.xml
- **General**
- Version number: 1.4.5
[fix] missing ctt key (tks romainreignier)
[fix] add default id if friendlyname is missing
=> [script.tubecast@krypton] 1.4.5

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/inputstreamhelper/config.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm_chromeos.py, script.module.inputstreamhelper/resources/language/resource.language.he_il/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ja_jp/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ko_kr/strings.po
- **General**
- Version number: 0.5.1+matrix.1
- Support resuming interrupted downloads on unreliable internet …
=> [script.module.inputstreamhelper@matrix] 0.5.1+matrix.1

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/inputstreamhelper/config.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm_chromeos.py, script.module.inputstreamhelper/resources/language/resource.language.he_il/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ja_jp/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ko_kr/strings.po
- **General**
- Version number: 0.5.1
- Support resuming interrupted downloads on unreliable internet connections
- …
=> [script.module.inputstreamhelper@krypton] 0.5.1

service.sleeptimer/addon.xml, service.sleeptimer/changelog.txt, service.sleeptimer/resources/language/English/strings.po, service.sleeptimer/resources/language/Portuguese/strings.po, service.sleeptimer/resources/settings.xml, service.sleeptimer/service.py
- Sync with upstream
- fix high cpu usage
- avoid using xbmc.sleep for high sleep values
- fix translations
=> [service.sleeptimer] 2.0.7

service.libraryautoupdate/addon.xml, service.libraryautoupdate/manual.py, service.libraryautoupdate/resources/lib/cronclasses.py, service.libraryautoupdate/resources/lib/service.py, service.libraryautoupdate/resources/lib/utils.py
Updated to remove calls to deprecated Python library functions for both ```xbmcgui.Dialog()``` and ```xbmc.translatePath``` …
=> [service.libraryautoupdate] 1.2.1

weather.ozweather/addon.xml, weather.ozweather/changelog.txt, weather.ozweather/resources/lib/common.py, weather.ozweather/resources/lib/forecast.py, weather.ozweather/resources/lib/locations.py
- **General**
- Version number: 1.2.2
Weather forecast data scraped from the Australian Bureau of Meteorology via WeatherZone - www.bom.gov.au and www.weatherzone.com.au.  For full features (e.g. radar) make sure you install the replacement skin files found via the addon wiki (https://kodi.wiki/index.php?title=Add-on:Oz_Weather).
V1.2.2
- Fix for setting of new locations
V1.2.1
- Updated for change in Kodi logging functions (LOGNOTICE -> LOGINFO)
v1.2.0
- Updated for Kodi Matrix and Python 3
=> [weather.ozweather@matrix] 1.2.2

script.embuary.info/addon.xml, script.embuary.info/resources/lib/tmdb.py
- **General**
- Version number: 1.2.7
=> [script.embuary.info@leia] 1.2.7

script.module.simplecache/addon.xml, script.module.simplecache/lib/simplecache.py
- **General**
- Add-on name: Simple Cache Module
- Add-on ID: script.module.simplecache
- Version number: 1.0.20
- URL: https://github.com/sualfred/script.module.simplecache
Provides a simple file- and memory based cache for Kodi addons. Based on the original work of Marcelveldt.
=> [script.module.simplecache@leia] 1.0.20

service.upnext/README.md, service.upnext/addon.xml, service.upnext/resources/language/resource.language.es_es/strings.po, service.upnext/resources/language/resource.language.ro_ro/strings.po, service.upnext/resources/language/resource.language.ru_ru/strings.po, service.upnext/resources/lib/player.py
- **General**
- Version number: 1.1.4+matrix.1
- Fix problem causing pop-up to not appear
- Translation updates to Romanian, Russian and Spanish
- Enable customPlayTime by default
- Do not seek to the end before playing next episode
- Add Kodi v17 compatibility
- Fix logging on Kodi v19 (Matrix) after recent breakage
- Enqueue the next episode in the playlist
- Translation updates to German
- …
=> [service.upnext@matrix] 1.1.4+matrix.1

service.upnext/README.md, service.upnext/addon.xml, service.upnext/resources/language/resource.language.es_es/strings.po, service.upnext/resources/language/resource.language.ro_ro/strings.po, service.upnext/resources/language/resource.language.ru_ru/strings.po, service.upnext/resources/lib/player.py
- **General**
- Version number: 1.1.4
- Fix problem causing pop-up to not appear
- Translation updates to Romanian, Russian and Spanish
- Enable customPlayTime by default
- Do not seek to the end before playing next episode
- Add Kodi v17 compatibility
- Fix logging on Kodi v19 (Matrix) after recent breakage
- Enqueue the next episode in the playlist
- Translation updates to German
- Bug fix for …
=> [service.upnext@leia] 1.1.4

service.iptv.manager/CHANGELOG.md, service.iptv.manager/addon.xml, service.iptv.manager/resources/lib/modules/iptvsimple.py
- **General**
- Add-on name: IPTV Manager
- Add-on ID: service.iptv.manager
- Version number: 0.2.2
- URL: https://github.com/add-ons/service.iptv.manager
This add-on integrates IPTV Channels from other Add-ons in the Kodi PVR.
v0.2.2 (2020-12-07)
- Relax version restriction for IPTV Simple.
- Process credits.
=> [service.iptv.manager@leia] 0.2.2

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/inputstreamhelper/config.py, script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py, script.module.inputstreamhelper/resources/settings.xml
- **General**
- Version number: 0.5.2+matrix.1
- Support …
=> [script.module.inputstreamhelper@matrix] 0.5.2+matrix.1

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/inputstreamhelper/config.py, script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py, script.module.inputstreamhelper/resources/settings.xml
- **General**
- Version number: 0.5.2
- Support resuming …
=> [script.module.inputstreamhelper@krypton] 0.5.2

script.xbmc.unpausejumpback/README.md, script.xbmc.unpausejumpback/addon.xml, script.xbmc.unpausejumpback/changelog.txt, script.xbmc.unpausejumpback/resources/lib/common.py, script.xbmc.unpausejumpback/resources/lib/unpause_jumpback.py
- **General**
- Add-on name: Unpause Jumpback
- Add-on ID: script.xbmc.unpausejumpback
- Version number: 3.0.1
- URL: https://github.com/bossanova808/script.xbmc.unpausejumpback/
This addon will jump back a number of seconds whenever a video is un-paused - to make sure you don't miss anything.
You can set the amount of seconds to jump back, and the minimum duration of the pause before the addon will trigger a jump back.
It also allows to jump back or forward after rewind or fast-forward of a specified amount of seconds to compensate for over-shooting.
(Originally created by Memphiz, up-keep taken over by bossanova808 in 2020 for Kodi Matrix and beyond).
v3.0.1
[fix] minor bugfix for http/s sources (plugins)
v3.0.0
[new] Update for Kodi …
=> [script.xbmc.unpausejumpback@matrix] 3.0.1

service.subtitles.rvm.addic7ed/addic7ed/core.py, service.subtitles.rvm.addic7ed/addic7ed/parser.py, service.subtitles.rvm.addic7ed/addic7ed/webclient.py, service.subtitles.rvm.addic7ed/addon.xml
- **General**
- Version number: 3.1.4+matrix.1
v.3.1.4:
- Fix cleaning a temp download directory.
=> [service.subtitles.rvm.addic7ed@matrix] 3.1.4+matrix.1

service.subtitles.rvm.addic7ed/addic7ed/core.py, service.subtitles.rvm.addic7ed/addic7ed/parser.py, service.subtitles.rvm.addic7ed/addic7ed/webclient.py, service.subtitles.rvm.addic7ed/addon.xml
- **General**
- Version number: 3.1.4
v.3.1.4:
- Fix cleaning a temp download directory.
=> [service.subtitles.rvm.addic7ed@krypton] 3.1.4

script.tubecast/README.md, script.tubecast/addon.xml, script.tubecast/resources/__init__.py, script.tubecast/resources/lib/__init__.py, script.tubecast/resources/lib/kodi/__init__.py, script.tubecast/resources/lib/kodi/kodilogging.py, script.tubecast/resources/lib/kodi/utils.py, script.tubecast/resources/lib/tubecast/__init__.py, script.tubecast/resources/lib/tubecast/kodicast.py, script.tubecast/resources/lib/tubecast/ssdp.py, script.tubecast/resources/lib/tubecast/utils.py, script.tubecast/resources/lib/tubecast/youtube/__init__.py, script.tubecast/resources/lib/tubecast/youtube/app.py, script.tubecast/resources/lib/tubecast/youtube/kodibrigde.py, script.tubecast/resources/lib/tubecast/youtube/pairing.py
- **General**
- Version number: 1.4.6+matrix.0
[new] use tubed instead of youtube
[new] branch based CI strategy
[del] python2 support
=> [script.tubecast@matrix] 1.4.6+matrix.0

screensaver.kaster/addon.xml, screensaver.kaster/changelog.txt, screensaver.kaster/resources/lib/screensaver.py
- **General**
- Version number: 1.3.5+matrix.1
v1.3.5 (23/12/2020)
[fix] Unicode fixes for python3 (tks @roidy)
=> [screensaver.kaster@matrix] 1.3.5+matrix.1

screensaver.kaster/addon.xml, screensaver.kaster/changelog.txt, screensaver.kaster/resources/lib/screensaver.py
- **General**
- Version number: 1.3.5
v1.3.5 (23/12/2020)
[fix] Unicode fixes for python3 (tks @roidy)
=> [screensaver.kaster@krypton] 1.3.5

script.module.kodiswift/addon.xml, script.module.kodiswift/changelog.txt
- Fixed the error in not importing python six library in addon.xml in version 0.0.9 (got an error report from a user).
- Give more details in changelog.
=> [script.module.kodiswift] 0.0.10

script.tvmaze.scrobbler/addon.xml, script.tvmaze.scrobbler/libs/exception_logger.py, script.tvmaze.scrobbler/libs/gui.py, script.tvmaze.scrobbler/libs/kodi_monitor.py, script.tvmaze.scrobbler/libs/kodi_service.py, script.tvmaze.scrobbler/libs/scheduled_tasks.py, script.tvmaze.scrobbler/libs/time_utils.py, script.tvmaze.scrobbler/resources/language/resource.language.en_gb/strings.po, script.tvmaze.scrobbler/resources/settings.xml, script.tvmaze.scrobbler/script.py, script.tvmaze.scrobbler/service.py
- **General**
- Version number: 1.1.0+matrix.1 …
=> [script.tvmaze.scrobbler@matrix] 1.1.0+matrix.1

service.iptv.manager/CHANGELOG.md, service.iptv.manager/addon.xml, service.iptv.manager/resources/language/resource.language.el_gr/strings.po, service.iptv.manager/resources/language/resource.language.en_gb/strings.po, service.iptv.manager/resources/language/resource.language.hu_hu/strings.po, service.iptv.manager/resources/language/resource.language.nl_nl/strings.po, service.iptv.manager/resources/language/resource.language.ro_ro/strings.po, service.iptv.manager/resources/lib/functions.py, service.iptv.manager/resources/lib/kodilogging.py, service.iptv.manager/resources/lib/kodiutils.py, service.iptv.manager/resources/lib/modules/addon.py, service.iptv.manager/resources/lib/modules/iptvsimple.py, service.iptv.manager/resources/lib/service.py, service.iptv.manager/resources/settings.xml
- **General**
- Add-on name: IPTV Manager
- Add-on ID: service.iptv.manager
- Version number: 0.2.3+matrix.1
- URL: https://github.com/add-ons/service.iptv.manager
IPTV Manager integrates IPTV channels from other add-ons in the Kodi TV and Radio menus.
v0.2.3 (2021-02-04)
- Allow to process raw m3u8 or xmltv data.
- Add support for #KODIPROP.
- Support multiple groups for a channel.
- Improvements for Kodi Matrix.
- Update translations.
=> [service.iptv.manager@matrix] 0.2.3+matrix.1

service.iptv.manager/CHANGELOG.md, service.iptv.manager/addon.xml, service.iptv.manager/resources/language/resource.language.el_gr/strings.po, service.iptv.manager/resources/language/resource.language.en_gb/strings.po, service.iptv.manager/resources/language/resource.language.hu_hu/strings.po, service.iptv.manager/resources/language/resource.language.nl_nl/strings.po, service.iptv.manager/resources/language/resource.language.ro_ro/strings.po, service.iptv.manager/resources/lib/functions.py, service.iptv.manager/resources/lib/kodilogging.py, service.iptv.manager/resources/lib/kodiutils.py, service.iptv.manager/resources/lib/modules/addon.py, service.iptv.manager/resources/lib/modules/iptvsimple.py, service.iptv.manager/resources/lib/service.py, service.iptv.manager/resources/settings.xml
- **General**
- Add-on name: IPTV Manager
- Add-on ID: service.iptv.manager
- Version number: 0.2.3
- URL: https://github.com/add-ons/service.iptv.manager
IPTV Manager integrates IPTV channels from other add-ons in the Kodi TV and Radio menus.
v0.2.3 (2021-02-04)
- Allow to process raw m3u8 or xmltv data.
- Add support for #KODIPROP.
- Support multiple groups for a channel.
- Improvements for Kodi Matrix.
- Update translations.
=> [service.iptv.manager@leia] 0.2.3

script.tvmaze.scrobbler/addon.xml, script.tvmaze.scrobbler/libs/exception_logger.py, script.tvmaze.scrobbler/libs/gui.py, script.tvmaze.scrobbler/libs/kodi_monitor.py, script.tvmaze.scrobbler/libs/kodi_service.py, script.tvmaze.scrobbler/libs/scheduled_tasks.py, script.tvmaze.scrobbler/libs/time_utils.py, script.tvmaze.scrobbler/resources/language/resource.language.en_gb/strings.po, script.tvmaze.scrobbler/resources/settings.xml, script.tvmaze.scrobbler/script.py, script.tvmaze.scrobbler/service.py
- **General**
- Version number: 1.1.0 …
=> [script.tvmaze.scrobbler@leia] 1.1.0

service.upnext/README.md, service.upnext/addon.xml, service.upnext/resources/language/resource.language.fi_fi/strings.po, service.upnext/resources/lib/api.py, service.upnext/resources/lib/playbackmanager.py, service.upnext/resources/lib/player.py, service.upnext/resources/lib/playitem.py, service.upnext/resources/lib/state.py, service.upnext/resources/lib/utils.py
- **General**
- Version number: 1.1.5+matrix.1
v1.1.5 (2021-02-21)
- Fix playlists to work with non-library content
- Fix to prevent unwanted playback when using playlist queueing method
- New translation for Finnish
v1.1.4 (2020-12-03)
- Fix problem causing pop-up to not appear
- Translation updates to Romanian, Russian and Spanish
v1.1.3 (2020-10-14)
- Enable customPlayTime by default
- Do not …
=> [service.upnext@matrix] 1.1.5+matrix.1

service.upnext/README.md, service.upnext/addon.xml, service.upnext/resources/language/resource.language.fi_fi/strings.po, service.upnext/resources/lib/api.py, service.upnext/resources/lib/playbackmanager.py, service.upnext/resources/lib/player.py, service.upnext/resources/lib/playitem.py, service.upnext/resources/lib/state.py, service.upnext/resources/lib/utils.py
- **General**
- Version number: 1.1.5
v1.1.5 (2021-02-21)
- Fix playlists to work with non-library content
- Fix to prevent unwanted playback when using playlist queueing method
- New translation for Finnish
v1.1.4 (2020-12-03)
- Fix problem causing pop-up to not appear
- Translation updates to Romanian, Russian and Spanish
v1.1.3 (2020-10-14)
- Enable customPlayTime by default
- Do not seek to …
=> [service.upnext@leia] 1.1.5

script.trakt/HOW_TO_RELEASE.md, script.trakt/addon.xml, script.trakt/resources/lib/syncEpisodes.py, script.trakt/resources/lib/syncMovies.py
- **General**
- Version number: 3.3.4 …
=> [script.trakt@matrix] 3.3.4

script.trakt/addon.xml, script.trakt/resources/lib/syncMovies.py
- **General**
- Version number: 3.3.5 …
=> [script.trakt@matrix] 3.3.5

service.subtitles.napisy24pl/addon.xml, service.subtitles.napisy24pl/resources/lib/NapisyUtils.py, service.subtitles.napisy24pl/service.py
This PR has fixes filesystem handling in the plugin due to changes in Kodi 19 final
1. use `zip://` protocol instead of `xbmc.executebuiltin(('XBMC.Extract("%s","%s")' % (zip_filename, __temp__,)), True)`
1. Instead of deleting `temp` using `shutil` it deletes all the files in it with `xbmcfs.delete`
=> [service.subtitles.napisy24pl] 3.0.3

weather.multi/addon.xml, weather.multi/changelog.txt, weather.multi/lib/utils.py, weather.multi/lib/weather.py
the addon is currently broken due to changes made by yahoo (they started checking user-agent as of today).
this update fixes that issue. …
=> [weather.multi] 0.0.6

script.trakt/addon.xml, script.trakt/resources/lib/syncEpisodes.py
- **General**
- Version number: 3.4.1 …
=> [script.trakt@matrix] 3.4.1

script.xbmcbackup/addon.xml, script.xbmcbackup/resources/lib/backup.py, script.xbmcbackup/resources/lib/vfs.py
Fixed issue major issue where backup rotation setting wasn't working with Matrix, needed to add ```force=True``` flag to ```rmdir()``` call.  …
=> [script.xbmcbackup] 1.6.6

service.subtitles.rvm.addic7ed/addic7ed/actions.py, service.subtitles.rvm.addic7ed/addon.xml, service.subtitles.rvm.addic7ed/main.py
- **General**
- Version number: 3.1.5+matrix.1
v.3.1.5:
- Fixed a crash when downloading subs for the first time after installing the addon.
v.3.1.4:
- Fix cleaning a temp download directory.
=> [service.subtitles.rvm.addic7ed@matrix] 3.1.5+matrix.1

script.tvmaze.scrobbler/addon.xml, script.tvmaze.scrobbler/libs/exception_logger.py, script.tvmaze.scrobbler/libs/medialibrary_api.py, script.tvmaze.scrobbler/libs/pulled_episodes_db.py, script.tvmaze.scrobbler/libs/scrobbling_service.py, script.tvmaze.scrobbler/libs/tvmaze_api.py
- **General**
- Version number: 1.1.1+matrix.1 …
=> [script.tvmaze.scrobbler@matrix] 1.1.1+matrix.1

service.subtitles.rvm.addic7ed/addic7ed/actions.py, service.subtitles.rvm.addic7ed/addon.xml, service.subtitles.rvm.addic7ed/main.py
- **General**
- Version number: 3.1.5
v.3.1.5:
- Fixed a crash when downloading subs for the first time after installing the addon.
v.3.1.4:
- Fix cleaning a temp download directory.
=> [service.subtitles.rvm.addic7ed@krypton] 3.1.5

script.tvmaze.scrobbler/addon.xml, script.tvmaze.scrobbler/libs/exception_logger.py, script.tvmaze.scrobbler/libs/medialibrary_api.py, script.tvmaze.scrobbler/libs/pulled_episodes_db.py, script.tvmaze.scrobbler/libs/scrobbling_service.py, script.tvmaze.scrobbler/libs/tvmaze_api.py
- **General**
- Version number: 1.1.1 …
=> [script.tvmaze.scrobbler@leia] 1.1.1

service.libraryautoupdate/addon.xml, service.libraryautoupdate/edit_custom_paths.py, service.libraryautoupdate/resources/language/resource.language.en_gb/strings.po, service.libraryautoupdate/resources/settings.xml
Updated the ```settings.xml``` to the new format. Also fixed issues with ```xbmcgui.Dialog()``` calls that used the old line1, line2 arguments.  …
=> [service.libraryautoupdate] 1.2.2

script.logviewer/addon.xml, script.logviewer/resources/lib/logviewer.py
- **General**
- Version number: 2.1.5+matrix.1
- URL: https://github.com/i96751414/script.logviewer
- Move xbmc.translatePath to xbmcvfs.translatePath (removed in v20)
=> [script.logviewer@matrix] 2.1.5+matrix.1

script.tvmaze.scrobbler/addon.xml, script.tvmaze.scrobbler/libs/kodi_monitor.py, script.tvmaze.scrobbler/resources/language/resource.language.en_gb/strings.po, script.tvmaze.scrobbler/resources/settings.xml
- **General**
- Version number: 1.2.0+matrix.1 …
=> [script.tvmaze.scrobbler@matrix] 1.2.0+matrix.1

script.tvmaze.scrobbler/addon.xml, script.tvmaze.scrobbler/libs/kodi_monitor.py, script.tvmaze.scrobbler/resources/language/resource.language.en_gb/strings.po, script.tvmaze.scrobbler/resources/settings.xml
- **General**
- Version number: 1.2.0 …
=> [script.tvmaze.scrobbler@leia] 1.2.0

script.xbmc.lcdproc/addon.xml, script.xbmc.lcdproc/changelog.txt, script.xbmc.lcdproc/resources/lib/lcdbase.py
Fixes compatibility with Python 3.9+
The lcd.xml parser still used the getiterator method, which seems to be deprecated since Python 2.7, but was finally dropped in 3.9.
=> [script.xbmc.lcdproc] 3.90.2

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py, script.module.inputstreamhelper/lib/inputstreamhelper/config.py, script.module.inputstreamhelper/lib/inputstreamhelper/utils.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm_chromeos.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py
- **General**
- Version number: 0.5.3
- Extract Widevine CDM directly from Chrome OS, minimizing disk space usage and …
=> [script.module.inputstreamhelper@krypton] 0.5.3

script.module.websocket/addon.xml, script.module.websocket/lib/websocket/_abnf.py
- disable use of numpy with Python3 (corrects an issue with Kodi crashing on certain platforms)
This is a non-upstream patch particularly for Kodi, so I'll have to reapply it whenever there is a module update, at least until we confirm that numpy is not causing Kodi crashes on certain platforms.
=> [script.module.websocket] 0.58.0+matrix.2

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/inputstreamhelper/config.py, script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py, script.module.inputstreamhelper/resources/language/resource.language.en_gb/strings.po
- **General**
- Version number: 0.5.4
- Extract …
=> [script.module.inputstreamhelper@krypton] 0.5.4

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py
- **General**
- Version number: 0.5.5+matrix.1
- …
=> [script.module.inputstreamhelper@matrix] 0.5.5+matrix.1

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py
- **General**
- Version number: 0.5.5
- Updated …
=> [script.module.inputstreamhelper@krypton] 0.5.5

script.tvmaze.scrobbler/addon.xml, script.tvmaze.scrobbler/libs/kodi_service.py
- **General**
- Version number: 1.2.1+matrix.1 …
=> [script.tvmaze.scrobbler@matrix] 1.2.1+matrix.1

service.subtitles.rvm.addic7ed/addic7ed/actions.py, service.subtitles.rvm.addic7ed/addic7ed/addon.py, service.subtitles.rvm.addic7ed/addic7ed/utils.py, service.subtitles.rvm.addic7ed/addic7ed/webclient.py, service.subtitles.rvm.addic7ed/addon.xml
- **General**
- Version number: 3.1.6+matrix.1
3.1.6:
- Various internal changes.
3.1.5:
- Fixed a crash when downloading subs for the first time after installing the addon.
=> [service.subtitles.rvm.addic7ed@matrix] 3.1.6+matrix.1

service.libraryautoupdate/addon.xml, service.libraryautoupdate/resources/lib/service.py
Since update to new settings format the hourly time selection drop down was not working properly, added fix.  …
=> [service.libraryautoupdate] 1.2.3

script.tvmaze.scrobbler/addon.xml, script.tvmaze.scrobbler/libs/kodi_service.py
- **General**
- Version number: 1.2.1 …
=> [script.tvmaze.scrobbler@leia] 1.2.1

service.subtitles.rvm.addic7ed/addic7ed/actions.py, service.subtitles.rvm.addic7ed/addic7ed/addon.py, service.subtitles.rvm.addic7ed/addic7ed/utils.py, service.subtitles.rvm.addic7ed/addic7ed/webclient.py, service.subtitles.rvm.addic7ed/addon.xml
- **General**
- Version number: 3.1.6
3.1.6:
- Various internal changes.
3.1.5:
- Fixed a crash when downloading subs for the first time after installing the addon.
=> [service.subtitles.rvm.addic7ed@krypton] 3.1.6

script.service.next-episode/addon.xml, script.service.next-episode/libs/addon.py, script.service.next-episode/libs/exception_logger.py, script.service.next-episode/main.py, script.service.next-episode/service.py
- **General**
- Version number: 1.2.4+matrix.1
1.2.4:
=> [script.service.next-episode@matrix] 1.2.4+matrix.1

script.xbmc.unpausejumpback/README.md, script.xbmc.unpausejumpback/addon.xml, script.xbmc.unpausejumpback/changelog.txt, script.xbmc.unpausejumpback/resources/lib/common.py, script.xbmc.unpausejumpback/resources/lib/unpause_jumpback.py
- **General**
- Add-on name: Unpause Jumpback
- Add-on ID: script.xbmc.unpausejumpback
- Version number: 3.0.2
- URL: https://github.com/bossanova808/script.xbmc.unpausejumpback/
This addon will jump back a number of seconds whenever a video is un-paused - to make sure you don't miss anything.
You can set the amount of seconds to jump back, and the minimum duration of the pause before the addon will trigger a jump back.
It also allows to jump back or forward after rewind or fast-forward of a specified amount of seconds to compensate for over-shooting.
(Originally created by Memphiz, up-keep taken over by bossanova808 in 2020 for Kodi Matrix and beyond).
v3.0.2
[fix] "Kodi is not playing any media file" errors
Basically if a user skips …
=> [script.xbmc.unpausejumpback@matrix] 3.0.2

weather.ozweather/addon.xml, weather.ozweather/changelog.txt, weather.ozweather/resources/lib/bom/bom_forecast.py, weather.ozweather/resources/lib/common.py, weather.ozweather/resources/lib/forecast.py, weather.ozweather/resources/lib/weatherzone/weatherzone_forecast.py
- **General**
- Version number: 2.0.1
v2.01
- Tweaks to cope with some BOM weather stations that return incomplete data
v2.0.0
- N.B. If you have run a version before 2.0, please re-configure the addon to set-up your new BOM locations
- Rewrite to use BOM API directly, leave Weatherzone in as a fallback option. if BOM not configured or …
=> [weather.ozweather@matrix] 2.0.1

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py, script.module.inputstreamhelper/lib/inputstreamhelper/config.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py, script.module.inputstreamhelper/resources/language/resource.language.en_gb/strings.po, script.module.inputstreamhelper/resources/settings.xml
- **General**
- Version number: 0.5.6+matrix.1
- Update Chrome OS ARM hardware …
=> [script.module.inputstreamhelper@matrix] 0.5.6+matrix.1

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py, script.module.inputstreamhelper/lib/inputstreamhelper/config.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py, script.module.inputstreamhelper/resources/language/resource.language.en_gb/strings.po, script.module.inputstreamhelper/resources/settings.xml
- **General**
- Version number: 0.5.6 …
=> [script.module.inputstreamhelper@krypton] 0.5.6

script.service.next-episode/addon.xml, script.service.next-episode/libs/addon.py, script.service.next-episode/libs/exception_logger.py, script.service.next-episode/main.py, script.service.next-episode/service.py
- **General**
- Version number: 1.2.4
1.2.4:
=> [script.service.next-episode@krypton] 1.2.4

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py
- **General**
- Version number: 0.5.7+matrix.1
v0.5.7 (2021-07-02)
- Further improve Widevine CDM installation on ARM hardware
v0.5.6 (2021-06-24)
- …
=> [script.module.inputstreamhelper@matrix] 0.5.7+matrix.1

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py
- **General**
- Version number: 0.5.7
v0.5.7 (2021-07-02)
- Further improve Widevine CDM installation on ARM hardware
v0.5.6 (2021-06-24)
- Fix …
=> [script.module.inputstreamhelper@krypton] 0.5.7

script.common.plugin.cache/addon.xml, script.common.plugin.cache/resources/language/resource.language.en_gb/strings.po, script.common.plugin.cache/resources/lib/storage_server/StorageServer.py
- **General**
- Add-on name: Common plugin cache
- Add-on ID: script.common.plugin.cache
- Version number: 2.6.3+matrix.1
- URL: https://github.com/anxdpanic/script.common.plugin.cache
A common caching API for Kodi add-ons.
[fix] use xbmcvfs.translatePath when available, xbmc.translatePath deprecated(Matrix) and removed(Nexus) |contrib: Gujal00|
=> [script.common.plugin.cache@matrix] 2.6.3+matrix.1

script.common.plugin.cache/addon.xml, script.common.plugin.cache/changelog.txt, script.common.plugin.cache/resources/language/resource.language.en_gb/strings.po, script.common.plugin.cache/resources/lib/storage_server/StorageServer.py
- **General**
- Add-on name: Common plugin cache
- Add-on ID: script.common.plugin.cache
- Version number: 2.6.3
- Kodi/repository version: jarvis
- URL: https://github.com/anxdpanic/script.common.plugin.cache
A common caching API for Kodi add-ons.
[fix] use xbmcvfs.translatePath when available, xbmc.translatePath deprecated(Matrix) and removed(Nexus) |contrib: Gujal00|
=> [script.common.plugin.cache@jarvis] 2.6.3

service.watchedlist/addon.xml, service.watchedlist/changelog.txt, service.watchedlist/lib/watchedlist/utils.py, service.watchedlist/lib/watchedlist/watchedlist.py
Fix for [changed interface of xbmc.translatePath()](https://forum.kodi.tv/showthread.php?tid=344263&pid=2975581#pid2975581).
This fix is not necessary in Kodi 19, but is needed for Kodi 20.
No change of functionality.
=> [service.watchedlist] 1.3.3

service.subtitles.rvm.addic7ed/addic7ed/utils.py, service.subtitles.rvm.addic7ed/addon.xml
- **General**
- Version number: 3.1.7+matrix.1
3.1.7
- Fixed crashes when playing non-medialibrary items.
3.1.6:
- Various internal changes.
=> [service.subtitles.rvm.addic7ed@matrix] 3.1.7+matrix.1

service.subtitles.rvm.addic7ed/addic7ed/utils.py, service.subtitles.rvm.addic7ed/addon.xml
- **General**
- Version number: 3.1.7
3.1.7
- Fixed crashes when playing non-medialibrary items.
3.1.6:
- Various internal changes.
=> [service.subtitles.rvm.addic7ed@krypton] 3.1.7

script.service.next-episode/addon.xml, script.service.next-episode/libs/medialibrary.py, script.service.next-episode/libs/nextepisode.py, script.service.next-episode/libs/utils.py
- **General**
- Version number: 1.2.5
1.2.5:
- Fixed crashes when movies do not have IMDB ID.
1.2.4:
=> [script.service.next-episode@krypton] 1.2.5

script.tubecast/README.md, script.tubecast/addon.xml, script.tubecast/resources/language/resource.language.en_gb/strings.po, script.tubecast/resources/language/resource.language.pt_pt/strings.po, script.tubecast/resources/language/resource.language.ru_ru/strings.po, script.tubecast/resources/lib/tubecast/youtube/app.py, script.tubecast/resources/lib/tubecast/youtube/kodibrigde.py, script.tubecast/resources/settings.xml
- **General**
- Version number: 1.4.7+matrix.1
[fix] Fix cast with new youtube app (tks @ivanich @Chalanxe @patrickkfkan)
[fix] Bump requirements
[new] Added translation support via weblate
[new] russian translation (tks @DimmKG)
[new] Add setting to allow the use of youtube instead of tubed
=> [script.tubecast@matrix] 1.4.7+matrix.1

script.tubecast/addon.xml, script.tubecast/resources/language/resource.language.ru_ru/strings.po, script.tubecast/resources/lib/tubecast/youtube/app.py
- **General**
- Version number: 1.4.6
[fix] Fix cast with new youtube app (tks @ivanich @Chalanxe @patrickkfkan)
[new] russian translation (tks @DimmKG)
=> [script.tubecast@krypton] 1.4.6

script.service.playbackresumer/addon.xml, script.service.playbackresumer/changelog.txt, script.service.playbackresumer/resources/lib/player.py, script.service.playbackresumer/resources/lib/store.py
- **General**
- Add-on name: Kodi Playback Resumer
- Add-on ID: script.service.playbackresumer
- Version number: 2.0.3
- URL: https://github.com/bossanova808/script.service.playbackresumer
Runs as a service and will periodically update the resume point while videos are playing, so you can re-start from where you were in the event of a crash.  It can also automatically resume a video if Kodi was shutdown while playing it. See setting to configure how often the resume point is set, and whether to automatically resume.
v2.0.3
- Bug fix for playing non-library videos
- Use common code, better logging
v2.0.2
- Complete re-write into more modular, modern Python 3
- Add support for advancedsettings ignoresecondsatstart and ignorepercentatend …
=> [script.service.playbackresumer@matrix] 2.0.3

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py, script.module.inputstreamhelper/lib/inputstreamhelper/config.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py, script.module.inputstreamhelper/resources/language/resource.language.en_gb/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ja_jp/strings.po, script.module.inputstreamhelper/resources/language/resource.language.ko_kr/strings.po
- **General**
- Version number: 0.5.8
v0.5.8 (2021-09-09)
- Simplify Widevine CDM installation on ARM hardware
- Update Japanese and Korean translations
v0.5.7 (2021-07-02)
- Further improve Widevine CDM installation on ARM hardware
v0.5.6 (2021-06-24)
v0.5.4 …
=> [script.module.inputstreamhelper@krypton] 0.5.8

script.timers/addon.py, script.timers/addon.xml, script.timers/program.py, script.timers/resources/settings.xml
Bugfix: actions in settings dialog don't work, i.e. 'reset volume' and 'play now'
=> [script.timers] 2.0.1

screensaver.kaster/addon.xml, screensaver.kaster/changelog.txt, screensaver.kaster/resources/lib/screensaver.py, screensaver.kaster/resources/settings.xml
- **General**
- Version number: 1.3.6+matrix.1
v1.3.6 (21/09/2021)
[fix] line2 does not get cleared with user photos (tks @fuse314)
[fix] allow pictures folder to be read-only (tks @fuse314)
=> [screensaver.kaster@matrix] 1.3.6+matrix.1

screensaver.kaster/addon.xml, screensaver.kaster/changelog.txt, screensaver.kaster/resources/lib/screensaver.py, screensaver.kaster/resources/settings.xml
- **General**
- Version number: 1.3.6
v1.3.6 (21/09/2021)
[fix] line2 does not get cleared with user photos (tks @fuse314)
[fix] allow pictures folder to be read-only (tks @fuse314)
=> [screensaver.kaster@krypton] 1.3.6

script.timers/addon.xml, script.timers/resources/lib/timer/scheduler.py, script.timers/resources/lib/timer/util.py
v2.0.3 (2021-10-31)
- Fixed issue related to reset to default settings after one-time timers has finished
- Fixed issue that wrong pvr channel was taken from epg if some channels are deactivated in PVR
- Fixed key error after deactivating timer 
- removed __init__.py files since not required in Python 3 anymore
=> [script.timers] 2.0.3

script.xbmc.unpausejumpback/addon.xml, script.xbmc.unpausejumpback/changelog.txt, script.xbmc.unpausejumpback/resources/lib/common.py, script.xbmc.unpausejumpback/resources/lib/unpause_jumpback.py
- **General**
- Add-on name: Unpause Jumpback
- Add-on ID: script.xbmc.unpausejumpback
- Version number: 3.0.3
- URL: https://github.com/bossanova808/script.xbmc.unpausejumpback/
This addon will jump back a number of seconds whenever a video is un-paused - to make sure you don't miss anything.
You can set the amount of seconds to jump back, and the minimum duration of the pause before the addon will trigger a jump back.
It also allows to jump back or forward after rewind or fast-forward of a specified amount of seconds to compensate for over-shooting.
(Originally created by Memphiz, up-keep taken over by bossanova808 in 2020 for Kodi Matrix and beyond).
v3.0.3
- Minor bugfix for http/s sources
=> [script.xbmc.unpausejumpback@matrix] 3.0.3

script.module.xbmcswift2/addon.xml, script.module.xbmcswift2/lib/xbmcswift2/storage.py
- **General**
- Version number: 19.0.7
Fixes for python 3.10 - move collections.MutableMapping to collections.abc.MutableMapping
=> [script.module.xbmcswift2@matrix] 19.0.7

script.timers/addon.py, script.timers/addon.xml, script.timers/context_setquickepgtimer.py, script.timers/program.py, script.timers/resources/language/resource.language.de_de/strings.po, script.timers/resources/language/resource.language.en_gb/strings.po, script.timers/resources/lib/timer/abstract_set_timer.py, script.timers/resources/lib/timer/scheduler.py, script.timers/resources/lib/timer/set_quick_epg_timer.py, script.timers/resources/lib/timer/set_sleep.py, script.timers/resources/lib/timer/set_snooze.py, script.timers/resources/lib/timer/set_timer.py, script.timers/resources/lib/timer/timer.py, script.timers/resources/lib/timer/util.py, script.timers/resources/settings.xml
v2.1.0 (2021-11-20):
- Improved start and stop action in case that multiple timers are running in parallel, see also https://github.com/Heckie75/kodi-addon-timers/issues/5 
- One-click-setup from epg (Quick Timer)
- Improved procedure of update state after one-time-timers have run out or settings have been changed
- Added 5 more timer slots
- Added feature in order to prevent that display is turned off if Kodi idles but is not in fullscreen mode
- Migrated to new XML settings format
- Major refactoring, better structured code
=> [script.timers] 2.1.0

script.radioparadise/CHANGELOG.md, script.radioparadise/README.md, script.radioparadise/addon.xml, script.radioparadise/script.py
Add script parameter for playing a particular Radio Paradise stream directly. …
=> [script.radioparadise] 1.0.3

service.autostop/README.md, service.autostop/addon.xml, service.autostop/changelog.txt, service.autostop/service.py
Description
v1.0.1 - Fixed exception bug which could occur if Kodi stopped playing a file 
at exactly the same time the addon attempted to stop playback.
This is a simple Kodi service addon which monitors video and music playback. It allows users
to selectively stop paused or current playback after a certain amount of time.
Checklist:
Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0
Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
add-on development wiki page.
Kodi pydocs provide information about the Python API
PEP8 codingstyle which is considered best practise but not mandatory.
This add-on …
=> [service.autostop] 1.0.1

script.service.checkpreviousepisode/addon.xml, script.service.checkpreviousepisode/changelog.txt, script.service.checkpreviousepisode/resources/lib/check_previous_episode.py, script.service.checkpreviousepisode/resources/lib/player.py, script.service.checkpreviousepisode/resources/lib/store.py
- **General**
- Add-on name: Kodi Check Previous Episode
- Add-on ID: script.service.checkpreviousepisode
- Version number: 0.4.5
- URL: https://github.com/bossanova808/script.service.checkpreviousepisode
This service helps prevent spoilers by checking if the previous episode in a series has been watched. If not, it will pause playback and warn you.  Specific shows can be marked to be ignored if episode order does not matter.
v0.4.5
- Fix logic of ignore if previous episode not actually in library
=> [script.service.checkpreviousepisode@matrix] 0.4.5

script.module.tubed.api/addon.xml, script.module.tubed.api/resources/lib/src/tubed_api/usher/lib/mpeg_dash.py, script.module.tubed.api/resources/lib/src/tubed_api/usher/lib/video_info.py
- **General**
- Add-on name: Tubed API
- Add-on ID: script.module.tubed.api
- Version number: 1.0.12
- URL: https://github.com/anxdpanic/script.module.tubed.api
The Tubed API module provides a convenient way to access YouTube's Data API in Kodi 19+
- fixup for age-gated material
- fixup issue with mpd generation
=> [script.module.tubed.api@matrix] 1.0.12

service.autostop/addon.xml, service.autostop/changelog.txt, service.autostop/service.py
Updated Kodi Matrix addon service.autostop v1.0.4.
This update has the following fix:
- Fixed a bug where the sleep timer could execute prematurely
when calling timer change via keyboard.xml or favourites.xml
due to playcount timer running when the sleep timer was set
to 0. 
[X ] My code follows the add-on rules and piracy stance of this project.
[X ] I have read the CONTRIBUTING document
[X ] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0
- Kodi …
=> [service.autostop] 1.0.4

script.playrandomvideos/addon.xml, script.playrandomvideos/changelog.txt, script.playrandomvideos/python/lib/listitembuilder.py, script.playrandomvideos/python/lib/playrandom.py, script.playrandomvideos/python/lib/pykodi.py, script.playrandomvideos/python/lib/quickjson.py, script.playrandomvideos/resources/language/resource.language.en_gb/strings.po, script.playrandomvideos/resources/settings.xml
- **General**
- Add-on name: Play Random Videos
- Add-on ID: script.playrandomvideos
- Version number: 2.1.0
- URL: https://github.com/rmrector/script.playrandomvideos
This add-on can quickly play random episodes from TV shows, movies from genres/sets/years/tags, and videos from playlists, the filesystem, and just about anything else, other than plugins.
v2.1.0 (2022-02-20)
- Feature: option to filter out recently played videos
- Feature: add more metadata to playlist items
v2.0.0 (2021-01-29)
- Kodi 19 Matrix / Python 3 compatibility. Breaks compatibility with previous versions of Kodi.
=> [script.playrandomvideos@matrix] 2.1.0

service.autostop/addon.xml, service.autostop/changelog.txt, service.autostop/common.py, service.autostop/resources/language/resource.language.en_gb/strings.po, service.autostop/resources/settings.xml, service.autostop/service.py, service.autostop/utilities.py
Autostop v1.0.5 update.  Includes the following changes:
- Added 300 and 600 second options for playback stop notification.
- Added check to ensure both playback stop and notification timers 
aren't set to 10 minutes creating a logic loop and instant 
notification on playback start. 
- Added Autostop addon icon to notification messages for easier
identification.
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is …
=> [service.autostop] 1.0.5

script.module.qhue/CHANGELOG.md, script.module.qhue/LICENSE, script.module.qhue/README-remote.md, script.module.qhue/README.md, script.module.qhue/addon.xml, script.module.qhue/lib/__init__.py, script.module.qhue/lib/oauth_receiver.py, script.module.qhue/lib/qhue.py, script.module.qhue/lib/qhue_remote.py
- **General**
- Add-on name: qhue
- Add-on ID: script.module.qhue
- Version number: 2.0.1
- Original Module URL: https://github.com/quentinsf/qhue
- Package location: https://github.com/zim514/script.module.qhue
A very lightweight Python wrapper to the Philips Hue API
Created as a separated module for use by script.service.hue, as requested [here](https://github.com/xbmc/repo-scripts/pull/2242#discussion_r854603336)
Please double-check addon.xml, I'm not what to use for the provider-name field and <source>stage between the two code locations noted above. 
Initial Commit of latest version
=> [script.module.qhue@matrix] 2.0.1

script.service.hue/addon.xml, script.service.hue/resources/lib/ambigroup.py
- **General**
- Add-on name: Hue Service
- Add-on ID: script.service.hue
- Version number: 1.2.3
- URL: https://github.com/zim514/script.service.hue
Automate your Hue lights with Kodi. Create multi-room scenes that run when you Play, Pause or Stop media playback. Create and delete multi-room scenes from add-on settings then select which to apply for different Playback events. Can use Hue's sunrise and sunset times to automatically disable the service during daytime and turn on the lights at sunset during playback. Includes Ambilight support.
v1.2.3
Fix Ambilight not initializing properly
=> [script.service.hue@matrix] 1.2.3

service.upnext/README.md, service.upnext/addon.xml, service.upnext/resources/language/resource.language.hr_hr/strings.po, service.upnext/resources/language/resource.language.ja_jp/strings.po, service.upnext/resources/language/resource.language.ko_kr/strings.po, service.upnext/resources/language/resource.language.ru_ru/strings.po, service.upnext/resources/language/resource.language.sv_se/strings.po, service.upnext/resources/language/resource.language.zh_tw/strings.po, service.upnext/resources/lib/api.py, service.upnext/resources/lib/monitor.py, service.upnext/resources/lib/playbackmanager.py, service.upnext/resources/lib/player.py, service.upnext/resources/lib/playitem.py, service.upnext/resources/skins/default/1080i/script-upnext-upnext.xml
- **General**
- Version number: 1.1.8+matrix.1
v1.1.8 (2022-09-13)
- Never ask if Still Watching? if playedInARow is 0
- Still Watching? checks number of plays not number+1
v1.1.7 (2022-09-03)
- Update check for filename of multi-part episodes
- Check for physical disc or disc image being played
- Translation update to Russian
- Fix CI workflow
v1.1.6 (2022-03-07)
- Fix for missing mediatype …
=> [service.upnext@matrix] 1.1.8+matrix.1

script.module.phate89/addon.xml, script.module.phate89/changelog.txt, script.module.phate89/lib/phate89lib/kodiutils.py
- **General**
- Add-on name: phate89 helper module
- Add-on ID: script.module.phate89
- Version number: 1.2.2+matrix.1
- URL: https://github.com/phate89/script.module.phate89
Helper module for addons
=> [script.module.phate89@matrix] 1.2.2+matrix.1

script.module.phate89/addon.xml, script.module.phate89/changelog.txt, script.module.phate89/lib/phate89lib/kodiutils.py
- **General**
- Add-on name: phate89 helper module
- Add-on ID: script.module.phate89
- Version number: 1.2.2
- Kodi/repository version: jarvis
- URL: https://github.com/phate89/script.module.phate89
Helper module for addons
=> [script.module.phate89@jarvis] 1.2.2

targets.cfg
Omega Repo
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboard). You can create your own account as well to continuously monitor your python coding before submitting …
=> add omega repo

script.module.infotagger/addon.xml, script.module.infotagger/resources/modules/infotagger/listitem.py
Adds a setter function for setResumePoint() to use infoproperties dictionary with backwards compatibility for depreciated ResumeTime and TotalTime properties …
=> script.module.infotagger 0.0.5

service.cronxbmc/addon.xml, service.cronxbmc/resources/lib/cron/main.py
Fixes issue with deprecated `xbmc.translatePath`. It works in Matrix but not Nexus, this will work for both.  …
=> [service.cronxbmc] 0.1.7

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/resources/versions.txt
- **General**
- Add-on name: Version Check
- Add-on ID: service.xbmc.versioncheck
- Version number: 0.5.28+matrix.1
- URL: https://github.com/XBMC-Addons/service.xbmc.versioncheck
Kodi Version Check only supports a number of platforms/distros as releases may differ between them. For more information visit the kodi.tv website.
- add Kodi 20.1 release
- Update translations from Weblate
=> [service.xbmc.versioncheck@matrix] 0.5.28+matrix.1

service.xbmc.versioncheck/addon.xml, service.xbmc.versioncheck/resources/versions.txt
- **General**
- Add-on name: Version Check
- Add-on ID: service.xbmc.versioncheck
- Version number: 0.5.28
- URL: https://github.com/XBMC-Addons/service.xbmc.versioncheck
Kodi Version Check only supports a number of platforms/distros as releases may differ between them. For more information visit the kodi.tv website.
- add Kodi 20.1 release
- Update translations from Weblate
=> [service.xbmc.versioncheck@leia] 0.5.28

service.autostop/addon.xml, service.autostop/changelog.txt, service.autostop/common.py, service.autostop/resources/language/resource.language.en_gb/strings.po, service.autostop/resources/settings.xml
v1.0.6 is a minor update to add a setting which allows the sleep timer to be reset after the addon stops playback. 
- [ X] Each add-on submission should be a single commit with using the following style: [script.foo.bar] 1.0.0
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practise …
=> [service.autostop] 1.0.6

script.metadata.editor/addon.xml, script.metadata.editor/resources/language/resource.language.de_DE/strings.po, script.metadata.editor/resources/lib/helper.py, script.metadata.editor/resources/lib/nfo_updater.py
…mcvfs, correct spelling for german language, bump version.
Fix deprecated xbmc.translatePath to xbmcvfs.translatePath. This made the addon working in Nexus again. Additional fix some spelling in german language string and bump version from 3.0.1 to 3.0.2
- This add-on repository has automated code guideline check which …
=> [script.metadata.editor] 3.0.1

service.libraryautoupdate/addon.xml, service.libraryautoupdate/resources/lib/service.py
The service.libraryautoupdate plugin performs a connectivity check before scanning the library. Previously, this check fetched `www.google.com`, which is inappropriate for a connection check.
This commit fixes the problem by fetching a static connectivity check page, which returns a 204 status code with an empty response.
=> [service.libraryautoupdate] 1.2.4

service.subtitles.shooter/addon.xml, service.subtitles.shooter/service.py
fixed: function xbmc.translatePath was removed in Kodi 20
=> [service.subtitles.shooter] 2.0.1

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/inputstreamhelper/config.py, script.module.inputstreamhelper/lib/inputstreamhelper/utils.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm_chromeos.py, script.module.inputstreamhelper/resources/language/resource.language.en_gb/strings.po
- **General**
- Version number: 0.6.1+matrix.1
v0.6.1 (2023-05-30)
- Performance improvements on Linux ARM
- This will be the last release for Python 2 i.e. Kodi 18 (Leia) and below. The next release will require Python 3 and Kodi 19 (Matrix) or higher.
v0.6.0 (2023-05-03)
- Initial support for AARCH64 Linux
- Initial support for AARCH64 Macs
- New option to install a specific version on most platforms
v0.5.10 (2022-04-18)
- Fix automatic submission of release
- …
=> [script.module.inputstreamhelper@matrix] 0.6.1+matrix.1

script.module.inputstreamhelper/README.md, script.module.inputstreamhelper/addon.xml, script.module.inputstreamhelper/lib/inputstreamhelper/config.py, script.module.inputstreamhelper/lib/inputstreamhelper/utils.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py, script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm_chromeos.py, script.module.inputstreamhelper/resources/language/resource.language.en_gb/strings.po
- **General**
- Version number: 0.6.1
v0.6.1 (2023-05-30)
- Performance improvements on Linux ARM
- This will be the last release for Python 2 i.e. Kodi 18 (Leia) and below. The next release will require Python 3 and Kodi 19 (Matrix) or higher.
v0.6.0 (2023-05-03)
- Initial support for AARCH64 Linux
- Initial support for AARCH64 Macs
- New option to install a specific version on most platforms
v0.5.10 (2022-04-18)
- Fix automatic submission of release
- Update German …
=> [script.module.inputstreamhelper@krypton] 0.6.1

script.copacetic.helper/README.md, script.copacetic.helper/addon.xml, script.copacetic.helper/resources/lib/script/actions.py, script.copacetic.helper/resources/lib/service/art.py, script.copacetic.helper/resources/lib/service/monitor.py
**1.0.5**
- Added script for easily re-ordering widgets in Copacetic settings screen
**1.0.4**
- Return dominant colour for home widgets when clearlogo cropper is active
- Added fanart multiart to backgtround slideshows
- This add-on repository has automated code guideline check which could help you improve your coding. …
=> script.copacetic.helper 1.0.5

script.module.requests/README.md, script.module.requests/addon.xml, script.module.requests/lib/requests/__init__.py, script.module.requests/lib/requests/__version__.py, script.module.requests/lib/requests/_internal_utils.py, script.module.requests/lib/requests/adapters.py, script.module.requests/lib/requests/api.py, script.module.requests/lib/requests/auth.py, script.module.requests/lib/requests/certs.py, script.module.requests/lib/requests/compat.py, script.module.requests/lib/requests/cookies.py, script.module.requests/lib/requests/exceptions.py, script.module.requests/lib/requests/help.py, script.module.requests/lib/requests/hooks.py, script.module.requests/lib/requests/models.py, script.module.requests/lib/requests/packages.py, script.module.requests/lib/requests/sessions.py, script.module.requests/lib/requests/status_codes.py, script.module.requests/lib/requests/structures.py, script.module.requests/lib/requests/utils.py
Update requests to 2.31.0
https://github.com/psf/requests/releases/tag/v2.31.0 …
=> [script.module.requests@matrix] 2.31.0

script.video.nfl.gamepass/README.md, script.video.nfl.gamepass/addon.xml, script.video.nfl.gamepass/changelog.txt, script.video.nfl.gamepass/default.py, script.video.nfl.gamepass/resources/language/resource.language.de_de/strings.po, script.video.nfl.gamepass/resources/language/resource.language.en_gb/strings.po, script.video.nfl.gamepass/resources/language/resource.language.ja_jp/strings.po, script.video.nfl.gamepass/resources/language/resource.language.nl_nl/strings.po, script.video.nfl.gamepass/resources/language/resource.language.ru_ru/strings.po, script.video.nfl.gamepass/resources/language/resource.language.uk_ua/strings.po, script.video.nfl.gamepass/resources/lib/pigskin/pigskin.py, script.video.nfl.gamepass/resources/settings.xml
**Addon**
Name: NFL Game Pass
ID: script.video.nfl.gamepass
Version: n/a
Source: https://github.com/pigskin/kodi-gamepass
**Info**
NFL has canceled the NFL Gamepass service, making this add-on obsolete. This PR updates the add-on to the latest code base and marks it as broken.
=> [script.video.nfl.gamepass] 2023.07.05

script.timers/addon.xml, script.timers/resources/language/resource.language.de_de/strings.po, script.timers/resources/language/resource.language.en_gb/strings.po, script.timers/resources/lib/player/player.py, script.timers/resources/lib/timer/notification.py, script.timers/resources/lib/timer/scheduleraction.py
v3.7.0 (2023-06-30)
- If you stop explicitly playback while a start-stop-timer is running there won't be another stop action anymore when this timer runs out.
- Added workaround that streamed video (probably mpeg-dash) immediately stops after timer has started (only happened if 'seek to correct time if timer starts belatedly' is activated)
=> [script.timers] 3.7.0

script.module.libard/addon.xml, script.module.libard/lib/libardnewjsonparser.py
prevent "TypeError: argument of type 'NoneType' is not iterable" on using the plugin "plugin.video.sportschau"
=> [script.module.libard] v6.0.2

script.copacetic.helper/README.md, script.copacetic.helper/addon.xml, script.copacetic.helper/resources/lib/script/actions.py, script.copacetic.helper/resources/lib/service/monitor.py, script.copacetic.helper/resources/lib/utilities.py
- Moved director/writer/studio/genre splitting to monitoring service
=> [script.copacetic.helper 1.0.6]

script.module.codequick/addon.xml, script.module.codequick/lib/urlquick.py
- **General**
- Add-on name: CodeQuick
- Add-on ID: script.module.codequick
- Version number: 1.0.3+matrix.1
- URL: https://github.com/willforde/script.module.codequick
Codequick is a framework for kodi add-on's. The goal of this framework is to simplify add-on development. This is achieved by reducing the amount of boilerplate code to a minimum, automating tasks like route dispatching and sort method selection. Ultimately allowing the developer to focus primarily on scraping content from websites and passing it to kodi.
Removed HTTPResponse from urlquick as it did not work with requests 2.31. It was only used for type annotations anyway.
=> [script.module.codequick@matrix] 1.0.3+matrix.1

service.subtitles.legendastv/addon.xml
Marking this plugin as broken, website has ceased to exist: http://legendas.tv/
cc @andrebrait
=> [service.subtitles.legendastv] 3.0.1 (broken)

weather.metoffice/addon.xml, weather.metoffice/changelog.txt, weather.metoffice/resources/settings.xml, weather.metoffice/src/default.py, weather.metoffice/src/metoffice/constants.py, weather.metoffice/src/metoffice/properties.py, weather.metoffice/src/metoffice/utilities.py
- Added feels like calculation.
- Updated geoip providers.
=> [weather.metoffice] v4.1.0

script.timers/addon.xml, script.timers/resources/language/resource.language.de_de/strings.po, script.timers/resources/language/resource.language.en_gb/strings.po, script.timers/resources/lib/contextmenu/set_quick_epg_timer.py
v3.8.0 (2023-08-06)
- Context menu quicktimer: Added dialog if item is already scheduled and ask to replace or delete
=> [script.timers] 3.8.0

script.service.playbackresumer/addon.xml, script.service.playbackresumer/changelog.txt, script.service.playbackresumer/resources/lib/player.py
- **General**
- Add-on name: Kodi Playback Resumer
- Add-on ID: script.service.playbackresumer
- Version number: 2.0.5
- URL: https://github.com/bossanova808/script.service.playbackresumer
Runs as a service and will periodically update the resume point while videos are playing, so you can re-start from where you were in the event of a crash.  It can also automatically resume a video if Kodi was shutdown while playing it. See setting to configure how often the resume point is set, and whether to automatically resume.
v2.0.5
- Fix odd reported bug with resume points (https://forum.kodi.tv/showthread.php?tid=355383&pid=3163480#pid3163480)
=> [script.service.playbackresumer@matrix] 2.0.5

script.copacetic.helper/README.md, script.copacetic.helper/addon.xml, script.copacetic.helper/resources/lib/service/art.py, script.copacetic.helper/resources/lib/service/monitor.py
**Changelog since last update:**
**1.0.8**
- Push dbid of corresponding cropped clearlogo to window prop for comparison so cropped clearlogos only show on correct listitems.
**1.0.7**
- Add tvguide to SlideShowMonitor() whitelist
- This add-on repository has automated code guideline check which could help you improve your …
=> script.copacetic.helper 1.0.8

script.service.hyperion-control/addon.xml, script.service.hyperion-control/resources/__init__.py, script.service.hyperion-control/resources/language/resource.language.de_de/strings.po, script.service.hyperion-control/resources/language/resource.language.en_gb/strings.po, script.service.hyperion-control/resources/language/resource.language.es_es/strings.po, script.service.hyperion-control/resources/language/resource.language.fr_fr/strings.po, script.service.hyperion-control/resources/language/resource.language.hu_hu/strings.po, script.service.hyperion-control/resources/language/resource.language.pl_pl/strings.po, script.service.hyperion-control/resources/lib/hyperion.py, script.service.hyperion-control/resources/lib/interfaces.py, script.service.hyperion-control/resources/lib/settings_manager.py, script.service.hyperion-control/resources/settings.xml
- **General**
- Add-on name: Hyperion Control
- Add-on ID: script.service.hyperion-control
- Version number: 20.0.1
- Kodi/repository version: nexus
- URL: https://github.com/hyperion-project/hyperion.control
Enable and disable components (like capture) of Hyperion automatically based on playing/screensaver state of Kodi[CR]-Supports auto detection of Hyperion Servers[CR]-Token authentication
20.0.1
- Removed redundant debug setting
20.0.0
- Kodi 20 (Nexus) support
- Multi instance handling
- New language: Hungarian
19.0.2
- New languages: Español, Français, Polski
19.0.1
- Kodi 19 support
- minor cleanups and corrections
1.0.1
- Fixed a crash with 3d mode @b-jesch
1.0.0
- Added support for server search
- Added support token authentication
- Fixed issue where kodi api …
=> [script.service.hyperion-control@nexus] 20.0.1

script.audio.motherearth/CHANGELOG.md, script.audio.motherearth/README.md, script.audio.motherearth/addon.xml, script.audio.motherearth/motherearth.py, script.audio.motherearth/resources/language/resource.language.en_gb/strings.po, script.audio.motherearth/resources/settings.xml
added Mother Earth Jazz channel …
=> [script.audio.motherearth] 2.2

script.timers/addon.xml, script.timers/resources/language/resource.language.de_de/strings.po, script.timers/resources/language/resource.language.en_gb/strings.po, script.timers/resources/lib/timer/scheduler.py, script.timers/resources/lib/timer/scheduleraction.py, script.timers/resources/lib/timer/timer.py, script.timers/resources/settings.xml
v3.9.0 (2023-11-11)
- Add new system action 'restart Kodi'
- Add new extra feature to prevent display off when audio is playing
- Bugfix: Prevent exception in fader context
=> [script.timers] 3.9.0

service.languagepreferencemanager/addon.xml, service.languagepreferencemanager/changelog.txt, service.languagepreferencemanager/resources/lib/prefutils.py
Version 1.0.2
- Fix 10sec latency on subs display and possible few lines lost - at video start or when switching audio.
- Forced sub tracks : check also subtitle field "isforced" in case field "name" is empty or misspelled.
- This add-on repository has automated code guideline check which could help you improve your …
=> [service.languagepreferencemanager] 1.0.2

script.module.dropbox_auth/LICENSE.txt, script.module.dropbox_auth/addon.xml, script.module.dropbox_auth/authenticate.py, script.module.dropbox_auth/resources/language/resource.language.de_de/strings.po, script.module.dropbox_auth/resources/language/resource.language.en_gb/strings.po, script.module.dropbox_auth/resources/utils.py
The addon was already part of Kodi Matrix, see #1825. I just had to [change one line](https://github.com/SchapplM/xbmc-addon-dropboxauth/commit/8ab4d7e6448cd72b9b420c8e301a3a71a18da285) and [updated the dependencies](https://github.com/SchapplM/xbmc-addon-dropboxauth/commit/343515344d5409d93b1d8590689718ff2320e7cd) for Kodi Nexus.
=> [script.module.dropbox_auth] 10.3.1

weather.gismeteo/addon.xml, weather.gismeteo/changelog.txt, weather.gismeteo/default.py, weather.gismeteo/resources/language/resource.language.de_de/strings.po, weather.gismeteo/resources/libs/__init__.py, weather.gismeteo/resources/libs/gismeteo.py, weather.gismeteo/resources/libs/simpleweather/webclient.py
- **General**
- Version number: 0.6.4
v0.6.4 (2023-10-30)[CR]- Adapted to changes in the service API[CR]- Added German translation (kyoforkshomebrews)[CR][CR]v0.6.3 (2021-09-27)[CR]- Fixed identified bugs[CR][CR]v0.6.2 (2021-05-31)[CR]- Updated compatibility with Kodi 19[CR]- Added Icelandic translation (sveinki)[CR][CR]v0.6.1 (2021-04-03)[CR]- SimplePlugin 3 module moved into external addon[CR]- Small changes in the add-on structure [CR]- Added French translation (DavidHenryThoreau)[CR]- Added Swedish translation (Sopor)
=> [weather.gismeteo@krypton] 0.6.4

weather.ozweather/README.md, weather.ozweather/addon.xml, weather.ozweather/changelog.txt, weather.ozweather/resources/lib/store.py
- **General**
- Version number: 2.1.0
2.1.0
- Fix light_rain icon & update BOM radar list
=> [weather.ozweather@matrix] 2.1.0

script.module.urllib3/addon.xml, script.module.urllib3/lib/urllib3/_collections.py, script.module.urllib3/lib/urllib3/_version.py, script.module.urllib3/lib/urllib3/connectionpool.py, script.module.urllib3/lib/urllib3/contrib/securetransport.py, script.module.urllib3/lib/urllib3/poolmanager.py, script.module.urllib3/lib/urllib3/request.py, script.module.urllib3/lib/urllib3/util/retry.py
update urllib3 to 1.26.18
https://github.com/urllib3/urllib3/releases/tag/1.26.18 …
=> [script.module.urllib3@krypton] 1.26.18

script.subtitles.zimukux/addon.xml, script.subtitles.zimukux/resources/language/resource.language.en_GB/strings.po, script.subtitles.zimukux/resources/language/resource.language.zh_CN/strings.po, script.subtitles.zimukux/resources/lib/sub_provider_service.py, script.subtitles.zimukux/resources/lib/zimuku_agent.py, script.subtitles.zimukux/resources/settings.xml
=> [script.subtitles.zimukux] 0.2.1

script.service.next-episode/addon.xml, script.service.next-episode/libs/__init__.py, script.service.next-episode/libs/addon.py, script.service.next-episode/libs/exception_logger.py, script.service.next-episode/libs/gui.py, script.service.next-episode/libs/logger.py, script.service.next-episode/libs/medialibrary.py, script.service.next-episode/libs/monitoring.py, script.service.next-episode/libs/nextepisode.py, script.service.next-episode/libs/simple_requests.py, script.service.next-episode/libs/utils.py, script.service.next-episode/main.py, script.service.next-episode/resources/settings.xml, script.service.next-episode/service.py
- **General**
- Version number: 1.2.6
- URL: https://github.com/romanvm/next-episode-kodi
1.2.6:
- Removed Python 2 compatibility
1.2.5:
- Fixed crashes when movies do not have IMDB ID.
=> [script.service.next-episode@matrix] 1.2.6

weather.ozweather/addon.xml, weather.ozweather/changelog.txt, weather.ozweather/resources/lib/forecast.py
- **General**
- Version number: 2.1.1
2.1.1
- Add Latitude and Longitude to Window data for skins that display 'season' using (arguably dubious) logic
=> [weather.ozweather@matrix] 2.1.1

script.service.checkpreviousepisode/addon.xml, script.service.checkpreviousepisode/changelog.txt, script.service.checkpreviousepisode/resources/lib/player.py
- **General**
- Add-on name: Kodi Check Previous Episode
- Add-on ID: script.service.checkpreviousepisode
- Version number: 0.4.6
- URL: https://github.com/bossanova808/script.service.checkpreviousepisode
This service helps prevent spoilers by checking if the previous episode in a series has been watched. If not, it will pause playback and warn you.  Specific shows can be marked to be ignored if episode order does not matter.
v0.4.6
- Ignore shows that have already been decided on (i.e. those with a non-zero resume point)
=> [script.service.checkpreviousepisode@matrix] 0.4.6

service.iptv.manager/CHANGELOG.md, service.iptv.manager/addon.xml, service.iptv.manager/resources/lib/modules/iptvsimple.py
* **Add-on name:** IPTV Manager
* **Add-on ID:** service.iptv.manager
* **Version number:** 0.2.4+matrix.1
* **Kodi/repository version:** matrix
* **Code location:** https://github.com/add-ons/service.iptv.manager
* **Description:** IPTV Manager integrates IPTV channels from other add-ons in the Kodi TV and Radio menus.
* **Owners:** @michaelarnauts & @peno64
**v0.2.4 (2023-12-02)**
* Fix for Configure IPTV automatically.
* https://github.com/add-ons/service.iptv.manager/compare/v0.2.3...v0.2.4
- Kodi …
=> [service.iptv.manager] 0.2.4+matrix.1

service.iptv.manager/CHANGELOG.md, service.iptv.manager/addon.xml, service.iptv.manager/resources/lib/modules/iptvsimple.py
fix for bad commit from someone who wasn't author of addon
=> [service.iptv.manager] v0.2.5

script.lockandenergycontrol/addon.py, script.lockandenergycontrol/addon.xml, script.lockandenergycontrol/resources/language/resource.language.de_de/strings.po, script.lockandenergycontrol/resources/language/resource.language.en_gb/strings.po, script.lockandenergycontrol/resources/settings.xml
v1.1.0 (2023-11-30)
- New feature to prevent display off when audio is playing
=> [script.lockandenergycontrol] 1.1.0

script.copacetic.helper/README.md, script.copacetic.helper/addon.xml, script.copacetic.helper/resources/lib/service/art.py, script.copacetic.helper/resources/lib/service/monitor.py, script.copacetic.helper/resources/lib/service/player.py, script.copacetic.helper/resources/lib/service/settings.py
**1.0.11**
- Removed visualisation waveform setting from list of settings changed by SettingsMonitor
**1.0.11**
- Reordered addon.xml back to how it was before 1.0.9 due to removal of script.copacetic.helper as a plugin source selectable for widgets.
- Enhanced Slideshow_Monitor class so that it can now fetch fanarts from containers with plugin sources when they are available then use these fanarts in the custom background slideshow. In this way, you can use a custom path to populate a global custom fanart slideshow even without any content in your local library
**1.0.10**
- read_fanart() method added in 1.0.10 now triggers on services monitor initialise rather than the first time that the SlideShow monitor is run so it should display backgrounds slightly quicker
**1.0.10**
- Custom path …
=> script.copacetic.helper 1.0.12

script.service.checkpreviousepisode/addon.xml, script.service.checkpreviousepisode/changelog.txt, script.service.checkpreviousepisode/resources/lib/common.py, script.service.checkpreviousepisode/resources/lib/monitor.py, script.service.checkpreviousepisode/resources/lib/player.py
- **General**
- Add-on name: Kodi Check Previous Episode
- Add-on ID: script.service.checkpreviousepisode
- Version number: 0.4.7
- URL: https://github.com/bossanova808/script.service.checkpreviousepisode
This service helps prevent spoilers by checking if the previous episode in a series has been watched. If not, it will pause playback and warn you.  Specific shows can be marked to be ignored if episode order does not matter.
v0.4.7 Add Window Property so skinners can dress up the dialog
=> [script.service.checkpreviousepisode@matrix] 0.4.7

service.languagepreferencemanager/addon.xml, service.languagepreferencemanager/changelog.txt, service.languagepreferencemanager/resources/lib/prefparser.py, service.languagepreferencemanager/resources/lib/prefutils.py
- Fix and simplify SignsSongs subtagging (was colliding with language codes subtagging ie. pt-br). Thanks to BrutuZ!
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-scripts/dashboar …
=> [service.languagepreferencemanager] 1.0.4

script.service.playbackresumer/addon.xml, script.service.playbackresumer/changelog.txt, script.service.playbackresumer/resources/lib/common.py, script.service.playbackresumer/resources/lib/player.py, script.service.playbackresumer/resources/lib/store.py
- **General**
- Add-on name: Kodi Playback Resumer
- Add-on ID: script.service.playbackresumer
- Version number: 2.0.6
- URL: https://github.com/bossanova808/script.service.playbackresumer
Runs as a service and will periodically update the resume point while videos are playing, so you can re-start from where you were in the event of a crash.  It can also automatically resume a video if Kodi was shutdown while playing it. See setting to configure how often the resume point is set, and whether to automatically resume.
v2.0.6 - Add support for non-library videos
=> [script.service.playbackresumer@matrix] 2.0.6

script.module.jurialmunkey/addon.xml, script.module.jurialmunkey/resources/language/resource.language.fi_fi/strings.po, script.module.jurialmunkey/resources/modules/jurialmunkey/bcache.py, script.module.jurialmunkey/resources/modules/jurialmunkey/dialog.py, script.module.jurialmunkey/resources/modules/jurialmunkey/futils.py, script.module.jurialmunkey/resources/modules/jurialmunkey/jsnrpc.py, script.module.jurialmunkey/resources/modules/jurialmunkey/litems.py, script.module.jurialmunkey/resources/modules/jurialmunkey/logger.py, script.module.jurialmunkey/resources/modules/jurialmunkey/modimp.py, script.module.jurialmunkey/resources/modules/jurialmunkey/parser.py, script.module.jurialmunkey/resources/modules/jurialmunkey/reqapi.py, script.module.jurialmunkey/resources/modules/jurialmunkey/scache.py, script.module.jurialmunkey/resources/modules/jurialmunkey/thread.py, script.module.jurialmunkey/resources/modules/jurialmunkey/window.py
Add some additional shared functions used across my addons …
=> [script.module.jurialmunkey] 0.1.18

script.copacetic.helper/README.md, script.copacetic.helper/addon.xml, script.copacetic.helper/resources/lib/script/actions.py, script.copacetic.helper/resources/lib/service/art.py, script.copacetic.helper/resources/lib/service/monitor.py, script.copacetic.helper/resources/lib/utilities.py
**1.0.18**
- Added subtitle_limiter() script, which sets subtitles to the first stream in the desired language if it's available and then toggles between this subtitle stream and 'off'. If the preferred language stream is not available it will toggle through all available subtitles instead.
- 
- This add-on repository has …
=> [script.copacetic.helper] 1.1.1

script.timers/addon.xml, script.timers/resources/lib/player/player.py, script.timers/resources/lib/timer/scheduler.py
v3.9.1 (2024-06-30)
- Bugfix: Prevent exception after changing already running non-fading-timer to fading-timer
=> [script.timers] 3.9.1

script.service.hyperion/addon.xml, script.service.hyperion/resources/lib/monitor.py
- **General**
- Add-on name: Hyperion Ambilight
- Add-on ID: script.service.hyperion
- Version number: 20.0.2
- Kodi/repository version: nexus
- URL: https://github.com/hyperion-project/hyperion.kodi
Hyperion is an opensource Bias or Ambient Lighting implementation which runs on many devices.[CR]This addon sends through the Hyperion PROTO-port your current picture to your Hyperion daemon for further processing like black border detection or smoothing.
20.0.2
- Python lower than 3.10 compatibility
20.0.1
- Clean-ups
- Handle missing PIL library on Android
20.0.0
- Kodi 20 (Nexus) support
- New languages: Hebrew, Italian
=> [script.service.hyperion@nexus] 20.0.2

service.subtitles.rvm.addic7ed/addic7ed/actions.py, service.subtitles.rvm.addic7ed/addic7ed/addon.py, service.subtitles.rvm.addic7ed/addic7ed/exception_logger.py, service.subtitles.rvm.addic7ed/addic7ed/exceptions.py, service.subtitles.rvm.addic7ed/addic7ed/parser.py, service.subtitles.rvm.addic7ed/addic7ed/simple_requests.py, service.subtitles.rvm.addic7ed/addic7ed/utils.py, service.subtitles.rvm.addic7ed/addic7ed/webclient.py, service.subtitles.rvm.addic7ed/addon.xml, service.subtitles.rvm.addic7ed/main.py
- **General**
- Version number: 3.2.0
3.2.0:
- Removed Python 2 compatibility.
=> [service.subtitles.rvm.addic7ed@matrix] 3.2.0
